# Inspecting intertexts in a micro level

I included some interesting combinations, but many more are possible!

## Loading in the needed librarires

In [1]:
import glob
import os
from collections import Counter
from itertools import combinations, product

import numpy as np
np.random.seed(18012023)

import pandas as pd
pd.set_option('display.max_colwidth', 0)

import seaborn as sb

from sklearn.metrics import pairwise_distances
import lxml.etree
from scipy.spatial.distance import pdist, squareform
from tqdm import tqdm
from sklearn.feature_extraction.text import TfidfVectorizer

import matplotlib.pyplot as plt
import matplotlib
plt.rcParams['figure.dpi'] = 300
plt.rcParams['font.family'] = 'Arial'
from IPython.display import display

## Loading in data and metadata

In [2]:
meta_df = pd.read_excel('../data/metadata_corrected.xlsx')
meta_df = meta_df[meta_df['exclude'] != 'x']
meta_df.sample(10)

,id,title,author,provenance,date_range,genre,subgenre,exclude
49,derde_martijn,Derde Martijn,Jacob van Maerlant,cdrom-mnl,1380-1425,Lyriek,NaN,NaN
206,sinte_kunera,Sinte Kunera,NaN,cdrom-mnl,1400-1500,Epiek,Heiligenleven,NaN
59,esopet,Esopet,Calfstaf en Noydekin,cdrom-mnl,1340-1360,Epiek,Dier,NaN
235,spiegel_historiael__4_velthem__fragm_we,Spiegel historiael (P4),Lodewijk van Velthem,cdrom-mnl,1393-1402,Epiek,Historiografie,NaN
48,der_ystorien_bloeme,Der ystorien bloeme,NaN,cdrom-mnl,1340-1360,Epiek,Historiografie,NaN
191,roman_van_caesar_fragm_br,Roman van Caesar,NaN,cdrom-mnl,1300-1350,Epiek,Ridder,NaN
247,truwanten,Truwanten,NaN,cdrom-mnl,1400-1420,Dramatiek,NaN,NaN
60,vanden_vier_vingheren_ende_vanden_dume,Expositie vanden viere vingheren ende vanden dume,NaN,cdrom-mnl,1400-1420,Epiek,Didactiek,NaN
70,Floyris ende Blantseflur,Floyris ende Blantseflur,NaN,CG1,1225-1201,Epiek,Ridder,NaN
65,florigout_fragm_l,Florigout,NaN,cdrom-mnl,1375-1400,Epiek,Ridder,NaN

In [3]:
def get_verse_groups(verses, size=2, intertexts=False):
    for i in range(len(verses) - (size - 1)):
        if not intertexts:
            yield ' / '.join(verses[i : i + size])
        else:
            its = Counter(verses[i : i + size])
            if None in its:
                yield None
            elif len(its) > 1:
                yield 'overlap'
            else:
                yield list(its.keys())[0]

In [4]:
def parse_xml(fn, rm_interpol=True, rm_prose=True):
    try:
        tree = lxml.etree.parse(fn)
    except OSError:
        print(f'- Could not load {fn}')
        return None
        
    if rm_interpol:
        for interpolation in tree.xpath("//interpolation"):
            interpolation.getparent().remove(interpolation)

    if rm_prose:
        for prose in tree.xpath("//prose"):
            prose.getparent().remove(prose)

        
    for line_node in tree.iterfind('//l'):
        try:
            intertext_id = line_node.attrib['intertext']
        except KeyError:
            intertext_id = None
        
        tokens_ = line_node.attrib['tokens'].split()
        lemmas_ = []
        
        lemma_tags = [l.text for l in line_node.iterfind('.//lemma')]
        pos_tags = [p.text for p in line_node.iterfind('.//pos')]
        
        for lemma, pos in zip(lemma_tags, pos_tags):
            for l, p in zip((lemma or '').split('+'), (pos or '').split('+')):
                    if p == 'NOU-P':
                        lemmas_.append('NOU-P')
                    else:
                        lemmas_.append(l)
    
        yield tokens_, lemmas_, intertext_id

In [5]:
GROUP_SIZE = 2

titles, tokens, lemmas, intertexts = [], [], [], []

for title, group in tqdm(meta_df.groupby('title')):
    work_tokens, work_lemmas, work_intertexts = [], [], []
    
    for id_ in sorted(group['id']):
        for tok, lem, intertext_id in parse_xml(f'../data/xml_galahad_BY-split/{id_}.xml'):
            work_tokens.append(tok)
            work_lemmas.append(lem)
            work_intertexts.append(intertext_id)
    
    verse_tokens = [' '.join(v) for v in work_tokens]
    verse_lemmas = [' '.join(v) for v in work_lemmas]

    verse_group_tokens = list(get_verse_groups(verse_tokens, size=GROUP_SIZE))
    verse_group_lemmas = list(get_verse_groups(verse_lemmas, size=GROUP_SIZE))
    verse_group_intertexts = list(get_verse_groups(work_intertexts, size=GROUP_SIZE, intertexts=True))

    tokens.extend(verse_group_tokens)
    lemmas.extend(verse_group_lemmas)
    intertexts.extend(verse_group_intertexts)
    titles.extend([title] * len(verse_group_lemmas))

100%|█████████████████████████████████████████| 208/208 [00:11<00:00, 18.68it/s]

In [6]:
df = pd.DataFrame(zip(titles, tokens, lemmas, intertexts), columns=('title', 'tokens', 'lemmas', 'intertext'))

In [7]:
df

,title,tokens,lemmas,intertext
0,AB recht ende averecht,Aensiet dese vrouwen hoe si gaen / Besiet hoe haer tuten staen,aanzien deze vrouw hoe zij gaan / bezien hoe haar tuut staan,None
1,AB recht ende averecht,Besiet hoe haer tuten staen / Claer dat si hen blanketten,bezien hoe haar tuut staan / klaar dat zij zij blanketten,None
2,AB recht ende averecht,Claer dat si hen blanketten / Die cleeder soe lanc dat si hen letten,klaar dat zij zij blanketten / die kleed zo lang dat zij zij letten,None
3,AB recht ende averecht,Die cleeder soe lanc dat si hen letten / Ende sleypen hen nae al op die eerde,die kleed zo lang dat zij zij letten / en slepen zij na al op die aarde,None
4,AB recht ende averecht,Ende sleypen hen nae al op die eerde / Fi diere vuylder hoverde,en slepen zij na al op die aarde / fi die vuil hovaart,None
...,...,...,...,...
861306,Wrake van Ragisel,Nu selewi swigen van desen / Ende van enen jongelinc vord lesen,nu zullen wij zwijgen van deze / en van een jongeling voort lezen,None
861307,Wrake van Ragisel,Ende van enen jongelinc vord lesen / Die te hove nu sal comen,en van een jongeling voort lezen / die te hof nu zullen komen,None
861308,Wrake van Ragisel,Die te hove nu sal comen / Eest alsict hebbe vernomen,die te hof nu zullen komen / zijn het als zij hebben vernemen,None
861309,Wrake van Ragisel,Eest alsict hebbe vernomen / Soe salmen noch van hem sien,zijn het als zij hebben vernemen / zo zullen men nog van hij zien,None
861310,Wrake van Ragisel,Soe salmen noch van hem sien / Groet wonder hier na gescien,zo zullen men nog van hij zien / groot wonder hier na geschieden,None

In [8]:
def tokenizer(text):
    return text.replace(' / ', ' ').lower().strip().split()

def add_rhyme_column(df):
    rhyme_words = []
    for lemmas in df['lemmas']:
        rhymes = []
        for verse in lemmas.split(' / '):
            words = verse.strip().split()
            if words:  # Ensure the verse is not empty
                rhymes.append(words[-1])
            else:
                rhymes.append('')  # Use an empty string or placeholder
        rhyme_words.append(' '.join(rhymes))
    df['rhyme'] = rhyme_words
    return df

In [9]:
df = add_rhyme_column(df)
df.head()

,title,tokens,lemmas,intertext,rhyme
0,AB recht ende averecht,Aensiet dese vrouwen hoe si gaen / Besiet hoe haer tuten staen,aanzien deze vrouw hoe zij gaan / bezien hoe haar tuut staan,None,gaan staan
1,AB recht ende averecht,Besiet hoe haer tuten staen / Claer dat si hen blanketten,bezien hoe haar tuut staan / klaar dat zij zij blanketten,None,staan blanketten
2,AB recht ende averecht,Claer dat si hen blanketten / Die cleeder soe lanc dat si hen letten,klaar dat zij zij blanketten / die kleed zo lang dat zij zij letten,None,blanketten letten
3,AB recht ende averecht,Die cleeder soe lanc dat si hen letten / Ende sleypen hen nae al op die eerde,die kleed zo lang dat zij zij letten / en slepen zij na al op die aarde,None,letten aarde
4,AB recht ende averecht,Ende sleypen hen nae al op die eerde / Fi diere vuylder hoverde,en slepen zij na al op die aarde / fi die vuil hovaart,None,aarde hovaart

In [10]:
optim_vs = 7000
optim_rw = 0.1693877551020408
optim_th = 0.42202047865566794

In [11]:
vec = TfidfVectorizer(max_features=optim_vs, min_df=2,
                      tokenizer=tokenizer, token_pattern=None).fit(df['lemmas'])

## Nearest neighbors

In [12]:
def nearest_verses(title1, title2, base_df, vectorizer, prop_filt=2, rhyme_weight=.15):
    A = base_df[base_df['title'] == title1]
    B = base_df[base_df['title'] == title2]
    
    AX = vec.transform(A['lemmas']) + rhyme_weight * vec.transform(A['rhyme'])
    BX = vec.transform(B['lemmas']) + rhyme_weight * vec.transform(B['rhyme'])
    
    nearest = []
    for i, ax in enumerate(AX):
        distances = pairwise_distances(ax, BX, metric='cosine').flatten()
        top_i = distances.argsort()[0]
        nearest.append((A.iloc[i]['tokens'], B.iloc[top_i]['tokens'],
                        A.iloc[i]['lemmas'], B.iloc[top_i]['lemmas'],
                        A.iloc[i]['title'], B.iloc[top_i]['title'],
                        A.iloc[i]['intertext'], B.iloc[top_i]['intertext'],
                        distances[top_i]))

    nearest = pd.DataFrame(nearest,
                           columns=['tokens1', 'tokens2', 'lemmas1', 'lemmas2',
                                    'title1', 'title2', 'intertext1', 'intertext2',
                                    'distance'])

    nearest = nearest[nearest['title1'] != nearest['title2']]
    nearest = nearest[
                      (nearest['lemmas1'].str.count('NOU-P') < prop_filt) & \
                      (nearest['lemmas1'].str.count('NOU-P') < prop_filt) 
                     ]
    return nearest

## Cases Studies

In [13]:
nearest_df = nearest_verses('Boec vander wraken', 'Sidrac',
                            base_df=df, vectorizer=vec, prop_filt=2, rhyme_weight=0)
nearest_df = nearest_df.sort_values(by='distance')
nearest_df.to_excel('../figures/parallel_verses/wraken-sidrac.xlsx')
nearest_df.head(50)

,tokens1,tokens2,lemmas1,lemmas2,title1,title2,intertext1,intertext2,distance
5652,Nu seght allegader Amen / Amen,Amen segt gemeenlike / Amen,nu zeggen algader amen / amen,amen zeggen gemeenlijk / amen,Boec vander wraken,Sidrac,None,None,0.155850
12,Daer om so biddic met trouwen / Hen die dit boec selen scouwen,Ende ic bidde hem allen met trauwen / Die desen bouc selen scauwen,daar om zo bidden ik met trouw / zij die dit boek zullen schouwen,en ik bidden hij al met trouw / die deze boek zullen schouwen,Boec vander wraken,Sidrac,None,None,0.189874
5622,Amen seghet allegader Amen / Ay hoe menichwerven heb ic gheseit,Amen segt gemeenlike / Amen,amen zeggen algader amen / ai hoe menigwerf hebben ik zeggen,amen zeggen gemeenlijk / amen,Boec vander wraken,Sidrac,None,None,0.282956
1518,MI quam een out boec in de hant / Daer ic in ghescreven vant,Soe quam my een boec ter hant / Daer ic in bescreven vant,ik komen een oud boek in de hand / daar ik in schrijven vinden,zo komen ik een boek ter hand / daar ik in beschrijven vinden,Boec vander wraken,Sidrac,None,None,0.312447
5621,Des onne ons die hemelsche Vader / Amen seghet allegader Amen,Amen segt gemeenlike / Amen,des on ons die hemels vader / amen zeggen algader amen,amen zeggen gemeenlijk / amen,Boec vander wraken,Sidrac,None,None,0.338080
5083,Ghesteinte silver ende gout / Ende diere juwele menichfout,Die beter es menichfout / Danne ghesteente zelver of gout,gesteente zilver en goud / en die juweel menigvout,die goed zijn menigvout / dan gesteente zelf of goud,Boec vander wraken,Sidrac,None,None,0.361816
5464,Dats Cristus mijn Sone / Dien ic hebbe allene,Dat God ende ghi allene / Enen sone hebt gemene,dat zijn NOU-P mijn zoon / dat ik hebben alleen,dat NOU-P en gij alleen / een zoon hebben menen,Boec vander wraken,Sidrac,None,None,0.370025
5465,Dien ic hebbe allene / Met sinen Vader ghemene,Dat God ende ghi allene / Enen sone hebt gemene,dat ik hebben alleen / met zijn vader menen,dat NOU-P en gij alleen / een zoon hebben menen,Boec vander wraken,Sidrac,None,None,0.372599
2232,Armelus dese grote here / Minde die vrouwe so zere,Die dese vrouwe niet en mint / Die de Vader alsoe minde,NOU-P deze groot heer / minnen die vrouwe zo zeer,die deze vrouwe niet ne minnen / die de vader alzo minnen,Boec vander wraken,Sidrac,None,None,0.393463
2777,Dat selen die sijn waerlike / Die verdient hebben dat hemelrike,Dat overlijt soe cortelike / Verdienen souden hemelrike,dat zullen die zijn waarlijk / die verdienen hebben dat hemelrijk,dat overlijd zo kortelijk / verdienen zullen hemelrijk,Boec vander wraken,Sidrac,None,None,0.414776
2778,Die verdient hebben dat hemelrike / Oec salmen kinnen te waren,Dat overlijt soe cortelike / Verdienen souden hemelrike,die verdienen hebben dat hemelrijk / ook zullen men kennen te zijn,dat overlijd zo kortelijk / verdienen zullen hemelrijk,Boec vander wraken,Sidrac,None,None,0.417488
2941,Ende draghen in die stede / Deser werelt ydelhede,Daer anders niet inne en leit / Dan der werelt ydelheit,en dragen in die stede / deze wereld ijdelheid,daar anders niet in ne liggen / dan de wereld ijdelheid,Boec vander wraken,Sidrac,None,None,0.427108
2475,Dese begheren te haren rade / Alle die liede vroech ende spade,Ende troest van allen goeden rade / An leren mach vroech ende spade,deze begeren te haar raad / al die lieden vroeg en spade,en troosten van al goed raad / aan leren mogen vroeg en spade,Boec vander wraken,Sidrac,None,None,0.432168
3467,Ende oec alle weldaet mede / Alsoet van rechte es sijn sede,Dit sal van rechte sijn sine sede / Alsoe alse sinte Jeronimus dede,en ook al weldaad mede / alzo het van rechte zijn zijn zede,dit zullen van rechte zijn zijn zede / alzo als NOU-P NOU-P doen,Boec vander wraken,Sidrac,None,None,0.436361
4283,Mids enen onghelovighen man / Die der Tartaren coninc sal wesen,Die Sydrac leerde die vroede / Eenen onghelovighen coninc,mits een ongelovig man / die de tartaar koning zullen wezen,die sidrac leren die vroed / een ongelovig koning,Boec vander wraken,Sidrac,None,None,0.436894
5068,Si en vonden meer no min / Manne kindere no wive,Want sy den tyt verliesen / Die nemmermeer no wijf no man,zij ne vinden meer noch min / man kind noch wijf,want zij de tijd verliezen / die nimmermeer noch wijf noch man,Boec vander wraken,Sidrac,None,None,0.437347
5282,Hoe si Gode ghesachten mochten / Dedij den raet dat quamen,Die anders doen sy doen quaet / Hoets hem elc dats mijn raet,hoe zij NOU-P gezachten mogen / doen hij de raad dat komen,die anders doen zij doen kwaad / hoe zij hij elk dat zijn mijn raad,Boec vander wraken,Sidrac,None,None,0.437933
5651,Daer wi moeten comen tsamen / Nu seght allegader Amen,Amen segt gemeenlike / Amen,daar wij moeten komen samen / nu zeggen algader amen,amen zeggen gemeenlijk / amen,Boec vander wraken,Sidrac,None,None,0.463620
2567,Omdat Hi die quade mint / Want si Gode en minnen twint,Die dese vrouwe niet en mint / Die de Vader alsoe minde,omdat hij die kwaad minnen / want zij NOU-P ne minnen twint,die deze vrouwe niet ne minnen / die de vader alzo minnen,Boec vander wraken,Sidrac,None,None,0.464196
13,Hen die dit boec selen scouwen / Dat si studeren met sinne,Die desen bouc selen scauwen / Dat sij Gode bidden vor mi,zij die dit boek zullen schouwen / dat zij studeren met zin,die deze boek zullen schouwen / dat zij NOU-P bidden voor ik,Boec vander wraken,Sidrac,None,None,0.469587
502,Anders dan in Hem allene / Dander ere die Hi dede,Anders dant dauctor ute gaf / Die anders doen sy doen quaet,anders dan in hij alleen / de ander eer die hij doen,anders dan het de autor uiten geven / die anders doen zij doen kwaad,Boec vander wraken,Sidrac,None,None,0.472630
993,Here no knape wijf no man / Ende so wie vanden heren,Want sy den tyt verliesen / Die nemmermeer no wijf no man,heer noch knaap wijf noch man / en zo wie van de heer,want zij de tijd verliezen / die nimmermeer noch wijf noch man,Boec vander wraken,Sidrac,None,None,0.473096
4072,EEn boecsken quam mi ter hant / Daer ic in ghescreven vant,Soe quam my een boec ter hant / Daer ic in bescreven vant,een boekje komen ik ter hand / daar ik in schrijven vinden,zo komen ik een boek ter hand / daar ik in beschrijven vinden,Boec vander wraken,Sidrac,None,None,0.478420
3920,Van dien van Cartago / Die hem alsoe ghinghen toe,Van Pertelpeuse van Amedase / Van Troyen ende van Fierenbrase,van dat van NOU-P / die hij alzo gaan toegespreken,van partelpeuze van NOU-P / van NOU-P en van NOU-P,Boec vander wraken,Sidrac,None,None,0.481520
3468,Alsoet van rechte es sijn sede / Sulc wreect oec dat verstaet,Dit sal van rechte sijn sine sede / Alsoe alse sinte Jeronimus dede,alzo het van rechte zijn zijn zede / zulk wreken ook dat verstaat,dit zullen van rechte zijn zijn zede / alzo als NOU-P NOU-P doen,Boec vander wraken,Sidrac,None,None,0.482132
285,Noch so seghet die Gods Sone fijn / Metten heylighen monde sijn,Beide die heilege Geest ende die Sone / Die een God sijn metten Vader,nog zo zeggen die God zoon fijn / met de heilig mond zijn,beide die heilig geest en die zoon / die een god zijn met de vader,Boec vander wraken,Sidrac,None,None,0.483340
2066,Starc ende stout groet van machte / Dese was van Sems gheslachte,Dese Sydrac was van Gode vercoren / Ende van den geslachte van Japhette geboren,sterk en stout groot van macht / deze zijn van NOU-P geslacht,deze sidrac zijn van NOU-P verkiezen / en van de geslacht van NOU-P geboren,Boec vander wraken,Sidrac,None,None,0.487478
2233,Minde die vrouwe so zere / Dat hi haer die stat van Romen gaf,Die dese vrouwe niet en mint / Die de Vader alsoe minde,minnen die vrouwe zo zeer / dat hij zij die stad van NOU-P geven,die deze vrouwe niet ne minnen / die de vader alzo minnen,Boec vander wraken,Sidrac,None,None,0.487835
1680,Dat van Gode sal sijn gheboren / Sal die Gods Sone sijn vercoren,Dese Sydrac was van Gode vercoren / Ende van den geslachte van Japhette geboren,dat van NOU-P zullen zijn geboren / zullen die God zoon zijn verkiezen,deze sidrac zijn van NOU-P verkiezen / en van de geslacht van NOU-P geboren,Boec vander wraken,Sidrac,None,None,0.487892
3796,Ende omt recht diet wel besiet / Es hi prince ende anders niet,Aldus eest ende anders niet / Die de dinc te rechte besiet,en om het recht die het wel bezien / zijn hij prince en anders niet,aldus zijn het en anders niet / die de ding te rechte bezien,Boec vander wraken,Sidrac,None,None,0.488487
522,En waert van boven niet verleent di / Dats van God ende oec van,Van Pertelpeuse van Amedase / Van Troyen ende van Fierenbrase,ne zijn het van boven niet verlenen du / dat zijn van NOU-P en ook van,van partelpeuze van NOU-P / van NOU-P en van NOU-P,Boec vander wraken,Sidrac,None,None,0.489481
2476,Alle die liede vroech ende spade / Dese sijn van groten love,Ende troest van allen goeden rade / An leren mach vroech ende spade,al die lieden vroeg en spade / deze zijn van groot lof,en troosten van al goed raad / aan leren mogen vroeg en spade,Boec vander wraken,Sidrac,None,None,0.490153
3759,In segghe dan niet dat / Ic en hebbe in enegher stat,Dat en dedic omme gene dinc / Anders dan dat ic niet en woude,ik ne zeggen dan niet dat / ik ne hebben in enig stad,dat ne doen ik om geen ding / anders dan dat ik niet ne willen,Boec vander wraken,Sidrac,None,None,0.499978
4251,Van discorde van onvreden / Van symonien van andren dinghen,Van Pertelpeuse van Amedase / Van Troyen ende van Fierenbrase,van discoord van onvrede / van symonie van ander ding,van partelpeuze van NOU-P / van NOU-P en van NOU-P,Boec vander wraken,Sidrac,None,None,0.500729
3919,Een zwaer orloghe ende groet / Van dien van Cartago,Van Pertelpeuse van Amedase / Van Troyen ende van Fierenbrase,een zwaar oorlog en groot / van dat van NOU-P,van partelpeuze van NOU-P / van NOU-P en van NOU-P,Boec vander wraken,Sidrac,None,None,0.500975
4042,Persem ende selfvuldicheit / Ende oec alle ydelheit,Daer anders niet inne en leit / Dan der werelt ydelheit,persem en zelfvuldigheid / en ook al ijdelheid,daar anders niet in ne liggen / dan de wereld ijdelheid,Boec vander wraken,Sidrac,None,None,0.501328
3656,In Tripertita hystoria / Dats een boec wildijt weten,In dichte niet dat weet wale / Dien boec ute altemale,in tripertita hystoria / dat zijn een boek willen weten,in dicht niet dat weten wel / dat boek uit altemaal,Boec vander wraken,Sidrac,None,None,0.503040
3570,Dier hi dicke nam haer goet / Ende verteret vroech ende spade,Ende troest van allen goeden rade / An leren mach vroech ende spade,die hij dik nemen haar goed / en verteren vroeg en spade,en troosten van al goed raad / aan leren mogen vroeg en spade,Boec vander wraken,Sidrac,None,None,0.503999
5000,Die de hertoghe heeft ghedaen / Vanden here van Valkenbosch nu,Alsoe sijn geesten vanden heren / Van Pertelpeuse van Amedase,die de hertog hebben doen / van de heer van NOU-P nu,alzo zijn geest van de heer / van partelpeuze van NOU-P,Boec vander wraken,Sidrac,None,None,0.504538
523,Dats van God ende oec van / Den keyser van wies weghen dan,Van Pertelpeuse van Amedase / Van Troyen ende van Fierenbrase,dat zijn van NOU-P en ook van / de keizer van wes wegen dan,van partelpeuze van NOU-P / van NOU-P en van NOU-P,Boec vander wraken,Sidrac,None,None,0.506025
1170,Om den ghemeynen orber vander stede / Dat sal van rechte sijn sede,Dit sal van rechte sijn sine sede / Alsoe alse sinte Jeronimus dede,om de gemeen oorbaar van de stede / dat zullen van rechte zijn zede,dit zullen van rechte zijn zijn zede / alzo als NOU-P NOU-P doen,Boec vander wraken,Sidrac,None,None,0.508475
2108,Ende elc alsic bescreven vant / Ende hadde maer een roede in de hant,Soe quam my een boec ter hant / Daer ic in bescreven vant,en elk als ik beschrijven vinden / en hebben maar een roede in de hand,zo komen ik een boek ter hand / daar ik in beschrijven vinden,Boec vander wraken,Sidrac,None,None,0.508481
3690,In sinen boeken ystoriale / Van enen ridder van over dmere,Van Troyen ende van Fierenbrase / Ende menich boec datmen mint,in zijn boek NOU-P / van een ridder van over dat meer,van NOU-P en van NOU-P / en menig boek dat men minnen,Boec vander wraken,Sidrac,None,None,0.509809
2361,So sal dander vallen met / Dat sal wesen twaren,Dat in de werelt soude gevallen / Ende hoe sy inden soude met allen,zo zullen de ander vallen met / dat zullen wezen dat waar,dat in de wereld zullen vallen / en hoe zij innen zullen met al,Boec vander wraken,Sidrac,None,None,0.511483
1979,Van Romen ende van Grieken met / Hij sal groet ende scone sijn,Van Pertelpeuse van Amedase / Van Troyen ende van Fierenbrase,van NOU-P en van griek met / hij zullen groot en schoon zijn,van partelpeuze van NOU-P / van NOU-P en van NOU-P,Boec vander wraken,Sidrac,None,None,0.513152
3659,Dese keyser hadde te sinen rade / Heyden ende Kersten vroech ende spade,Ende troest van allen goeden rade / An leren mach vroech ende spade,deze keizer hebben te zijn raad / heide en kerst vroeg en spade,en troosten van al goed raad / aan leren mogen vroeg en spade,Boec vander wraken,Sidrac,None,None,0.513682
2900,Ende stichten stede ende borghe / Ende deen dander minnen so zere,Dan vechten ende vrouwen te minnen / Ende lant ende stede ende borge te winnen,en stichten stede en borg / en de een de ander minnen zo zeer,dan vechten en vrouw te minnen / en land en stede en borg te winnen,Boec vander wraken,Sidrac,None,None,0.514305
4602,Ende van allen fortsen ende quaede / Datmen hem doet vroech ende spade,Ende troest van allen goeden rade / An leren mach vroech ende spade,en van al fors en kwaad / dat men hij doen vroeg en spade,en troosten van al goed raad / aan leren mogen vroeg en spade,Boec vander wraken,Sidrac,None,None,0.514914
1298,Arestotiles die wise clerc / Maecte een boec een scone werc,Dant die edele wise clerc / Selve dichte in sijn werc,NOU-P die wijs klerk / maken een boek een schoon werk,dan het die edel wijs klerk / zelf dichten in zijn werk,Boec vander wraken,Sidrac,None,None,0.519630
4404,Waert dat alsoe ghesciede / Dat die onghelovighe liede,Die Sydrac leerde die vroede / Eenen onghelovighen coninc,zijn het dat alzo geschieden / dat die ongelovig lieden,die sidrac leren die vroed / een ongelovig koning,Boec vander wraken,Sidrac,None,None,0.521330

In [14]:
df[
    df['lemmas'].str.contains("hand") &
    df['lemmas'].str.contains("vinden") &
    df['lemmas'].str.contains("boek")
]#['title'].unique()

,title,tokens,lemmas,intertext,rhyme
47878,Boec vander wraken,MI quam een out boec in de hant / Daer ic in ghescreven vant,ik komen een oud boek in de hand / daar ik in schrijven vinden,None,hand vinden
50432,Boec vander wraken,EEn boecsken quam mi ter hant / Daer ic in ghescreven vant,een boekje komen ik ter hand / daar ik in schrijven vinden,None,hand vinden
64110,Brabantsche yeesten (B1-3),Den boec hilt hi als ict vant / Aldaer metter rechter hant,de boek houden hij als ik het vinden / aldaar met de recht hand,None,vinden hand
117151,Commentaar op het Hooglied,In den eersten boec te hant / Hier ghelijc als ic dair vant,in de eerst boek te hand / hier gelijk als ik daar vinden,None,hand vinden
318367,Historie van Troyen,In Ysis boec die waerheit vant / Hierteghen seg ic u tehant,in NOU-P boek die waarheid vinden / hiertegen zeggen ik u tehand,None,vinden tehand
339295,Korte kroniek van Brabant (lange versie),Den boeck hilt hi als ict vant / Aldaer metter rechter hant,de boek houden hij als ik het vinden / aldaar met de recht hand,None,vinden hand
606624,Sidrac,Soe quam my een boec ter hant / Daer ic in bescreven vant,zo komen ik een boek ter hand / daar ik in beschrijven vinden,None,hand vinden
661210,Spiegel historiael (P1-P4),In Eusebius bouc ic vant / Dat hi hem dode metter hant,in NOU-P boek ik vinden / dat hij hij doden met de hand,None,vinden hand
709619,Spiegel historiael (P1-P4),Den bouc hilt hi alsict vant / Aldaer metter rechtre hant,de boek houden hij als zij vinden / aldaar met de rechter hand,None,vinden hand

In [15]:
df[
    df['lemmas'].str.contains("goud") &
    df['lemmas'].str.contains("menigvout") &
    df['lemmas'].str.contains("gesteente")
]

,title,tokens,lemmas,intertext,rhyme
51443,Boec vander wraken,Ghesteinte silver ende gout / Ende diere juwele menichfout,gesteente zilver en goud / en die juweel menigvout,None,goud menigvout
75071,Brabantsche yeesten (B6),Perlen ghesteinte ende gout / Ende chierheit menichfout,parel gesteente en goud / en sierheid menigvout,None,goud menigvout
410918,Melibeus,Dat wijf es beter menechfout / Dan ghesteynte silver of gout,dat wijf zijn goed menigvout / dan gesteente zilver of goud,None,menigvout goud
606684,Sidrac,Die beter es menichfout / Danne ghesteente zelver of gout,die goed zijn menigvout / dan gesteente zelf of goud,None,menigvout goud

In [16]:
df[
    df['lemmas'].str.contains("goud") &
    df['lemmas'].str.contains("menigvout")
]

,title,tokens,lemmas,intertext,rhyme
614,Alexanders geesten,Sijn sin es beter dan gout / Hier om es beter menechfout,zijn zin zijn goed dan goud / hier om zijn goed menigvout,None,goud menigvout
1567,Alexanders geesten,Den boden gaf hi selver ende gout / Ende dede hem ere menichfout,de bode geven hij zilver en goud / en doen hij een menigvout,None,goud menigvout
4263,Alexanders geesten,Diere stene ende daertoe gout / Ende ander chierheit menichfout,die steen en daartoe goud / en ander sierheid menigvout,None,goud menigvout
6574,Alexanders geesten,Hi gaf mildelike tgout / Ende ander rijcheit menichfout,hij geven mildelijk het goud / en ander rijkheid menigvout,None,goud menigvout
10075,Alexanders geesten,Bede selver ende gout / Ende rijcheit menechfout,bede zilver en goud / en rijkheid menigvout,None,goud menigvout
51443,Boec vander wraken,Ghesteinte silver ende gout / Ende diere juwele menichfout,gesteente zilver en goud / en die juweel menigvout,None,goud menigvout
75071,Brabantsche yeesten (B6),Perlen ghesteinte ende gout / Ende chierheit menichfout,parel gesteente en goud / en sierheid menigvout,None,goud menigvout
136339,Der leken spieghel,Maer des rijcs sorghe es menechfout / Om sijn seluer ende om sijn gout,maar de rijk zorg zijn menigvout / om zijn zelf en om zijn goud,None,menigvout goud
142980,Der minnen loep,Duerbair cleynoot sulver goudt / Ghesteynten paerlen menichfout,doorbaar kleinood zelf goud / gesteent parel menigvout,None,goud menigvout
189829,Devoot ende profitelyck boecxken,V sorghe was menichfout / Cleyn was v siluer v gout,uw zorg zijn menigvout / klein zijn uw zilver uw goud,None,menigvout goud
191542,Devoot ende profitelyck boecxken,Drie coninghen menichfout / Myrre wieroock ende gout,drie koning menigvout / mirre wierook en goud,None,menigvout goud
197680,Dietsche doctrinale,Hebt lieuer seiti menechfout / Mine leringhe dan mijn gout,hebben liever zeggen gij menigvout / mijn lering dan mijn goud,None,menigvout goud
199523,Dietsche doctrinale,Vriends troest es beter menichfout / Dan ghesteinte siluer oft gout,vriend troost zijn goed menigvout / dan gesteind zilver of goud,None,menigvout goud
200501,Dietsche doctrinale,Die dicke es menichfout / Beter dan siluer oft gout,die dik zijn menigvout / goed dan zilver of goud,None,menigvout goud
200683,Dietsche doctrinale,Wet dat vriende menechfout / Beter sijn dan siluer oft gout,wetten dat vriend menigvout / goed zijn dan zilver of goud,None,menigvout goud
203525,Dietsche doctrinale,Goet name es beter menechfout / Dan siluer stene oft gout,goed naam zijn goed menigvout / dan zilveren steen of goud,None,menigvout goud
207521,Eerste Martijn,Wes nerachtich minne niet dat gout / Wes erachtich menichfout,wat neerachtig minne niet dat goud / wat eerachtig menigvout,None,goud menigvout
209454,Enaamse Codex,Daertoe seluer ende ghout / Ende cierheit menechfout,daartoe zelf en goud / en sierheid menigvout,None,goud menigvout
223785,Florimont,Daer loet men in selver ende gout / Ende chierheit menechfout,daar laden men in zilver en goud / en sierheid menigvout,None,goud menigvout
244202,Gedichten (Willem van Hildegaersberch),Mit sijnre ghenaden menichfout / Coren gras sulver gout,met zijn genade menigvout / keur gras zelf goud,None,menigvout goud
275694,Gruuthuse-liederen,Salic u gheven zelver ende gout / So gaf mi orlof menichfout,zullen ik u geven zilver en goud / zo geven ik oorlof menigvout,None,goud menigvout
295668,Historie van Troyen,Hier is silver ende gout / Ende duere cleder menichfout,hier zijn zilver en goud / en duur kleed menigvout,None,goud menigvout
335687,Jonathas ende Rosafiere,Hij gaf haer selver ende gout / Ende cleederen menichfout,hij geven zij zelf en goud / en kleed menigvout,None,goud menigvout
336647,Karel ende Elegast,Beyde siluer ende gout / Sinen list is menichfout,beide zilver en goud / zijn list zijn menigvout,None,goud menigvout
385675,Limborch,Die u offerande brachten menichfout / Myrre wieroec ende gout,die u offerande brengen menigvout / mirre wierook en goud,None,menigvout goud
387964,Limborch,Ende wiisdem zilver ende gout / Ende ander sierheit menichfout,en wonen hij zilver en goud / en ander sierheid menigvout,None,goud menigvout
410918,Melibeus,Dat wijf es beter menechfout / Dan ghesteynte silver of gout,dat wijf zijn goed menigvout / dan gesteente zilver of goud,None,menigvout goud
413725,Melibeus,Gratie es beter menechfout / Dan zilver es ofte gout,gratie zijn goed menigvout / dan zilver zijn ofte goud,None,menigvout goud
423911,Merlijn,Ende die minden gaf hi gout / Ende clenoden menechfout,en die minde geven hij goud / en kleinood menigvout,None,goud menigvout
470927,Parthonopeus van Bloys,So honech ende gout / Dat staet daer harde menechfout,zo honing en goud / dat staan daar hard menigvout,None,goud menigvout
503171,Riddere metter mouwen,Daer was bliscap menichfout / Si gaven selver ende gout,daar zijn blijdschap menigvout / zij geven zilver en goud,None,menigvout goud
588489,Rose,Mar dragen cireit menichfout / Bont graeu selver ende gout,maar dragen cireet menigvout / bont grauw zilver en goud,None,menigvout goud
606684,Sidrac,Die beter es menichfout / Danne ghesteente zelver of gout,die goed zijn menigvout / dan gesteente zelf of goud,None,menigvout goud
647842,Spiegel historiael (P1-P4),Tien tiden so was menechfout / Geprijst eere vore gout,tien tijd zo zijn menigvout / prijzen eer voor goud,None,menigvout goud
722273,Spiegel historiael (P1-P4),Voer Antyochen selver ende gout / Alle den prencen menechfout,voor NOU-P zilver en goud / al de prins menigvout,None,goud menigvout
830078,Vanden levene ons heren,Mirre wieroec ende gout / Si aenbedden tkint menichfout,mirre wierook en goud / zij aanbedden dat kind menigvout,None,goud menigvout
832927,Vanden levene ons heren,Ende daden offerande menichfout / Mirre wieroec ende gout,en doen offerande menigvout / mirre wierook en goud,None,menigvout goud
845111,Walewein (Penninc),In die riviere alst ware gout / Walewein die menichfout,in die rivier als het zijn goud / NOU-P die menigvout,None,goud menigvout

In [17]:
nearest_df = nearest_verses('Der leken spieghel', 'Jans teesteye',
                            base_df=df, vectorizer=vec, prop_filt=2)
nearest_df = nearest_df.sort_values(by='distance')
nearest_df.to_excel('../figures/parallel_verses/lekenspiegel-teesteye.xlsx')
nearest_df.head(50)

,tokens1,tokens2,lemmas1,lemmas2,title1,title2,intertext1,intertext2,distance
4699,Elc mensche die sal / Gode minnen bouen al,Elc mensche die sal / Gode minnen boven al,elk mens die zullen / NOU-P minnen boven al,elk mens die zullen / NOU-P minnen boven al,Der leken spieghel,Jans teesteye,None,None,0.000000e+00
4709,Nieman doeden noch verslaen / Gheen valsch orconde doen verstaen,Nieman doden noch verslaen / Gheen valsche orconde doen verstaen,niemand doden noch verslaan / geen vals oorkonde doen verstaan,niemand doden noch verslaan / geen vals oorkonde doen verstaan,Der leken spieghel,Jans teesteye,None,None,0.000000e+00
3501,Sal men gaen daer toe / Wijslijc ende met maten,Salmen gaen daer toe / Wijsselijc ende met maten,zullen men gaan daar toe / wijselijk en met maat,zullen men gaan daar toe / wijselijk en met maat,Der leken spieghel,Jans teesteye,None,None,2.220446e-16
4708,Ende oec niet stelen wats ghesciet / Nieman doeden noch verslaen,Ende oec niet stelen wats ghesciet / Nieman doden noch verslaen,en ook niet stelen wat geschieden / niemand doden noch verslaan,en ook niet stelen wat geschieden / niemand doden noch verslaan,Der leken spieghel,Jans teesteye,None,None,2.220446e-16
2732,Want soe die nideghe langher leeft / Soe hi meer onwils heeft,Want so die nideghe langher leeft / So hi meer sijns onwillen heeft,want zo die nijdige lang leven / zo hij meer onwil hebben,want zo die nijdige lang leven / zo hij meer zijn onwil hebben,Der leken spieghel,Jans teesteye,None,None,4.709279e-03
11201,Daer hi elken loen sal gheuen / Van dat hi hier heeft bedreuen,Hi elken loen sal gheven / Van dat hi hier heeft bedreven,daar hij elk loen zullen geven / van dat hij hier hebben bedrijven,hij elk loen zullen geven / van dat hij hier hebben bedrijven,Der leken spieghel,Jans teesteye,None,None,1.319916e-02
14677,Ende elken loen zal gheuen / Van dat hi hier heeft bedreuen,Hi elken loen sal gheven / Van dat hi hier heeft bedreven,en elk loen zullen geven / van dat hij hier hebben bedrijven,hij elk loen zullen geven / van dat hij hier hebben bedrijven,Der leken spieghel,Jans teesteye,None,None,1.391463e-02
4707,Anders mans wijf onderwinden niet / Ende oec niet stelen wats ghesciet,Anderre wive onderwenden niet / Ende oec niet stelen wats ghesciet,ander man wijf onderwinden niet / en ook niet stelen wat geschieden,ander wijf onderwinden niet / en ook niet stelen wat geschieden,Der leken spieghel,Jans teesteye,None,None,2.554649e-02
9378,Maer anebeedden een calf / Datsi van ere ghieten daeden,Maer si aenbeedden een calf / Dat si goten van ere,maar aanbeden een kalf / dat zij van een gieten doen,maar zij aanbeden een kalf / dat zij gieten van een,Der leken spieghel,Jans teesteye,None,None,3.207500e-02
5333,Ende elken loen gheuen / Van dat hi hier heeft bedreuen,Hi elken loen sal gheven / Van dat hi hier heeft bedreven,en elk loen geven / van dat hij hier hebben bedrijven,hij elk loen zullen geven / van dat hij hier hebben bedrijven,Der leken spieghel,Jans teesteye,None,None,3.230851e-02
4704,Te vergheefs nemen inden mont / Vieren wel die daghe ons heren,Te vergheefs nemen inden mont / Vieren die heylighe daghe Ons Heren,te vergeefs nemen in de mond / vieren wel die dag ons heer,te vergeefs nemen in de mond / vieren die heilig dag ons heer,Der leken spieghel,Jans teesteye,None,None,5.761684e-02
4710,Gheen valsch orconde doen verstaen / Ander mans wijf begheren twint,Gheen valsche orconde doen verstaen / Anders mans wijf begheren twint,geen vals oorkonde doen verstaan / ander man wijf begeren twint,geen vals oorkonde doen verstaan / anders man wijf begeren twint,Der leken spieghel,Jans teesteye,None,None,7.418365e-02
21802,Wi moeten alle openbaer / Vore sijn anschijn comen daer,Wi moeten allen openbaer / Voer sijn aenschijn staen daer,wij moeten al openbaar / voor zijn aanschijn komen daar,wij moeten al openbaar / voor zijn aanschijn staan daar,Der leken spieghel,Jans teesteye,None,None,7.512487e-02
4402,Het soudu te lanc recken / Soudic v al vertrecken,Die ic u wel soude vertrecken / Maer het soude te langhe recken,het zullen du te lang rekken / zullen ik u al vertrekken,die ik u wel zullen vertrekken / maar het zullen te lang rekken,Der leken spieghel,Jans teesteye,None,None,8.790180e-02
2731,Dan dat si langhe moeten leuen / Want soe die nideghe langher leeft,Dan datmen hem bidt om lanc leven / Want so die nideghe langher leeft,dan dat zij lang moeten leven / want zo die nijdige lang leven,dan dat men hij bidden om lang leven / want zo die nijdige lang leven,Der leken spieghel,Jans teesteye,None,None,9.676742e-02
16701,Die ziele inder hellen / Daer si euwelijc sal quellen,Van daer selen inder hellen / Daer si ewelijc selen quellen,die ziel in de hel / daar zij eeuwelijk zullen kwellen,van daar zullen in de hel / daar zij eeuwelijk zullen kwellen,Der leken spieghel,Jans teesteye,None,None,1.057301e-01
17471,Het was hebbic zegghen horen / Een yeraut hier te voren,WOuter ic hebbe segghen horen / Dat een coninc hier te voren,het zijn hebben ik zeggen horen / een jeroud hier te voren,NOU-P ik hebben zeggen horen / dat een koning hier te voren,Der leken spieghel,Jans teesteye,None,None,1.145767e-01
4700,Gode minnen bouen al / Ende sinen euenkersten des sijt vroet,Gode minnen boven al / Ende sinen evenkersten dies benic vroet,NOU-P minnen boven al / en zijn evenkersten des zijn vroed,NOU-P minnen boven al / en zijn evenkersten dies zijn ik vroed,Der leken spieghel,Jans teesteye,None,None,1.152142e-01
4701,Ende sinen euenkersten des sijt vroet / Ghelijc hi hem zeluen doet,Ende sinen evenkersten dies benic vroet / Ghelijc dat hi hem selven doet,en zijn evenkersten des zijn vroed / gelijk hij hij zelf doen,en zijn evenkersten dies zijn ik vroed / gelijk dat hij hij zelf doen,Der leken spieghel,Jans teesteye,None,None,1.194506e-01
2848,Daer hi sijn lijf omme besuerde / Ende sine ziele omme auontuerde,Siele ende lijf om avontuert / Ende dat sijn leven dicke besuert,daar hij zijn lijf om bezuren / en zijn ziel om avonturen,ziel en lijf om avonturen / en dat zijn leven dik bezuren,Der leken spieghel,Jans teesteye,None,None,1.324372e-01
4723,M iaer te voren / Eer cnristus wart gheboren,Meer dan M iaer te voren / Dat Cristus soude werden gheboren,m jaar te voren / eer NOU-P worden geboren,meer dan m jaar te voren / dat NOU-P zullen worden geboren,Der leken spieghel,Jans teesteye,None,None,1.396339e-01
2102,Hi soude gode sijn ghelijc / Ende oec wesen onsterflijc,Si souden sijn onsterfelijc / Ende haren God sijn ghelijc,hij zullen NOU-P zijn gelijk / en ook wezen onsterfelijk,zij zullen zijn onsterfelijk / en haar NOU-P zijn gelijk,Der leken spieghel,Jans teesteye,None,None,1.396760e-01
18703,Den andren tsine soude gheuen / Dus was landshere ierst verheuen,Die elken tsine dede gheven / Dus wert de lantshere yrst verheven,de ander dat zijn zullen geven / dus zijn landheer eerst verheffen,die elk dat zijn doen geven / dus worden de landheer eerst verheffen,Der leken spieghel,Jans teesteye,None,None,1.444489e-01
9377,Ende en kindens groet noch half / Maer anebeedden een calf,Ende en bekendens al noch half / Maer si aenbeedden een calf,en een kennen zij groot nog half / maar aanbeden een kalf,en ne bekennen dat al nog half / maar zij aanbeden een kalf,Der leken spieghel,Jans teesteye,None,None,1.474424e-01
2740,Dat enen anderen goet gheschiet / Dat hem en costet niet,Dat enen andren goet ghesciet / Dat hem en cost no en scaedt niet,dat een ander goed geschieden / dat hij ne kosten niet,dat een ander goed geschieden / dat hij ne kosten noch ne schaden niet,Der leken spieghel,Jans teesteye,None,None,1.477261e-01
4749,Die alle scriuen ende leren / Die heileghe comst ons heren,Die alle scriven ende leren / Die heylighe toecomst Ons Heren,die al schrijven en leren / die heilig komst ons heer,die al schrijven en leren / die heilig toekomst ons heer,Der leken spieghel,Jans teesteye,None,None,1.485224e-01
2614,In ertrike nes groet no smal / Die miltheit gods en gheuet al,Int ertrike en es groet no smal / Hi en hevet ghegheven al,in aardrijk ne zijn groot noch smal / die mildheid NOU-P ne geven al,in het aardrijk ne zijn groot noch smal / hij ne hebben geven al,Der leken spieghel,Jans teesteye,None,None,1.608793e-01
17319,Het was een ridder hier te voren / In zassen hebbic zegghen horen,WOuter ic hebbe segghen horen / Dat een coninc hier te voren,het zijn een ridder hier te voren / in NOU-P hebben ik zeggen horen,NOU-P ik hebben zeggen horen / dat een koning hier te voren,Der leken spieghel,Jans teesteye,None,None,1.653878e-01
15754,Soe dat hen god es hout / Om datsi quiten hore scout,Ende quiten willen hare scout / So sal hen God wesen hout,zo dat zij NOU-P zijn houden / om hij dat zij kwijten haar scout,en kwijten willen haar scout / zo zullen zij NOU-P wezen houden,Der leken spieghel,Jans teesteye,None,None,1.699176e-01
454,Maer die godheit in dien / Blijft daer al onghesien,Maer die vorme sire gotheyt in dien / Bleef nochtan al onghesien,maar die godheid in dat / blijven daar al ongezien,maar die vormen zijn godheid in dat / blijven nochtan al ongezien,Der leken spieghel,Jans teesteye,None,None,1.720904e-01
18875,HEren selen thoren rade / Goede liede ende ghestade,Heren sellen hebben te haren rade / Wise liede ende ghestade,heer zullen hethaar raad / goed lieden en gestade,heer zullen hebben te haar raad / wijs lieden en gestade,Der leken spieghel,Jans teesteye,None,None,1.723248e-01
7771,Die hemel ende erde maecte al / Ende alse hi wilt ontmaken sal,Ende diet ghemaect heeft al / Ende alse hi wille ontmaken sal,die hemel en aarde maken al / en als hij willen ontmaken zullen,en die het maken hebben al / en als hij willen ontmaken zullen,Der leken spieghel,Jans teesteye,None,None,1.791264e-01
4711,Ander mans wijf begheren twint / Noch anders goed waerment vint,Anders mans wijf begheren twint / Noch anders goet Also men vint,ander man wijf begeren twint / noch anders goed waar men vinden,anders man wijf begeren twint / nog anders goed alzo men vinden,Der leken spieghel,Jans teesteye,None,None,1.853876e-01
18885,Ende den here volghen al sire daet / Weder si goet si ofte quaet,So prijst hi al sijns heren daet / Weder dat goet si ofte quaet,en de heer volgen al zijn daad / weder zij goed zijn ofte kwaad,zo prijzen hij al zijn heer daad / weder dat goed zij ofte kwaad,Der leken spieghel,Jans teesteye,None,None,1.866129e-01
3502,Wijslijc ende met maten / Ende enen d niet quisten laten,Wijsselijc ende met maten / Ende enen penninc niet quisten laten,wijselijk en met maat / en een d niet kwisten laten,wijselijk en met maat / en een penning niet kwisten laten,Der leken spieghel,Jans teesteye,None,None,1.872625e-01
21918,Ende iaghent al ter hellen / Daer si ewelec selen quellen,Van daer selen inder hellen / Daer si ewelijc selen quellen,en jagen het al ter hel / daar zij eeuwelijk zullen kwellen,van daar zullen in de hel / daar zij eeuwelijk zullen kwellen,Der leken spieghel,Jans teesteye,None,None,1.912716e-01
3500,Tien ghemeinen orbore soe / Sal men gaen daer toe,Teenen ghemeynen orboer so / Salmen gaen daer toe,tien gemeen oorbaar zo / zullen men gaan daar toe,teen gemeen oorbaar zo / zullen men gaan daar toe,Der leken spieghel,Jans teesteye,None,None,1.948143e-01
394,Hem en es verboerghen twint / Die alle herten binnen kint,Ende die alle herten binnen kint / Ende dien verborghen en es twint,hij ne zijn verborgen twint / die al hert binnen kind,en die al hert binnen kennen / en dat verborgen ne zijn twint,Der leken spieghel,Jans teesteye,None,None,1.966267e-01
4703,Godes name te gheere stont / Te vergheefs nemen inden mont,Ende God name in gheenre stont / Te vergheefs nemen inden mont,NOU-P naam te gaarne stonde / te vergeefs nemen in de mond,en NOU-P nemen innen gene stonde / te vergeefs nemen in de mond,Der leken spieghel,Jans teesteye,None,None,2.002425e-01
14184,Ende wi sijn alle sine kinder / Die goet sijn meerre ende minder,Want hijs onse Vader wi sijn sine kindre / Hi ghevet al meerder ende minder,en wij zijn al zijn kind / die goed zijn meerder en minder,want hij dat ons vader wij zijn zijn kind / hij geven al meerder en minder,Der leken spieghel,Jans teesteye,None,None,2.036448e-01
2741,Dat hem en costet niet / Ende die hem noyt arch en dede,Dat hem en cost no en scaedt niet / Noch noyt hem gheen arch en dede,dat hij ne kosten niet / en die hij nooit erg ne doen,dat hij ne kosten noch ne schaden niet / noch nooit hij geen erg ne doen,Der leken spieghel,Jans teesteye,None,None,2.110203e-01
2730,Niet meere vloec machmen hem gheuen / Dan dat si langhe moeten leuen,Men derf hem niet meer vloeke gheven / Dan datmen hem bidt om lanc leven,niet meer vloek mogen men hij geven / dan dat zij lang moeten leven,men derven hij niet meer vloek geven / dan dat men hij bidden om lang leven,Der leken spieghel,Jans teesteye,None,None,2.143932e-01
16221,Ens coninc bisscop no pape / Ridder vrouwe no cnape,En es paeus bisscop no pape / Lantshere riddere no knape,het ne zijn koning bisschop noch paap / ridder vrouwe noch knaap,ne zijn paus bisschop noch paap / landheer ridder noch knaap,Der leken spieghel,Jans teesteye,None,None,2.190056e-01
1928,Dus draghen sise inder helle / Daer si ewelike moet quellen,Van daer selen inder hellen / Daer si ewelijc selen quellen,dus dragen zij zij in de hel / daar zij eeuwelijk moeten kwellen,van daar zullen in de hel / daar zij eeuwelijk zullen kwellen,Der leken spieghel,Jans teesteye,None,None,2.195370e-01
8,Ligghe sijn ere ende sijn lof / Ende dat si alle daer of,Datter in ligghe sijn ere ende sijn lof / Ende tfolc werde verblijdt daer of,liggen zijn eer en zijn lof / en dat zij al daar af,dat er en liggen zijn eer en zijn lof / en dat volk worden verblijden daar af,Der leken spieghel,Jans teesteye,None,None,2.228556e-01
17986,Ende en mach drinken noch eten / Nochtan en can hi gheweten,Dat si niet en connen gheweten / Wat si drincken moghen of eten,en ne mogen drinken noch eten / nochtan ne kunnen hij geweten,dat zij niet ne kunnen geweten / wat zij drinken mogen of eten,Der leken spieghel,Jans teesteye,None,None,2.234556e-01
20496,Ledecheit tallen stonden / Es voederse van vele sonden,Dat ledecheyt tallen stonden / Voeden can die sonden,ledigheid te al stond / zijn voederse van veel zonde,dat ledigheid te al stond / voeden kunnen die zonde,Der leken spieghel,Jans teesteye,None,None,2.250002e-01
2376,Ende met zire doeght des verdient / Dat god onse here es sijn vrient,Ende die des oec heeft verdient / Dat God es worden onse vrient,en met zijn deugd des verdienen / dat NOU-P ons heer zijn zijn vriend,en die des ook hebben verdienen / dat NOU-P zijn worden ons vriend,Der leken spieghel,Jans teesteye,None,None,2.279370e-01
20386,Wet ghine hebt groet no smal / Hine heuet ghegheuen al,Int ertrike en es groet no smal / Hi en hevet ghegheven al,wetten gij ne hebben groot noch smal / hij ne hebben geven al,in het aardrijk ne zijn groot noch smal / hij ne hebben geven al,Der leken spieghel,Jans teesteye,None,None,2.302364e-01
17263,Dat ghi enen andren vroech ende spade / Doet als ghi woudt datmen v dade,Ende elc anderen sal doen vroech ende spade / Also hi woude datmen hem dade,dat gij een ander vroeg en spade / doen als gij willen dat men u doen,en elk ander zullen doen vroeg en spade / alzo hij willen dat men hij doen,Der leken spieghel,Jans teesteye,None,None,2.317338e-01

In [18]:
nearest_df = nearest_verses('Sidrac', 'Jans teesteye',
                            base_df=df, vectorizer=vec, prop_filt=2)
nearest_df = nearest_df.sort_values(by='distance')
nearest_df.to_excel('../figures/parallel_verses/sidrac-teesteye.xlsx')
nearest_df.head(50)

,tokens1,tokens2,lemmas1,lemmas2,title1,title2,intertext1,intertext2,distance
27,Aldus eest ende anders niet / Die de dinc te rechte besiet,Want die de dinc te rechte besiet / So en was Cristus leven anders niet,aldus zijn het en anders niet / die de ding te rechte bezien,want die de ding te rechte bezien / zo ne zijn NOU-P leven anders niet,Sidrac,Jans teesteye,None,None,0.190362
129,Doe hine metter gracie van Gode / Hadde bekeert te sinen ghebode,Die de gratie heeft te Gode / Men houde de X ghebode,toen hij hij met de gratie van NOU-P / hebben bekeren te zijn gebod,die de gratie hebben te NOU-P / men houden de tien gebod,Sidrac,Jans teesteye,None,None,0.365651
209,Al in die stat tAntwerpen / Wast dat ic dit translateerde,AL tote Andwerpen in die stat / Luste tween ghesellen dat,al in die stad te antwerpen / wassen dat ik dit translateren,al tot antwerpen in die stad / lust twee gezel dat,Sidrac,Jans teesteye,None,None,0.372522
167,Dat God ende ghi allene / Enen sone hebt gemene,Ende wanen dat ic allene / Die goede metten quaden mene,dat NOU-P en gij alleen / een zoon hebben menen,en wanen dat ik alleen / die goed met de kwaad menen,Sidrac,Jans teesteye,None,None,0.398777
221,Amen segt gemeenlike / Amen,Ewelijc in alder tijt Amen / DAvonture Ian wats dat,amen zeggen gemeenlijk / amen,eeuwelijk in al tijd amen / de avontuur NOU-P NOU-P dat,Sidrac,Jans teesteye,None,None,0.422559
17,Ende troest van allen goeden rade / An leren mach vroech ende spade,Ende pijnt daer om vroech ende spade / Ende alse hi dan te goede es comen,en troosten van al goed raad / aan leren mogen vroeg en spade,en pijnen daar om vroeg en spade / en als hij dan te goed zijn komen,Sidrac,Jans teesteye,None,None,0.448263
208,Verre van mi wille werpen / Al in die stat tAntwerpen,AL tote Andwerpen in die stat / Luste tween ghesellen dat,ver van ik willen werpen / al in die stad te antwerpen,al tot antwerpen in die stad / lust twee gezel dat,Sidrac,Jans teesteye,None,None,0.452782
188,Daer boven inden oversten trone / Daer die ingelen singen hoge,Alle die hemele ende die eerde / Ende daer boven die hoghe trone,daar boven in de overst troon / daar die engel zingen hoog,al die hemel en die aarde / en daar boven die hoog troon,Sidrac,Jans teesteye,None,None,0.455318
28,Die de dinc te rechte besiet / Die den tijt onledich maken,Want die de dinc te rechte besiet / So en was Cristus leven anders niet,die de ding te rechte bezien / die de tijd onledig maken,want die de ding te rechte bezien / zo ne zijn NOU-P leven anders niet,Sidrac,Jans teesteye,None,None,0.456364
145,Doen ic dit werc ierst began / Ende hebbe versleten nochtan,Doen kerstenheyt yrst began / Die keyser ende de heren nochtan,toen ik dit werk eerst beginnen / en hebben verslijten nochtan,toen kerstenheid eerst beginnen / die keizer en de heer nochtan,Sidrac,Jans teesteye,None,None,0.458654
180,Beide die heilege Geest ende die Sone / Die een God sijn metten Vader,Des onne ons ende gheve sijn volleest / Die Vader die Sone die Heilighe Gheest,beide die heilig geest en die zoon / die een god zijn met de vader,de on ons en geven zijn volleest / die vader die zoon die heilig geest,Sidrac,Jans teesteye,None,None,0.461751
187,Daer by sy es ghevoeget scone / Daer boven inden oversten trone,Ende daer boven die hoghe trone / Die hi al vulde scone,daar bij zij zijn voegen schoon / daar boven in de overst troon,en daar boven die hoog troon / die hij al vullen schoon,Sidrac,Jans teesteye,None,None,0.463547
174,Die dese vrouwe niet en mint / Die de Vader alsoe minde,Om dat die vader deen kint / Meer dan hen hadde ghemint,die deze vrouwe niet ne minnen / die de vader alzo minnen,om dat die vader de een kind / meer dan zij hebben minnen,Sidrac,Jans teesteye,None,None,0.465025
37,Dat overlijt soe cortelike / Verdienen souden hemelrike,Mach die mensche verdienen des / Dat hemelrike sijn es,dat overlijd zo kortelijk / verdienen zullen hemelrijk,mogen die mens verdienen de / dat hemelrijk zijn zijn,Sidrac,Jans teesteye,None,None,0.467254
45,Hondertfout van lone / Te Antwerpen daer ic wone,Boendale heetmen mi daer / Ende wone te Andwerpen nu,honderdfout van loon / te NOU-P daar ik wonen,NOU-P heten men ik daar / en wonen te NOU-P nu,Sidrac,Jans teesteye,None,None,0.468246
117,Als God de warelt zal domen / Ende hoe si ter bliscap sullen comen,Ende sal ten ionxten daghe comen / Alle mensche doemen,als NOU-P de wereld zullen doemen / en hoe zij ter blijdschap zullen komen,en zullen ten jong dag komen / al mens doemen,Sidrac,Jans teesteye,None,None,0.471013
83,Anders dan dat ic niet en woude / Dat dese edele leringe soude,So en was Cristus leven anders niet / Dan exemple ende leringhe mede,anders dan dat ik niet ne willen / dat deze edel lering zullen,zo ne zijn NOU-P leven anders niet / dan exempel en lering mede,Sidrac,Jans teesteye,None,None,0.471013
155,Niet toe gebringen en can / Het es te swaer elcken man,Ende dat es swaer elken man / Dat nieman gheweten en can,niet toegespreken gebrengen ne kunnen / het zijn te zwaar elk man,en dat zijn zwaar elk man / dat niemand geweten ne kunnen,Sidrac,Jans teesteye,None,None,0.473429
4,Alsoe sijn geesten vanden heren / Van Pertelpeuse van Amedase,Die van Grieken ende van Cartago / Ende van anderen landen also,alzo zijn geest van de heer / van partelpeuze van NOU-P,die van griek en van NOU-P / en van ander land alzo,Sidrac,Jans teesteye,None,None,0.477393
78,Anders dant dauctor ute gaf / Die anders doen sy doen quaet,Ende die anders segghen daer af / Si doen quaet sijts gewes,anders dan het de autor uiten geven / die anders doen zij doen kwaad,en die anders zeggen daar af / zij doen kwaad zijn het gewis,Sidrac,Jans teesteye,None,None,0.482695
206,Alst comt te minen laetsten stonden / Dat hi mi dan al mine zonden,Dat hi hem huede van sonden / Ende dat hi peynse tallen stonden,als het komen te mijn laat stond / dat hij ik dan al mijn zonde,dat hij hij houden van zonde / en dat hij peinzen te al stond,Sidrac,Jans teesteye,None,None,0.483296
202,Ende ic bidde hem allen met trauwen / Die desen bouc selen scauwen,Ende oec machmen in u scouwen / Meer dogheden ende trouwen,en ik bidden hij al met trouw / die deze boek zullen schouwen,en ook mogen men in u schouwen / meer deugd en trouw,Sidrac,Jans teesteye,None,None,0.488312
151,Vanden cruden latic uut / Ende vanden stenen die virtuit,In haer macht ende in haer virtuut / Maer de twee sijn nu wt,van de kruid laten ik uit / en van de steen die virtuut,in haar macht en in haar virtuut / maar de twee zijn nu uit,Sidrac,Jans teesteye,None,None,0.488899
111,Want dese bouc hevet in / Der warelt fundament ende beghin,Soudic u des maken in inne / Vander werelt beghinne,want deze boek hebben in / de wereld fundament en begin,zullen ik u des maken in in / van de wereld begin,Sidrac,Jans teesteye,None,None,0.496494
191,Epiloog / Ghelooft zi God van hemelrike,God gheve hem sijn hemelrike / Nu hebdi verstaen die nuthede,epiloog / loven zij NOU-P van hemelrijk,NOU-P geven hij zijn hemelrijk / nu hebben gij verstaan die nutheid,Sidrac,Jans teesteye,None,None,0.501175
15,Ende leggen die boeke onder voet / Daer men wijsheit doget ende goet,Ende datter in es quaet ende goet / Es al onder des mans voet,en leggen die beuk onder voet / daar men wijsheid doen en goed,en dat er en zijn kwaad en goed / zijn al onder de man voet,Sidrac,Jans teesteye,None,None,0.502283
18,An leren mach vroech ende spade / In weet wat sire inne menen,Maer het was al ghemene / Dat si hadden vroech ende spade,aan leren mogen vroeg en spade / u weten wat zijn ik ne menen,maar het zijn al gemeen / dat zij hebben vroeg en spade,Sidrac,Jans teesteye,None,None,0.502652
46,Te Antwerpen daer ic wone / Soe quam my een boec ter hant,Boendale heetmen mi daer / Ende wone te Andwerpen nu,te NOU-P daar ik wonen / zo komen ik een boek ter hand,NOU-P heten men ik daar / en wonen te NOU-P nu,Sidrac,Jans teesteye,None,None,0.505787
94,Die ic hier na bescrive / Die boec daer icse ute trac,Dat si wel te verstane gheven / In haren boeken die si hebben bescreven,die ik hier na beschrijven / die boek daar ik zij uit trekken,dat zij wel te verstaan geven / in haar boek die zij hebben beschrijven,Sidrac,Jans teesteye,None,None,0.508181
181,Die een God sijn metten Vader / Dus heeft sy algader,Si schinen dat si weten algader / Die verholenheyt des Vader,die een god zijn met de vader / dus hebben zij algader,zij schijnen dat zij weten algader / die verholenheid de vader,Sidrac,Jans teesteye,None,None,0.512089
35,Want die tijt es ons ghegeuen / Omme dat wy in dit leven,God heeft den man ghegheven / Grote gracie in dit leven,want die tijd zijn ons geven / om dat wij in dit leven,NOU-P hebben de man geven / groot gratie in dit leven,Sidrac,Jans teesteye,None,None,0.514136
29,Die den tijt onledich maken / Met onoerboerliken saken,Een sake daer hem een man / Onledech mede maken mach,die de tijd onledig maken / met onoorbaarlijk zaak,een sake daar hij een man / onledig mede maken mogen,Sidrac,Jans teesteye,None,None,0.520886
184,Daer by eest openbare / Dat haer niet en es ontseit,In dEwangelie openbare / Dat si doen des en doet niet,daar bij zijn het openbaar / dat zij niet ne zijn ontzeggen,in de ewangelie openbaar / dat zij doen de ne doen niet,Sidrac,Jans teesteye,None,None,0.520977
139,Dat ic dit werc bringhe toe / Ende mijn leven betren zoe,Ende ghebetert spade ende vroe / Ende nemt in lanc so meer toe,dat ik dit werk brengen toezenden / en mijn leven beteren zo,en beteren spa en vroe / en nemen in lang zo meer toezenden,Sidrac,Jans teesteye,None,None,0.521320
220,Ende na dit leven hemelrike / Amen segt gemeenlike,Voor Gode te draghene in hemelrike / Ende voor dingle ghemeynlike,en na dit leven hemelrijk / amen zeggen gemeenlijk,voor NOU-P te dragen in hemelrijk / en voor dengel gemeenlijk,Sidrac,Jans teesteye,None,None,0.522104
67,Die de materie sal leggen wale / Van ere tale in een ander tale,Deen es behendech ende mach wale / Gheven ende can oec wel sijn tale,die de materie zullen leggen wel / van een taal in een ander taal,de een zijn behendig en mogen wel / geven en kunnen ook wel zijn taal,Sidrac,Jans teesteye,None,None,0.523663
96,Es geheten die wise Sidrac / Na enen clerc wijs ende fijn,Es voer Gode also mare / Alse eens clercs des benic wijs,zijn heten die wijze NOU-P / na een klerk wijs en fijn,zijn voor NOU-P alzo maar / als een klerk de benig wijs,Sidrac,Jans teesteye,None,None,0.523684
101,Dat in de werelt soude gevallen / Ende hoe sy inden soude met allen,So selen si ghelijc met allen / Ane der kerstene wet vallen,dat in de wereld zullen vallen / en hoe zij innen zullen met al,zo zullen zij gelijk met al / aan de kersten wet vallen,Sidrac,Jans teesteye,None,None,0.530709
185,Dat haer niet en es ontseit / Vander edelre Godheit,Dat miere herten ghenoech dede / Vander hogher godhede,dat zij niet ne zijn ontzeggen / van de edel godheid,dat mijn hert genoeg doen / van de hoog godheid,Sidrac,Jans teesteye,None,None,0.531228
116,Ende de welke behouden zal sijn / Als God de warelt zal domen,Ende sal ten ionxten daghe comen / Alle mensche doemen,en de welk behouden zullen zijn / als NOU-P de wereld zullen doemen,en zullen ten jong dag komen / al mens doemen,Sidrac,Jans teesteye,None,None,0.531731
104,Hoe der inglen coor sijn gheheten / Dit was hem algader cont,Hem en es verborghen niet / Het es hem algader cont,hoe de engel koor zijn heten / dit zijn hij algader kond,hij ne zijn verborgen niet / het zijn hij algader kond,Sidrac,Jans teesteye,None,None,0.532529
149,In dichte niet dat weet wale / Dien boec ute altemale,I ziele es beter dat weet wale / Dan dese werelt altemale,in dicht niet dat weten wel / dat boek uit altemaal,ziel zijn goed dat weten wel / dan deze wereld altemaal,Sidrac,Jans teesteye,None,None,0.532912
177,In hore omme die dinc / Dat sire den Sone by ontfinc,Dat was Christus in waerre dinc / Die menschelike vorme ontfinc,in haar om die ding / dat zijn de zoon bij ontvangen,dat zijn NOU-P in waar ding / die menselijk vorm ontvangen,Sidrac,Jans teesteye,None,None,0.533774
194,Dat hi mi so langhe spaerde / Ende minen zin also verclaerde,Die dinc ende bat verclaren / Dan si vore verclaert waren,dat hij ik zo lang sparen / en mijn zin alzo verklaren,die ding en bet verklaren / dan zij voor verklaren zijn,Sidrac,Jans teesteye,None,None,0.539249
112,Der warelt fundament ende beghin / Ende oec zal hi doen verstaen,Soudic u des maken in inne / Vander werelt beghinne,de wereld fundament en begin / en ook zullen hij doen verstaan,zullen ik u des maken in in / van de wereld begin,Sidrac,Jans teesteye,None,None,0.540280
2,Die hem ane die boeke houden / Daer sy clene profijt inne leren,Ende Moyses boeke hilden si / Ende propheten oec daer bi,die hij aan die beuk houden / daar zij klein profijt in leren,en NOU-P beuk houden zij / en profeten ook daar bij,Sidrac,Jans teesteye,None,None,0.543569
38,Verdienen souden hemelrike / Ende die hier luttel sayen,Mach die mensche verdienen des / Dat hemelrike sijn es,verdienen zullen hemelrijk / en die hier luttel zaaien,mogen die mens verdienen de / dat hemelrijk zijn zijn,Sidrac,Jans teesteye,None,None,0.547425
183,Die drievuldicheit in hare / Daer by eest openbare,Wouter dus sijn openbare / Die gheloven comen hare,die drievuldigheid in haar / daar bij zijn het openbaar,NOU-P dus zijn openbaar / die geloof komen haar,Sidrac,Jans teesteye,None,None,0.547432
75,Uten Grixe dat hy conste wale / Ende oec ute Ebreusche tale,Deen es behendech ende mach wale / Gheven ende can oec wel sijn tale,uit dat griks dat hij kunnen wel / en ook uit Ebreus taal,de een zijn behendig en mogen wel / geven en kunnen ook wel zijn taal,Sidrac,Jans teesteye,None,None,0.550639
175,Die de Vader alsoe minde / Dat hy sinen heylegen Geest sinde,Diemen te deser werelt mint / Werdt in deser bitterheyt gheint,die de vader alzo minnen / dat hij zijn heilig geest einden,die men te deze wereld minnen / worden in deze bitterheid einden,Sidrac,Jans teesteye,None,None,0.553319

In [19]:
nearest_df = nearest_verses('Melibeus', 'Dietsche doctrinale',
                            base_df=df, vectorizer=vec, prop_filt=2)
nearest_df = nearest_df.sort_values(by='distance')
nearest_df.to_excel('../figures/parallel_verses/melibeus-dietsche_doctrinale.xlsx')
nearest_df.head(50)

,tokens1,tokens2,lemmas1,lemmas2,title1,title2,intertext1,intertext2,distance
3659,Seneca seghet noch dit woert / Dat nieman bat toe en hoert,Noch seit seneca dit woert / Dat niemanne bat toe en hoert,NOU-P zeggen nog dit woord / dat niemand bet toezenden ne hoeren,nog zeggen NOU-P dit woord / dat niemand bet toezenden ne hoeren,Melibeus,Dietsche doctrinale,None,None,0.000000
3245,Gheeft mi op die wrake / Ic sal lonen die sake,Hi sprect gheeft mi op die wrake / Ende ic sal lonen die sake,geven ik op die wrake / ik zullen lonen die sake,hij spreken geven ik op die wrake / en ik zullen lonen die sake,Melibeus,Dietsche doctrinale,None,None,0.040383
1884,Die van vele lieden ontsien es / Moet vele lieden ontsien weder,Vele lieden hi moet van dien / Vele lieden weder ontsien,die van veel lieden ontzien zijn / moeten veel lieden ontzien weder,veel lieden hij moeten van dat / veel lieden weder ontzien,Melibeus,Dietsche doctrinale,None,None,0.049199
2341,Ende so wien men ontsiet / Ende mach ghemint wesen niet,Soe wien datmen ontsiet / En mach ghemint wesen niet,en zo wie men ontzien / en mogen minnen wezen niet,zo wie dat men ontzien / ne mogen minnen wezen niet,Melibeus,Dietsche doctrinale,None,None,0.062379
1267,Haddic enen voete inden grave / Nochtan so woudic leren,Haddic enen voet int graf / Nochtan soudic willen leren,hebben ik een voet in de graf / nochtan zo willen ik leren,hebben ik een voet in het graf / nochtan zullen ik willen leren,Melibeus,Dietsche doctrinale,None,None,0.065268
1352,Die wise paeus Innocentius / Scrijft in sine boeke aldus,Die paus innocentius / Scrijft in sinen boeke aldus,die wijs paus NOU-P / schrijven in zijn beuk aldus,die paus NOU-P / schrijven in zijn beuk aldus,Melibeus,Dietsche doctrinale,None,None,0.076405
1026,Salomon seghet die hoedt sinen mont / Hoedt sijn ziele talre stont,Soe wie hoeden can sinen mont / Hoet sine ziele talre stont,NOU-P zeggen die hoeden zijn mond / hoeden zijn ziel te al stonde,zo wie hoeden kunnen zijn mond / hoeden zijn ziel te al stonde,Melibeus,Dietsche doctrinale,None,None,0.091876
2265,Wat si u segghen ende tonen / Hoedt u altoes jeghene honen,Watsi segghen ofte tonen / Hoedt u altoes jeghen honen,wat zij u zeggen en tonen / hoeden u altoos jegen hoon,watsie zeggen ofte tonen / hoeden u altoos jegen hoon,Melibeus,Dietsche doctrinale,None,None,0.107855
1466,Want stercmoedecheyt wet wale / Es een der doghet cardinale,Want hets ene doeght wet dat wale / Van iiij doeghden cardinale,want sterkmoedigheid wetten wel / zijn een de deugd kardinaal,want het zijn een deugd wetten dat wel / van vier deugd kardinaal,Melibeus,Dietsche doctrinale,None,None,0.110409
3215,Roepen ghemeynlijc over al / Datmen cracht met crachten weren sal,Roepen alle al ouer al / Datmen cracht met crachte weren sal,roepen gemeenlijk over al / dat men kracht met kracht weren zullen,roepen al al over al / dat men kracht met kracht weren zullen,Melibeus,Dietsche doctrinale,None,None,0.112594
1268,Nochtan so woudic leren / Daer af comt so vele eren,Nochtan soudic willen leren / Daer coemt af soe vele eren,nochtan zo willen ik leren / daar af komen zo veel eer,nochtan zullen ik willen leren / daar komen af zij veel eer,Melibeus,Dietsche doctrinale,None,None,0.116499
766,Als of hi ons woude maken vroet / Dat gheen dinc en es so goet,Seneca maect ons vroet / Dat gheen dinc en es soe goet,als of hij ons willen maken vroed / dat geen ding ne zijn zo goed,NOU-P maken ons vroed / dat geen ding ne zijn zo goed,Melibeus,Dietsche doctrinale,None,None,0.117634
1547,Die saen een dinc verstaen heeft / Ende traechelijc sijn vonnes gheeft,Die de dinc cort verstaen heeft / Ende traechlec sijn vonnesse gheeft,die zaan een ding verstaan hebben / en tragelijk zijn vonnis geven,die de ding kort verstaan hebben / en tragelijk zijn vonnis geven,Melibeus,Dietsche doctrinale,None,None,0.118493
866,Want si can verre voersien / Dinghen die moghen ghescien,Ende wijsheit can verre vorsien / Dinghen die moeghen ghescien,want zij kunnen verre voorzien / ding die mogen geschieden,en wijsheid kunnen verre voorzien / ding die mogen geschieden,Melibeus,Dietsche doctrinale,None,None,0.128208
1170,Want prijs ende lof in eygenen mont / Wert onsuver talre stont,Lof ende prijs in eyghenen mont / Wert onstinert talre stont,want prijs en lof in eigen mond / worden onzuiver te al stond,lof en prijs in eigen mond / worden ontineren te al stond,Melibeus,Dietsche doctrinale,None,None,0.132276
3231,Hets beter in tijts weder staen / Dan namaels ter wraken ghegaen,Hets beter te tide weder staen / Dan namaels ter wraken vaen,het zijn goed in tijd wederen staan / dan namaals ter wraak gaan,het zijn goed te tijd wederen staan / dan namaals ter wraak vangen,Melibeus,Dietsche doctrinale,None,None,0.145503
1266,Een wijs man seghet aldus hier ave / Haddic enen voete inden grave,Die wise man sprect hier af / Haddic enen voet int graf,een wijs man zeggen aldus hier af / hebben ik een voet in de graf,die wijs man spreken hier af / hebben ik een voet in het graf,Melibeus,Dietsche doctrinale,None,None,0.145985
3735,Dbeghin van vrienscapen es / Wel spreken sijts gewes,Dbeghin van vrienscapen es / Wel spreken sijds ghewes,het begin van vriendschap zijn / wel spreken zijn het gewis,het begin van vriendschap zijn / wel spreken zijds gewis,Melibeus,Dietsche doctrinale,None,None,0.153793
736,Hadde ghemaect sprac hi ten saken / Laet ons hem een hulpe maken,Sprac hi mede dese saken / Laet ons hem ene hulpe maken,"hebben maken spreken hij ten zaak / laten ons hij een hulp, help maken","spreken hij mijden deze zaak / laten ons hij een hulp, help maken",Melibeus,Dietsche doctrinale,None,None,0.156357
2275,Ghine sult niet ontsien allene / Die grote viande maer oec die clene,Ghine selt niet doen allene / Die grote maer oec die clene,gij ne zullen niet ontzien alleen / die groot vijand maar ook die klein,gij ne zullen niet doen alleen / die groot maar ook die klein,Melibeus,Dietsche doctrinale,None,None,0.157446
2259,Die ghi in allen stonden / Goet en ghetruwe hebt vonden,Dan hem dien ghi tanderen stonden / Goet ende ghetrouwe hebt vonden,die gij in al stond / goed en getrouw hebben vinden,dan hij dat gij te ander stond / goed en getrouw hebben vinden,Melibeus,Dietsche doctrinale,None,None,0.162992
2340,Want hi es van hem ontsien / Ende so wien men ontsiet,Men sal die doet ontsien niet / Want soe wie die doet onsiet,want hij zijn van hij ontzien / en zo wie men ontzien,men zullen die doen ontzien niet / want zo wie die doen ontzien,Melibeus,Dietsche doctrinale,None,None,0.166745
1709,Ghereckelijc willen gaen voert / Alsoe der eersaemheyt toe behoert,Want soe wat si setten voert / Der eersamheit toe behoert,gerekkelijk willen gaan voeren / alzo de eerzaamheid toezenden behoren,want zo wat zij zetten voeren / de eerzaamheid toezenden behoren,Melibeus,Dietsche doctrinale,None,None,0.174421
1901,Want die quade dat verstaet / En gaf hem selden noyt goeden raet,Want hi selden dat verstaet / Hem seluen gheeft goeden raet,want die kwaad dat verstaan / ne geven hij zeld nooit goed raad,want hij zeld dat verstaan / hij zelf geven goed raad,Melibeus,Dietsche doctrinale,None,None,0.180252
774,Hi seghet dat gheen dinc en gheyt / Boven wijfs goedertierenheyt,Dat twijfs goedertierenheit gaet / Bouen alle goedertietenheit,hij zeggen dat geen ding ne gaan / boven wijf goedertierenheid,dat het wijf goedertierenheid gaan / boven al goedertietenheid,Melibeus,Dietsche doctrinale,None,None,0.195690
1899,DEs quaets menschen raet wats ghesciet / En sal men emmer volghen niet,Tquaets menschen raet wats gesciet / En salmen oec volghen niet,de kwaad mens raad wat geschieden / en zullen men immer volgen niet,het kwaadsen mens raad wat geschieden / ne zullen men ook volgen niet,Melibeus,Dietsche doctrinale,None,None,0.205645
1675,Vrienden die ghi in stonden / Goet ende ghetruwe hadt vonden,Dan hem dien ghi tanderen stonden / Goet ende ghetrouwe hebt vonden,vriend die gij in stond / goed en getrouw hebben vinden,dan hij dat gij te ander stond / goed en getrouw hebben vinden,Melibeus,Dietsche doctrinale,None,None,0.207952
2423,Ende sonderlinghe wet wel dat / Int besetten van eenre stat,Ende sunderlinghe wet wel dat / Moet men rechten in ene stat,en zonderling wetten wel dat / in het bezette van een stad,en zonderling wetten wel dat / moeten men rechten in een stad,Melibeus,Dietsche doctrinale,None,None,0.208580
1033,Es die wijste seyt die wise man / Het es alte grote scande den man,Hi ware wijs die dat dade / Iheronimus seit die wise man,zijn die wijs zeggen die wijs man / het zijn al te groot schande de man,hij zijn wijs die dat doen / NOU-P zeggen die wijs man,Melibeus,Dietsche doctrinale,None,None,0.210413
2355,EEn der yrster creaturen / Die de meester der naturen,Onder allen creaturen / Heeft die meester der naturen,een de eerst creatuur / die de meester de natuur,onder al creatuur / hebben die meester de natuur,Melibeus,Dietsche doctrinale,None,None,0.210461
1555,Maer met goeder gestadecheyt / Also ons Seneca seyt,Maer met goeder ghestadecheit / Die wise salomon aldus seit,maar met goed gestadigheid / alzo ons NOU-P zeggen,maar met goed gestadigheid / die wijze NOU-P aldus zeggen,Melibeus,Dietsche doctrinale,None,None,0.215304
764,Dat wijf es beter menechfout / Dan ghesteynte silver of gout,Die dicke es menichfout / Beter dan siluer oft gout,dat wijf zijn goed menigvout / dan gesteente zilver of goud,die dik zijn menigvout / goed dan zilver of goud,Melibeus,Dietsche doctrinale,None,None,0.217456
3571,Gratie es beter menechfout / Dan zilver es ofte gout,Die dicke es menichfout / Beter dan siluer oft gout,gratie zijn goed menigvout / dan zilver zijn ofte goud,die dik zijn menigvout / goed dan zilver of goud,Melibeus,Dietsche doctrinale,None,None,0.219912
3216,Datmen cracht met crachten weren sal / Men sal oec vechten starc ende stijf,Datmen cracht met crachte weren sal / Niet om wrake te doene stijf,dat men kracht met kracht weren zullen / men zullen ook vechten sterk en stijf,dat men kracht met kracht weren zullen / niet om wrake te doen stijf,Melibeus,Dietsche doctrinale,None,None,0.220638
3411,Ende in uw goedertierenhede / Ende in Melibeus mede,In wercken ende in worden mede / Ende in alle goedertierenhede,en in uw goedertierenheid / en in NOU-P mede,in werk en in woord mede / en in al goedertierenheid,Melibeus,Dietsche doctrinale,None,None,0.223605
2601,Want hem dander quadien / Daer bi te bat castien,Ende dat hem die quadien / Daer af selen castien,want hij de ander kwadie / daar bij te bet kastijden,en dat hij die kwadie / daar af zullen kastijden,Melibeus,Dietsche doctrinale,None,None,0.231723
838,Ende datmen ter doghet sal tien / Ende dat quade altoes vlien,Ende datmen ten besten tie / Ende dat quade altoes vlie,en dat men ter deugd zullen tijgen / en dat kwaad altoos vlieden,en dat men ten beste tijgen / en dat kwaad altoos vlieden,Melibeus,Dietsche doctrinale,None,None,0.232944
2609,Die selen pinen die quadien / Ende van hare quaetheyt castien,Ende dat hem die quadien / Daer af selen castien,die zullen pijnen die kwadie / en van haar kwaadheid kastijden,en dat hij die kwadie / daar af zullen kastijden,Melibeus,Dietsche doctrinale,None,None,0.235729
3770,Nu segt Amen ghemeynlike / AMEN,Amen amen / Vander gods minnen hebdi gehoert,nu zeggen amen gemeenlijk / amen,amen amen / van de NOU-P min hebben gij horen,Melibeus,Dietsche doctrinale,None,None,0.235966
1975,Ende wies princen vroech eten / Marcus doet ons oec weten,Coninc es dat doet hi weten / Ende daer die princen vroech eten,en wes prins vroeg eten / NOU-P doen ons ook weten,koning zijn dat doen hij weten / en daar die prins vroeg eten,Melibeus,Dietsche doctrinale,None,None,0.239422
238,Salomon seghet die wise man / Die alle dinc doen can,Ia dat die doet gheuen can / Salomon seit die wise man,NOU-P zeggen die wijs man / die al ding doen kunnen,ja dat die doen geven kunnen / NOU-P zeggen die wijs man,Melibeus,Dietsche doctrinale,None,None,0.240246
2233,Ende en loent vroech ende spade / Niemans quaet met quade,Ende wacht emmer vroech ende spade / Dat ghi nien loent goet met quade,en ne loenen vroeg en spade / niemand kwaad met kwaad,en wachten immer vroeg en spade / dat gij nie loenen goed met kwaad,Melibeus,Dietsche doctrinale,None,None,0.240581
1767,Vonnest u selven vroech ende spade / Dats beter dan oft een ander dade,Dan v goet soe hebdi ere / Ghebiet v seluen vroech ende spade,vonnissen u zelf vroeg en spa / dat zijn goed dan of een ander dat,dan uw goed zo hebben gij een / gebieden u zelf vroeg en spa,Melibeus,Dietsche doctrinale,None,None,0.246258
794,Ende draghet sorghe ende hoede / Van sinen live van sinen goede,Want hi es besceermere ende hoede / Van horen liue ende goede,en dragen zorg en hoede / van zijn lijf van zijn goed,want hij zijn bescheermer en hoede / van haar lijf en goed,Melibeus,Dietsche doctrinale,None,None,0.247146
3495,Doe si int huus quamen ghegaen / Es Melibeus opghestaen,Doe cristus was opghestaen / Ende inden weghe quam ghegaen,toen zij in het huis komen gaan / zijn NOU-P opstaan,toen NOU-P zijn opstaan / en in de weg komen gaan,Melibeus,Dietsche doctrinale,None,None,0.251057
1653,Ende so wie die vindet dat / Hi vint enen groten scat,Die ghetrouwen vrient vint / Dat hi vint enen scat,en zo wie die vinden dat / hij vinden een groot schat,die getrouw vriend vinden / dat hij vinden een schat,Melibeus,Dietsche doctrinale,None,None,0.251379
839,Ende dat quade altoes vlien / Also Cassiodorus seyt,Ende dat quade altoes vlie / Seneca seit dat wijsheit can,en dat kwaad altoos vlieden / alzo NOU-P zeggen,en dat kwaad altoos vlieden / NOU-P zeggen dat wijsheid kunnen,Melibeus,Dietsche doctrinale,None,None,0.251594
2837,Hemelrijc dat es waer / Haer en es niet te swaer,Arestotiles hi seeght waer / Den studere en es niet te swaer,hemelrijk dat zijn waar / zij ne zijn niet te zwaar,NOU-P hij zeggen waar / de studeerder ne zijn niet te zwaar,Melibeus,Dietsche doctrinale,None,None,0.256220
1288,Dus selen clercken sijn die leren / Die hem ter wijsheyt willen keren,Die hem ter wijsheit wille keren / Sal int ierste moeten leren,dus zullen klerk zijn die leren / die hij ter wijsheid willen keren,die hij ter wijsheid willen keren / zullen in het eerst moeten leren,Melibeus,Dietsche doctrinale,None,None,0.257061
2969,Te vele armoeds noch rijcheden / Maer houdt mi in middelheden,Armoede noch rijcheit en gheeft mi / Dese begheerde middelhede,te veel armoed noch rijkheid / maar houden ik in middelheid,armoede noch rijkheid ne geven ik / deze begeerd middelheid,Melibeus,Dietsche doctrinale,None,None,0.260428

In [20]:
nearest_df = nearest_verses('Brabantsche yeesten (B5)', 'Dietsche doctrinale',
                            base_df=df, vectorizer=vec, prop_filt=2)
nearest_df = nearest_df.sort_values(by='distance')
nearest_df.to_excel('../figures/parallel_verses/yeesten_5-dietsche_doctrinale.xlsx')
nearest_df.head(50)

,tokens1,tokens2,lemmas1,lemmas2,title1,title2,intertext1,intertext2,distance
2334,Nochtan in allen manieren / Soe was hi hem goedertieren,Ontfermhertech ende goedertieren / Es hi in allen manieren,nochtan in al manier / zo zijn hij hij goedertieren,ontfermhartig en goedertieren / zijn hij in al manier,Brabantsche yeesten (B5),Dietsche doctrinale,None,None,0.123103
844,Daer hi mochte vroech ende spade / Beide met rade ende met dade,Den bedroefden vroech ende spade / Troesten met rade ende met dade,daar hij mogen vroeg en spade / beide met raad en met daad,de bedroefde vroeg en spade / troosten met raad en met daad,Brabantsche yeesten (B5),Dietsche doctrinale,None,None,0.150772
1050,Oec doetmen met wisen rade / Datmen met crachten niet en dade,Want men doet met wisen rade / Datmen met crachte niet en dade,ook doen men met wijs raad / dat men met kracht niet ne doen,want men doen met wijze raad / dat men met kracht niet ne doen,Brabantsche yeesten (B5),Dietsche doctrinale,None,None,0.178545
3921,Souden al te nieute keren / Ende dat hi met Gode ende met eren,Ende hem te sulker neren keren / Die met gode si ende met eren,zullen al te niet keren / en dat hij met NOU-P en met eer,en hij te zulk neer keren / die met NOU-P zijn en met eer,Brabantsche yeesten (B5),Dietsche doctrinale,None,None,0.191088
1144,Ende dat hi om sinen wille allene / Ende om ander dinc en ghene,Ende oec om ander dinc en ghene / Dan om dese viere allene,en dat hij om zijn wil alleen / en om ander ding ne gene,en ook om ander ding ne gene / dan om deze vuur alleen,Brabantsche yeesten (B5),Dietsche doctrinale,None,None,0.240140
2983,Ende gherne sach si vrede / Eendrachticheit te waren,Van starcmoedecheiden / Van vreden ende eendrachtecheiden,en gaarne zien zij vrede / eendrachtigheid te zijn,van sterkmoedigheid / van vrede en eendrachtigheid,Brabantsche yeesten (B5),Dietsche doctrinale,None,None,0.241958
1114,Een grooten pot van metale / Diene daer liet weet men wale,Nemt enen pot van motale / Ende enen anderen daer bi,een groot pot van metaal / die hij daar laten weten men wel,nemen een pot van metaal / en een ander daar bij,Brabantsche yeesten (B5),Dietsche doctrinale,None,None,0.252542
3432,Ende oec swegher die ghelike / Edewaerts van Enghelant,En mach niet sijn haer ghelike / Ihesus sydrac seit des ghelike,en ook zweger die gelijke / edewaarts van NOU-P,ne mogen niet zijn haar gelijke / NOU-P NOU-P zeggen de gelijke,Brabantsche yeesten (B5),Dietsche doctrinale,None,None,0.262970
1113,Wart daer vonden heb ic vernomen / Een grooten pot van metale,Nemt enen pot van motale / Ende enen anderen daer bi,worden daar vinden hebben ik vernemen / een groot pot van metaal,nemen een pot van metaal / en een ander daar bij,Brabantsche yeesten (B5),Dietsche doctrinale,None,None,0.268512
3188,Van rechte den Almaenschen rike / Dat si daden groot onghelike,Metten hoeuerdeghen riken / Want si sere ongheliken,van rechte de Almaans rijk / dat zij doen groot ongelijk,met de hoevaardige rijk / want zij zeer ongelijk,Brabantsche yeesten (B5),Dietsche doctrinale,None,None,0.275709
4011,Alsoe ons wel maect ghewes / Die wise Aristotiles,Alsoe langhe als si leuen sal / Seneca maect ons ghewes,alzo ons wel maken gewes / die wijze NOU-P,alzo lang als zij leven zullen / NOU-P maken ons gewes,Brabantsche yeesten (B5),Dietsche doctrinale,None,None,0.279036
1060,Nochtan hadden si ghenoech / Van vitalien al haer ghevoech,Al geloeft men wel int geuoech / Dat en es nochtan niet genoech,nochtan hebben zij genoeg / van NOU-P al haar gevoeg,al loven men wel in het gevoeg / dat ne zijn nochtan niet genoeg,Brabantsche yeesten (B5),Dietsche doctrinale,None,None,0.281895
48,Die in hate ende in nijt / Ghestaen hadden langhe tijt,Ende en wilt in gheenre tijt / In haet ligghen no in nijt,die in haat en in nijd / gestaan hebben lang tijd,en ne willen in gene tijd / in haat liggen noch in nijd,Brabantsche yeesten (B5),Dietsche doctrinale,None,None,0.292032
3996,Doemen screef Ons Heren jaer / Dertien hondert ende veertach,Doen men screef cristus gheboert / Dertiene hondert ende xl voert,toen men schrijven ons heer jaar / dertien honderd een veertig,toen men schrijven NOU-P gebeuren / dertien honderd een veertig voort,Brabantsche yeesten (B5),Dietsche doctrinale,None,None,0.298459
758,Die de honde als ende als / Wanen hebben opten hals,Maer soe wiese ontsiet als ende als / Waentse altoes hebben opten hals,die de hond als en als / wanen hebben op de hals,maar zo wezen ontzien als en als / wanen zij altoos hebben op de hals,Brabantsche yeesten (B5),Dietsche doctrinale,None,None,0.298741
2010,Doen die hertoghe dat vernam / Dat die grave tote hem quam,Ende doen hi oec vernam / Dat judaes tote hem quam,toen die hertog dat vernemen / dat die graf tot hij komen,en toen hij ook vernemen / dat NOU-P tot hij komen,Brabantsche yeesten (B5),Dietsche doctrinale,None,None,0.308748
2022,Oec waest Brusele bi ghenoech / Ende hi vant daer sijn ghevoech,Bedi haren sin int gheuoech / En es daer toe niet ripe ghenoech,ook zijn NOU-P bij gevoeg / en hij vinden daar zijn gevoeg,bedie haar zin in het gevoeg / ne zijn daar toe niet rijp gevoeg,Brabantsche yeesten (B5),Dietsche doctrinale,None,None,0.310172
1754,Beide van live ende van goede / Ende dede setten nauwe hoede,Want hi es besceermere ende hoede / Van horen liue ende goede,beide van lijf en van goed / en doen zetten nauw hoede,want hij zijn bescheermer en hoede / van haar lijf en goed,Brabantsche yeesten (B5),Dietsche doctrinale,None,None,0.312400
3619,Dant is in den mensche / Dits een woord van wensche,Beide te gode ende ten mensche / Dits een minne van groten wensche,dan het zijn in de mens / dit zijn een woord van wens,beide te NOU-P en ten mens / dit zijn een minne van groot wens,Brabantsche yeesten (B5),Dietsche doctrinale,None,None,0.315220
914,Want hi hadde lude ende stille / Ghedaen al gader sinen wille,En oec seldi lude ende stille / Beide sijn van enen wille,want hij hebben luid en stil / doen gader zijn wil,en ook zullen gij luid en stil / beide zijn van een wil,Brabantsche yeesten (B5),Dietsche doctrinale,None,None,0.328770
4012,Die wise Aristotiles / Maer hoe hoghe si climmen int deinde,Hoe hoegh si clemmen nochtan soude si / Hoghere clemmen mochtsi,die wijze NOU-P / maar hoe hoog zij klimmen in het denie,hoe hoog zij klimmen nochtan zullen zij / hoog klimmen mogen zij,Brabantsche yeesten (B5),Dietsche doctrinale,None,None,0.330873
3107,Want hi ware des rijcx man / Dat hi ente sine souden,Vanden sinen ghemint si / Want hine es maer een man,want hij zijn de rijk man / dat hij en zijne zullen,van de zijne gemint zij / want hij ne zijn maar een man,Brabantsche yeesten (B5),Dietsche doctrinale,None,None,0.343317
2864,Porden ridderen ende knapen / Te Brabant waert metter wapen,Noch hem oec setten te wapen / Ghelijc riddren ende scilt knapen,poord ridder en knaap / te NOU-P zijn het met de wapen,noch hij ook zetten te wapen / gelijk ridder en schild knaap,Brabantsche yeesten (B5),Dietsche doctrinale,None,None,0.349730
3869,Ende hi dan hem verheft daer in / Soe acht God sijns te min,Hi mochte hem verheffen daer in / Ende der gratien hebben te min,en hij dan hij verheffen daar in / zo achten NOU-P zijn te min,hij mogen hij verheffen daar in / en de gratie hebben te min,Brabantsche yeesten (B5),Dietsche doctrinale,None,None,0.350305
2926,Ende daer vore des sijt vroet / Heeft die hertoghe ander goet,Sijn in hem seluen herde goet / Maer si hebben des sijt vroet,en daar voor des zijde vroed / hebben die hertog ander goed,zijn in hij zelf hard goed / maar zij hebben des zijde vroed,Brabantsche yeesten (B5),Dietsche doctrinale,None,None,0.350927
2986,Ende beterde alle dinghe / Oec was si sonderlinghe,Ende oec vore gode sunderlinghe / Ghehaedt vore alle dinghe,en beteren al ding / ook zijn zij zonderling,en ook voor NOU-P zonderling / hebben voor al ding,Brabantsche yeesten (B5),Dietsche doctrinale,None,None,0.359519
1008,Want hi duchte in sinen waen / Dat hem af souden gaen,Ende inder noet niet af gaen / Hi saelt doen sonder waen,want hij duchten in zijn waan / dat hij afvangen zullen gaan,en in de nood niet afvangen gaan / hij zullen doen zonder waan,Brabantsche yeesten (B5),Dietsche doctrinale,None,None,0.361278
1047,Dan sijn liede taventuerne / Want die wiselic verbeiden mach,Maer sal wijslec verbeiden / Ende striden met sinnecheiden,dan zijn lieden tavontuurne / want die wijselijk verbeiden mogen,maar zullen wijselijk verbeiden / en strijden met zinnigheid,Brabantsche yeesten (B5),Dietsche doctrinale,None,None,0.363827
3413,Ende hi die waerhiet wel vernam / Dat Philips doen niet en quam,Ende doen hi oec vernam / Dat judaes tote hem quam,en hij die waarheid wel vernemen / dat NOU-P toen niet ne komen,en toen hij ook vernemen / dat NOU-P tot hij komen,Brabantsche yeesten (B5),Dietsche doctrinale,None,None,0.364580
3775,Heimelic van daer met liste / Dats niemant daer en wiste,Die vele wijsheden wiste / Soe loent men daer list met liste,heimelijk van daar met list / dat zijn niemand daar ne wissen,die veel wijsheid wissen / zo loenen men daar list met list,Brabantsche yeesten (B5),Dietsche doctrinale,None,None,0.364975
854,Dat die hertoghe sijts ghewes / Van allen in hem bleven es,Ende in allen dien sijts ghewes / Dat ieghen gods wille es,dat die hertog zijn dat gewis / van al in hij blijven zijn,en in al dat zij het gewis / dat jegen NOU-P wil zijn,Brabantsche yeesten (B5),Dietsche doctrinale,None,None,0.365254
1362,In Vrancrike es hi ghekeert / Ende heeft den coninc daer gheleert,Ende eest dat hi sine wijsheit keert / Alsoe ic v hebbe gheleert,in NOU-P zijn hij keren / en hebben de koning daar leren,en zijn het dat hij zijn wijsheid keren / alzo ik u hebben leren,Brabantsche yeesten (B5),Dietsche doctrinale,None,None,0.365870
664,Der welker ic swighe stille / Om hoers selfs eren wille,En hebdi niet soe swighet stille / Ende gheeft gode den goeden wille,de welk ik zwijgen stillen / om haar zelf eer wil,ne hebben gij niet zo zwijgen stillen / en geven NOU-P de goed wil,Brabantsche yeesten (B5),Dietsche doctrinale,None,None,0.368902
692,Dat nochtan te doene was swaer / Want en staet dat es waer,Arestotiles hi seeght waer / Den studere en es niet te swaer,dat nochtan te doen zijn zwaar / want ne staan dat zijn waar,NOU-P hij zeggen waar / de studeerder ne zijn niet te zwaar,Brabantsche yeesten (B5),Dietsche doctrinale,None,None,0.369831
3179,Ende oec van daer niet sceiden / Hi en hadde ghesproken wet wel dat,Dat doet ons van gode sceiden / Men mach niet dienen dat wet wale,en ook van daar niet scheiden / hij ne hebben spreken wet wel dat,dat doen ons van NOU-P scheiden / men mogen niet dienen dat wet wel,Brabantsche yeesten (B5),Dietsche doctrinale,None,None,0.370126
411,In desen tiden quam die here / Van Scaffelberghe als ict versinne,Hertoghe sat ende here / Int iaer alsict versinne,in deze tijd komen die heer / van NOU-P als ik het verzinnen,hertog zitten en heer / in het jaar als zij verzinnen,Brabantsche yeesten (B5),Dietsche doctrinale,None,None,0.370766
1173,Ende sijns lants neringhe mede / Des si niet en hebben daer,Scuwet neringhen altoes mede / Daer in es onneersamhede,en zijn land nering mede / des zij niet ne hebben daar,schuwen nering altoos mede / daar in zijn onnederzaamheid,Brabantsche yeesten (B5),Dietsche doctrinale,None,None,0.379559
712,Van den heren metter spoet / Die hem ghemaect hadden den moet,Te houden sinen goeden moet / Oft hi bederft v metter spoet,van de heer met de spoed / die hij maken hebben de moet,te houden zijn goed moet / of hij bederven u met de spoed,Brabantsche yeesten (B5),Dietsche doctrinale,None,None,0.379588
2162,Bacheleren ende knapen mede / Al te Brusele in die stede,Ende oec v daer toe mede / Al tantwerpen in die stede,bachelaar en knaap mede / al te NOU-P in die stede,en ook u daar toe mede / al NOU-P in die stede,Brabantsche yeesten (B5),Dietsche doctrinale,None,None,0.380993
1924,Om dat ic der waerheit bi ga / Seker alse verre als ic versta,Ia alsoe verre dat verstaet / Alse sine iuridictie gaet,om dat ik de waarheid zijn gaan / zeker als verre als ik verstaan,ja alzo verre dat verstaan / als zijn jurisdictie gaan,Brabantsche yeesten (B5),Dietsche doctrinale,None,None,0.381818
3669,Mer hets om dinc als ic versta / Die licht volghen sal hier na,Die gode wille volghen na / Sal gheuen alsict versta,maar het zijn om ding als ik verstaan / die licht volgen zullen hier na,die NOU-P willen volgen na / zullen geven als zij verstaan,Brabantsche yeesten (B5),Dietsche doctrinale,None,None,0.386033
3243,Ende heeft aldus gheordineert / Dat die coninc van Behem,Die mensche es ghedisponeert / Van naturen ende gheordeneert,en hebben aldus ordineren / dat die koning van NOU-P,die mens zijn disponeren / van natuur en ordineren,Brabantsche yeesten (B5),Dietsche doctrinale,None,None,0.386349
4010,Te gader staen wats gheschiet / Alsoe ons wel maect ghewes,Alsoe langhe als si leuen sal / Seneca maect ons ghewes,te gader staan wat geschieden / alzo ons wel maken gewes,alzo lang als zij leven zullen / NOU-P maken ons gewes,Brabantsche yeesten (B5),Dietsche doctrinale,None,None,0.389298
3751,Ende sinen here sinen vader / Ende dat hi dat al gader,Kindre nv sijt alle gader / Onderdaen moeder ende vader,en zijn heer zijn vader / en dat hij dat al gader,kind nu zijn al gader / onderdaan moeder en vader,Brabantsche yeesten (B5),Dietsche doctrinale,None,None,0.390822
66,Met Otten hilden dat verstaet / Ieghen den hertoghe ende sinen raet,Ghi en selt nochtan dat verstaet / Met allen lieden niet hebben raet,met NOU-P houden dat verstaat / jegen de hertog en zijn raad,gij ne zullen nochtan dat verstaat / met al lieden niet hebben raad,Brabantsche yeesten (B5),Dietsche doctrinale,None,None,0.391023
34,Want hi noch was een kint / Ende ute hem selven dede twint,Wijs man hem seluen wel kint / Ende hi en verheft hem twint,want hij nog zijn een kind / en uit hij zelf doen twint,wijs man hij zelf wel kind / en hij ne verheffen hij twint,Brabantsche yeesten (B5),Dietsche doctrinale,None,None,0.391928
1799,Te Valencine daer si quamen / Dat si den hertoghe vroech ende spade,Herberghen daer toe mede / Den bedroefden vroech ende spade,te NOU-P daar zij komen / dat zij de hertog vroeg en spade,herbergen daar toe mede / de bedroefde vroeg en spade,Brabantsche yeesten (B5),Dietsche doctrinale,None,None,0.393135
2277,Si en sijns targher niet / Want hare doeght en can,Soe wie dat niet swighen en can / En can te poeinte spreken niet,zij ne zijn terger niet / want haar deugd ne kunnen,zo wie dat niet zwijgen ne kunnen / ne kunnen te poeinte spreken niet,Brabantsche yeesten (B5),Dietsche doctrinale,None,None,0.395007
366,Die hi hebben mochte sonder strijt / Karle oec in sijnre tijt,Die om dat gloue streden / Ende oec godeuaert van belioen,die hij hebben mogen zonder strijden / NOU-P ook in zijn tijd,die om dat glof strijden / en ook NOU-P van NOU-P,Brabantsche yeesten (B5),Dietsche doctrinale,None,None,0.397021
699,Ende die stede die borch mede / Soe dat elc sijt seker das,In ene ander stede hi seit mede / Die ghene es seker telker stede,en die stede die borg mede / zo dat elk zijn zeker dat,in een ander stede hij zeggen mede / die gene zijn zeker te elk stede,Brabantsche yeesten (B5),Dietsche doctrinale,None,None,0.398438

In [21]:
nearest_df = nearest_verses('Brabantsche yeesten (B5)', 'Van den derden Eduwaert',
                            base_df=df, vectorizer=vec, prop_filt=2)
nearest_df = nearest_df.sort_values(by='distance')
nearest_df.to_excel('../figures/parallel_verses/yeesten_5-eduwaert.xlsx')
nearest_df.head(50)

,tokens1,tokens2,lemmas1,lemmas2,title1,title2,intertext1,intertext2,distance
3291,Daer al dlant an viel sere / Ieghen den grave sinen here,Daer al tlant an viel seere / Jegen den grave sinen heere,daar al dat land aan vallen zeer / jegen de graf zijn heer,daar al dat land aan vallen zeer / jegen de graf zijn heer,Brabantsche yeesten (B5),Van den derden Eduwaert,None,None,0.000000e+00
3046,Ende die grave van Gulke met / Dies beide hadden te bet,Ende die grave van Gulken met / Dies beide hadden te bet,en die graf van NOU-P met / dies beide hebben te bet,en die graf van NOU-P met / dies beide hebben te bet,Brabantsche yeesten (B5),Van den derden Eduwaert,None,None,0.000000e+00
3297,Ende die grave van Hollant mede / Met consent van elker stede,Ende die grave van Hollant mede / Met consente van elker stede,en die graf van NOU-P mede / met consent van elk stede,en die graf van NOU-P mede / met consent van elk stede,Brabantsche yeesten (B5),Van den derden Eduwaert,None,None,0.000000e+00
3303,Ieghen elc lant ende elken here / Ende dit soude dueren emmermere,Jegen elc lant ende elken heere / Ende dit soude duren emmermeere,jegen elk land en elk heer / en dit zullen duren immermeer,jegen elk land en elk heer / en dit zullen duren immermeer,Brabantsche yeesten (B5),Van den derden Eduwaert,None,None,1.110223e-16
3260,Doen die heren hoerden clare / Dat die hertoghe noch was dare,Doe die heeren hoerden claer / Dat die hertoge noch waere daer,toen die heer hoeren klaar / dat die hertog nog zijn daar,toen die heer hoeren klaar / dat die hertog nog zijn daar,Brabantsche yeesten (B5),Van den derden Eduwaert,None,None,2.220446e-16
3047,Dies beide hadden te bet / Want si in dit bedrijf tsamen,Dies beide hadden te bet / Want sij in dit bedrijf te samen,dies beide hebben te bet / want zij in dit bedrijf samen,dies beide hebben te bet / want zij in dit bedrijf te samen,Brabantsche yeesten (B5),Van den derden Eduwaert,None,None,1.129491e-02
3259,Oft opt velt te samen sterven / Doen die heren hoerden clare,Oft opt velt tesamen sterven / Doe die heeren hoerden claer,of op het veld te samen sterven / toen die heer hoeren klaar,of op het veld samen sterven / toen die heer hoeren klaar,Brabantsche yeesten (B5),Van den derden Eduwaert,None,None,1.325763e-02
3050,Want deen wil heten hertoghe / Ende dander marcgrave hoghe,Want deene wilt heeten hertoge / Ende dandre een marcgrave hoge,want de een willen heten hertog / en de ander markgraaf hoog,want de een willen heten hertog / en de ander een markgraaf hoog,Brabantsche yeesten (B5),Van den derden Eduwaert,None,None,1.414189e-02
3301,Dat elc soude anderen wale / Helpen houden sine pale,Ende elc soude andren wale / Helpen houden sine pale,dat elk zullen ander wel / helpen houden zijn paal,en elk zullen ander wel / helpen houden zijn paal,Brabantsche yeesten (B5),Van den derden Eduwaert,None,None,1.473972e-02
3450,Soe en soude kerstenhede / Die scade nemmermeer verwinnen,Sone soude dat kerstenhede / De scade nemmermeer verwinnen,zo ne zullen kerstenheid / die schade nimmermeer verwinnen,zo ne zullen dat kerstenheid / de schade nimmermeer verwinnen,Brabantsche yeesten (B5),Van den derden Eduwaert,None,None,2.631090e-02
3286,Die soe wart ghetoghen voert / Dat al dlant ane hem vel,Doe so wart getogen voert / Dat al tlant an hem vel,die zo worden tijgen voort / dat al dat land aan hij vellen,toen zo worden tijgen voort / dat al dat land aan hij vellen,Brabantsche yeesten (B5),Van den derden Eduwaert,None,None,3.257252e-02
2810,Sinen raet al ghemene / Daer soe droechmen over ene,Soe droechmen daer over een / Metten rade al gemeen,zijn raad al gemeen / daar zo dragen men over een,zo dragen men daar over een / met de raad al gemeen,Brabantsche yeesten (B5),Van den derden Eduwaert,None,None,4.388607e-02
3051,Ende dander marcgrave hoghe / Dat si in dit bedrijf wonnen,Ende dandre een marcgrave hoge / Dat sij in dat bedrijf gewonnen,en de ander markgraaf hoog / dat zij in dit bedrijf winnen,en de ander een markgraaf hoog / dat zij in dat bedrijf winnen,Brabantsche yeesten (B5),Van den derden Eduwaert,None,None,4.428083e-02
3458,Dat mens hem ewelijc ere soude spreken / Die hertoghe sach wel ende verstoet,Men soude hem ewelijc eere spreken / Die hertoge die wel verstoet,dat men hij eeuwelijk eer zullen spreken / die hertog zien wel en verstaan,men zullen hij eeuwelijk eer spreken / die hertog die wel verstaan,Brabantsche yeesten (B5),Van den derden Eduwaert,None,None,6.232693e-02
3283,Nu wart binnen Ghent verhaven / Een knape niet rike van haven,Binnen Ghent so was verhaven / Een knape niet rike van haven,nu worden binnen NOU-P verheffen / een knaap niet rijk van haven,binnen NOU-P zo zijn verheffen / een knaap niet rijk van haven,Brabantsche yeesten (B5),Van den derden Eduwaert,None,None,7.197901e-02
3052,Dat si in dit bedrijf wonnen / Wants hem die keiser woude onnen,Dat sij in dat bedrijf gewonnen / Want hem die keyser des woude onnen,dat zij in dit bedrijf winnen / want dat hij die keizer willen onnen,dat zij in dat bedrijf winnen / want hij die keizer des willen onnen,Brabantsche yeesten (B5),Van den derden Eduwaert,None,None,7.344925e-02
3449,Ende waert dat men strede / Soe en soude kerstenhede,Datmen daer omme strede / Sone soude dat kerstenhede,en zijn het dat men strijden / zo ne zullen kerstenheid,dat men daar om strijden / zo ne zullen dat kerstenheid,Brabantsche yeesten (B5),Van den derden Eduwaert,None,None,1.025811e-01
3464,Ende bracht daer toe int leste / Dattet quam tenen bestande,Si brachtene daer toe int lest / Dat wesen soude een bestant,en brengen daar toe in het leste / dat het komen te een bestand,zij brengen daar toe in het leste / dat wezen zullen een bestand,Brabantsche yeesten (B5),Van den derden Eduwaert,None,None,1.050635e-01
3048,Want si in dit bedrijf tsamen / Hoechden haers titels namen,Want sij in dit bedrijf te samen / Hoechden hoirs titels namen,want zij in dit bedrijf samen / hoogte haar titel nemen,want zij in dit bedrijf te samen / hogen haar titel nemen,Brabantsche yeesten (B5),Van den derden Eduwaert,None,None,1.071665e-01
426,Dat hi Hoesdinne heeft ieghen / Den here van Scaffenberghe vercreghen,Van doen hij hadde vercregen / Crevecuer ende Alut jegen,dat hij hoesdin hebben jegen / de heer van NOU-P verkrijgen,van toen hij hebben verkrijgen / creveceur en alut jegen,Brabantsche yeesten (B5),Van den derden Eduwaert,None,None,1.233629e-01
3287,Dat al dlant ane hem vel / Spreken consti harde wel,Dat al tlant an hem vel / Maer hij conste spreken wel,dat al dat land aan hij vellen / spreken kunnen gij hard wel,dat al dat land aan hij vellen / maar hij kunnen spreken wel,Brabantsche yeesten (B5),Van den derden Eduwaert,None,None,1.256790e-01
3049,Hoechden haers titels namen / Want deen wil heten hertoghe,Hoechden hoirs titels namen / Want deene wilt heeten hertoge,hoogte haar titel nemen / want de een willen heten hertog,hogen haar titel nemen / want de een willen heten hertog,Brabantsche yeesten (B5),Van den derden Eduwaert,None,None,1.274650e-01
3343,Met een deel groter scepen / Ende heeft dat Swin begrepen,Van Vrancrike Philips scepen / Die dat Swin hadden begrepen,met een deel groot schepen / en hebben dat zwin begrijpen,van NOU-P NOU-P schepen / die dat zwin hebben begrijpen,Brabantsche yeesten (B5),Van den derden Eduwaert,None,None,1.442594e-01
3288,Spreken consti harde wel / Ende wart van groten ghewelde,Maer hij conste spreken wel / Ende wart van groeter gewelde,spreken kunnen gij hard wel / en worden van groot geweld,maar hij kunnen spreken wel / en worden van groot geweld,Brabantsche yeesten (B5),Van den derden Eduwaert,None,None,1.478432e-01
3254,Quam een man ende brachte hem mare / Dat die hertoghe noch daer ware,Ende brachte hem selke mare / Dat die hertoge noch daer waere,komen een man en brengen hij mare / dat die hertog nog daar zijn,en brengen hij zulk mare / dat die hertog nog daar zijn,Brabantsche yeesten (B5),Van den derden Eduwaert,None,None,1.528494e-01
3333,Onder Vlaminghe ende Brabantsoene / Ende Heinewiere vroem ende coene,Vlaminge ende Brabantsoene / Die hem wouden maken coene,onder Vlaming en Brabantsoen / en henewier vroom en koen,Vlaming en Brabantsoen / die hij willen maken koen,Brabantsche yeesten (B5),Van den derden Eduwaert,None,None,1.802295e-01
3236,Ende dat Eduwaert met sijnre ghewelt / Noch daer laghe op dat velt,Doen sij daer dus mit gewelt / Gelegen hadden op dat velt,en dat NOU-P met zijn geweld / nog daar liggen op dat veld,toen zij daar dus met geweld / liggen hebben op dat veld,Brabantsche yeesten (B5),Van den derden Eduwaert,None,None,1.848525e-01
1818,Daer bi droeghen si over een / In haren raet al ghemeen,Soe droechmen daer over een / Metten rade al gemeen,daar bij dragen zij over een / in haar raad al gemeen,zo dragen men daar over een / met de raad al gemeen,Brabantsche yeesten (B5),Van den derden Eduwaert,None,None,1.856873e-01
3455,Ane paepscap ende ane nonnen mede / Diemen daer vonde in die stede,Ane maeghden ane nonnen mede / Diemen vonde in die stede,aan paapschap en aan non mede / die men daar vinden in die stede,aan maagd aan non mede / die men vinden in die stede,Brabantsche yeesten (B5),Van den derden Eduwaert,None,None,1.881467e-01
3369,Nu sijn die Vlaminghe met allen / An coninc Eduwaerde ghevallen,Nu siin die Vleminge mit allen / An coninc Eduwaert gevallen,nu zijn die Vlaming met al / aan koning NOU-P vallen,nu zijn die vleming met al / aan koning NOU-P vallen,Brabantsche yeesten (B5),Van den derden Eduwaert,None,None,1.891220e-01
3996,Doemen screef Ons Heren jaer / Dertien hondert ende veertach,Doe men Gods jaer screef meer no min / Derthien hondert ende veertach,toen men schrijven ons heer jaar / dertien honderd een veertig,toen men NOU-P jaar schrijven meer node min / dertien honderd een veertig,Brabantsche yeesten (B5),Van den derden Eduwaert,None,None,1.898250e-01
3256,Ende dat si waren met allen / Neder te voet ghevallen,Ende siin hulperen mit allen / Neder te voet gevallen,en dat zij zijn met al / neder te voet vallen,en zijn helper met al / neder te voet vallen,Brabantsche yeesten (B5),Van den derden Eduwaert,None,None,1.972871e-01
894,Dede den coninc grote ere / Alse betaemt al selken here,Ontfing hine mit groter eeren / Alse betaemt selken heren,doen de koning groot eer / als betamen al zulk heer,ontvangen hij ne met groot eer / als betamen zulk heer,Brabantsche yeesten (B5),Van den derden Eduwaert,None,None,2.023099e-01
3931,Ende nam al te hant sine vaert / Met sinen volke te Ludic waert,Ende Eduwaert nam sine vaert / Te sinen wive te Ghent waert,en nemen al te hand zijn vaart / met zijn volk te NOU-P waart,en NOU-P nemen zijn vaart / te zijn wijf te NOU-P waart,Brabantsche yeesten (B5),Van den derden Eduwaert,None,None,2.090036e-01
3335,Hilt hi hem daer over enen pas / Daer hi wel mede bewaert was,Maer sij lagen over eenen pas / Daer hij met wel bewaert was,houden hij hij daar over een pas / daar hij wel mede bewaren zijn,maar zij liggen over een pas / daar hij met wel bewaren zijn,Brabantsche yeesten (B5),Van den derden Eduwaert,None,None,2.119827e-01
3302,Helpen houden sine pale / Ieghen elc lant ende elken here,Ende elc soude andren wale / Helpen houden sine pale,helpen houden zijn paal / jegen elk land en elk heer,en elk zullen ander wel / helpen houden zijn paal,Brabantsche yeesten (B5),Van den derden Eduwaert,None,None,2.243253e-01
3300,Ende met zeghelen gheconfirmeert / Dat elc soude anderen wale,Ende mit zegulen te confirmeerne / Daer elc van hen soude wederstaen,en met zegel confirmeren / dat elk zullen ander wel,en met zegel te confirmeren / daar elk van zij zullen wederstaan,Brabantsche yeesten (B5),Van den derden Eduwaert,None,None,2.246648e-01
3454,Ane maeghden ende ane vrouwen / Ane paepscap ende ane nonnen mede,Ane vrouwen jonge ende oude / Ane maeghden ane nonnen mede,aan maagd en aan vrouw / aan paapschap en aan non mede,aan vrouw jong en oude / aan maagd aan non mede,Brabantsche yeesten (B5),Van den derden Eduwaert,None,None,2.296942e-01
3457,Ende consti dorloghe ghebreken / Dat mens hem ewelijc ere soude spreken,Ende consti doirloge gebreken / Men soude hem ewelijc eere spreken,en kunnen doorlog gebreken / dat men hij eeuwelijk eer zullen spreken,en kunnen gij de oorlog gebreken / men zullen hij eeuwelijk eer spreken,Brabantsche yeesten (B5),Van den derden Eduwaert,None,None,2.331096e-01
606,Dat die coninc ware viant / Des hertoghen van Brabant,Dan die hertoge van Brabant / Ende alse waere hij viant,dat die koning zijn vijand / de hertog van NOU-P,dan die hertog van NOU-P / en als zijn hij vijand,Brabantsche yeesten (B5),Van den derden Eduwaert,None,None,2.341522e-01
3473,Want hem ghebrac silver ende gout / Daer hi met ghelden soude sijn scout,Want hine hadde silver no gout / Daer hij met mochte siin scout,want hij gebreken zilver en goud / daar hij met gelden zullen zijn scout,want hij hij hebben zilver noch goud / daar hij met mogen zijn scout,Brabantsche yeesten (B5),Van den derden Eduwaert,None,None,2.344908e-01
3298,Met consent van elker stede / Ende dat vaste bechartereert,Met consente van elker stede / Die steden van Vlaenderen quamen,met consent van elk stede / en dat vast bechartereren,met consent van elk stede / die stad van NOU-P komen,Brabantsche yeesten (B5),Van den derden Eduwaert,None,None,2.354003e-01
2501,Metten sinen overtoghe / Met soe meneghen vromen man,Met menegen vromen man / Ende dat die coninc waere dan,met de zijn overtoog / met zo menig vroom man,met menig vroom man / en dat die koning zijn dan,Brabantsche yeesten (B5),Van den derden Eduwaert,None,None,2.439152e-01
2502,Met soe meneghen vromen man / Dat wonder was te scouwene an,Dat wonder was te scouwen an / Daer moeste sterven menich man,met zo menig vroom man / dat wonder zijn te schouwen aan,dat wonder zijn te schouwen aan / daar moeten sterven menig man,Brabantsche yeesten (B5),Van den derden Eduwaert,None,None,2.493427e-01
3084,Nu alse Eduwaert heeft vernomen / Dat die keiser niet en sal comen,Doe die coninc dat vernam / Dat die keyser niet en quam,nu als NOU-P hebben vernemen / dat die keizer niet ne zullen komen,toen die koning dat vernemen / dat die keizer niet ne komen,Brabantsche yeesten (B5),Van den derden Eduwaert,None,None,2.499239e-01
3370,An coninc Eduwaerde ghevallen / Ende setten tsamen hare vaert,An coninc Eduwaert gevallen / Ende gereedden hoere vaert,aan koning NOU-P vallen / en zetten samen haar vaart,aan koning NOU-P vallen / en gereden haar vaart,Brabantsche yeesten (B5),Van den derden Eduwaert,None,None,2.614158e-01
3070,Alse vicaris des rijcs / Wie sach ye des ghelijcs,Alse vicarijs des heylichs rijcx / Waer hoerde noyt man des gelijcx,als vicaris de rijk / wie zien ik de gelijke,als vicaris de heilig rijk / waar hoeren nooit man de gelijke,Brabantsche yeesten (B5),Van den derden Eduwaert,None,None,2.619460e-01
784,Was te vernoye harde sere / Van Tonenborch die grote here,Saert sprac hij Segt uwen heere / Dat mi vernoit harde seere,zijn te vernooien hard zeer / van NOU-P die groot heer,saart spreken hij zeggen uw heer / dat ik vernooien hard zeer,Brabantsche yeesten (B5),Van den derden Eduwaert,None,None,2.635644e-01
3983,Den hertoghe van Brabant / Diese ontfinc al te hant,Es si gekeert al te hant / Toten hertoge van Brabant,de hertog van NOU-P / die zij ontvangen al te hand,zijn zij keren al te hand / tot de hertog van NOU-P,Brabantsche yeesten (B5),Van den derden Eduwaert,None,None,2.650013e-01
3222,Dat si van node haer vaert / Nemen moesten thuus waert,Oft sij souden nemen haer vaert / So si ierst mochten thuus waert,dat zij van nood haar vaart / nemen moeten thuis waart,of zij zullen nemen haar vaart / zo zij eerst mogen thuis waart,Brabantsche yeesten (B5),Van den derden Eduwaert,None,None,2.669918e-01

In [22]:
nearest_df = nearest_verses('Brabantsche yeesten (B5)', 'Korte kroniek van Brabant (lange versie)',
                            base_df=df, vectorizer=vec, prop_filt=2)
nearest_df = nearest_df.sort_values(by='distance')
nearest_df.to_excel('../figures/parallel_verses/yeesten_5-korte_kroniek.xlsx')
nearest_df.head(50)

,tokens1,tokens2,lemmas1,lemmas2,title1,title2,intertext1,intertext2,distance
3008,Ten Minderbroedren leit si begraven / Te Brusele met groter haven,Keiser Kaerle was begraven / Tot Aken met groter haven,ten minderbroederen liggen zij begraven / te NOU-P met groot haven,keizer NOU-P zijn begraven / tot NOU-P met groot haven,Brabantsche yeesten (B5),Korte kroniek van Brabant (lange versie),None,None,0.242643
560,Hertoghe Jan sijn ouder vader / Was doot eer sconincs vader,Die hi ende siin vader Puppiin / Ende Kaerle Marteel die oude vader siin,hertog NOU-P zijn oud vader / zijn dood eer de koning vader,die hij en zijn vader pupiin / en NOU-P NOU-P die oud vader zijn,Brabantsche yeesten (B5),Korte kroniek van Brabant (lange versie),None,None,0.254282
2290,Alsoe hart in desen doene / Ende met hem die Brabantsoene,Ende die Oosterse Brabansoene / Quamen tot desen hoghen doene,alzo hard in deze doen / en met hij die Brabantsoen,en die oosters Brabantsoen / komen tot deze hoog doen,Brabantsche yeesten (B5),Korte kroniek van Brabant (lange versie),None,None,0.265808
677,Ontghelden dat sijn ouder vader / Ende sijn vader hadde ghedaen,Die hi ende siin vader Puppiin / Ende Kaerle Marteel die oude vader siin,ontgelden dat zijn oud vader / en zijn vader hebben doen,die hij en zijn vader pupiin / en NOU-P NOU-P die oud vader zijn,Brabantsche yeesten (B5),Korte kroniek van Brabant (lange versie),None,None,0.280502
3996,Doemen screef Ons Heren jaer / Dertien hondert ende veertach,Doemen screef die iare ons Heren / Dertien hondert ende xij mede,toen men schrijven ons heer jaar / dertien honderd een veertig,toen men schrijven die jaar ons heer / dertien honderd een tweeëntwintigste mede,Brabantsche yeesten (B5),Korte kroniek van Brabant (lange versie),None,None,0.282006
622,Dede hien nemen metter vaert / Ende voeren te Ghenapie waert,Ende Montaguut an siinre vaert / Daer na voer hi tot Riemen waert,doen hij hij nemen met de vaart / en voeren te NOU-P waart,en NOU-P aan zijn vaart / daar na voeren hij tot NOU-P waart,Brabantsche yeesten (B5),Korte kroniek van Brabant (lange versie),None,None,0.289998
1662,Ieghen den hertoghe van Brabant / Trocken si oec al te hant,Jegen die hertogen van Brabant / Die Oosteriken hadden in hant,jegen de hertog van NOU-P / trekken zij ook al te hand,jegen die hertog van NOU-P / die oosterrijk hebben in hand,Brabantsche yeesten (B5),Korte kroniek van Brabant (lange versie),None,None,0.319657
2494,Ende lieten riden op die waerde / Ende dat hi keerde metter vaerde,Met eren ende met groter waerde / Ende keerde weder siinre vaerde,en laten rijden op die waarde / en dat hij keren met de vaart,met eer en met groot waarde / en keren woeden zijn vaart,Brabantsche yeesten (B5),Korte kroniek van Brabant (lange versie),None,None,0.323726
466,Maer den grave daden si scade groot / Want sijn liede bleven daer doot,Ende dede Hughen scade groot / Dat veel der siinre bleven doot,maar de graf doen zij schade groot / want zijn lieden blijven daar dood,en doen NOU-P schade groot / dat veel de zinder blijven dood,Brabantsche yeesten (B5),Korte kroniek van Brabant (lange versie),None,None,0.327171
165,Dus soe wies daer een ghevecht / Tusschen Tricht ende dien here,Tusschen Ludike ende Maestrecht / Hi verwan in een ghevecht,dus zo wassen daar een gevecht / tussen NOU-P en dat heer,tussen NOU-P en NOU-P / hij verwinnen in een gevecht,Brabantsche yeesten (B5),Korte kroniek van Brabant (lange versie),None,None,0.327281
618,Hadde hi Reinoute ende sijn lant / Wel ghehadt in sijn hant,Al hadde Kaerle in siin hande / Kuenincrike ende grote lande,hebben hij NOU-P en zijn land / wel hebben in zijn hand,al hebben NOU-P in zijn hand / koninkrijk en groot land,Brabantsche yeesten (B5),Korte kroniek van Brabant (lange versie),None,None,0.329215
3333,Onder Vlaminghe ende Brabantsoene / Ende Heinewiere vroem ende coene,Kaerle dees hertoghe coene / Nam Lotrikers ende Brabansoene,onder Vlaming en Brabantsoen / en henewier vroom en koen,NOU-P deze hertog koen / nemen lotrijker en Brabantsoen,Brabantsche yeesten (B5),Korte kroniek van Brabant (lange versie),None,None,0.337018
3772,Die by den kinderen waren daer / Ende binnen corten tiden daer naest,Karollus discessit in isto / Ende daer na in corten tiden,die bij de kind zijn daar / en binnen kort tijd daar na,karollus discessit in isto / en daar na in kort tijd,Brabantsche yeesten (B5),Korte kroniek van Brabant (lange versie),None,None,0.339399
3545,Van den Vriesen dat was jammer groot / Ende met hem bleven doot,Hi bleef in Egipten doot / Van enen evel dats jammer groot,van de Fries dat zijn jammer groot / en met hij blijven dood,hij blijven in NOU-P dood / van een euvel dat zijn jammer groot,Brabantsche yeesten (B5),Korte kroniek van Brabant (lange versie),None,None,0.344586
2162,Bacheleren ende knapen mede / Al te Brusele in die stede,Kaerle die wan Spangen mede / Te Compostelle inder stede,bachelaar en knaap mede / al te NOU-P in die stede,NOU-P die winnen NOU-P mede / te NOU-P in de stede,Brabantsche yeesten (B5),Korte kroniek van Brabant (lange versie),None,None,0.345064
2014,Ende brachtene te Brusele in die stede / Daer hi hem grote ere dede,Hi wan Ludicke die stede / Daer hi grote scade in dede,en brengen hij te NOU-P in die stede / daar hij hij groot eer doen,hij winnen NOU-P die stede / daar hij groot schade in doen,Brabantsche yeesten (B5),Korte kroniek van Brabant (lange versie),None,None,0.345800
310,Te Tricht in der stede / Want sine liede waren mede,Kaerle die wan Spangen mede / Te Compostelle inder stede,te NOU-P in de stede / want zijn lieden zijn mede,NOU-P die winnen NOU-P mede / te NOU-P in de stede,Brabantsche yeesten (B5),Korte kroniek van Brabant (lange versie),None,None,0.347188
3432,Ende oec swegher die ghelike / Edewaerts van Enghelant,Dat grote Kaerle zonder geliic / Keiser ende kueninc van Vrancriic,en ook zweger die gelijke / edewaarts van NOU-P,dat groot NOU-P zonder gelijke / keizer en koning van NOU-P,Brabantsche yeesten (B5),Korte kroniek van Brabant (lange versie),None,None,0.350054
3750,Tusschen den hertoghe van Brabant / Ende sinen here sinen vader,Tuterste van siins vader rike / Dus lach tusschen Lodewiicke,tussen de hertog van NOU-P / en zijn heer zijn vader,tuiterste van zijn vader NOU-P / dus lachen tussen NOU-P,Brabantsche yeesten (B5),Korte kroniek van Brabant (lange versie),None,None,0.350354
2822,Bi den heren van Vrancrike / Daer die hertoghe sekerlike,Wilde siin een hertooch van Lotrike / Lambrecht dochte zekerlike,bij de heer van NOU-P / daar die hertog zekerlijk,willen zien een hertog van NOU-P / NOU-P deugen zekerlijk,Brabantsche yeesten (B5),Korte kroniek van Brabant (lange versie),None,None,0.353372
559,Ieghen recht ende redene was / Hertoghe Jan sijn ouder vader,Die hi ende siin vader Puppiin / Ende Kaerle Marteel die oude vader siin,jegen recht en rede zijn / hertog NOU-P zijn oud vader,die hij en zijn vader pupiin / en NOU-P NOU-P die oud vader zijn,Brabantsche yeesten (B5),Korte kroniek van Brabant (lange versie),None,None,0.355498
3983,Den hertoghe van Brabant / Diese ontfinc al te hant,Jegen die hertogen van Brabant / Die Oosteriken hadden in hant,de hertog van NOU-P / die zij ontvangen al te hand,jegen die hertog van NOU-P / die oosterrijk hebben in hand,Brabantsche yeesten (B5),Korte kroniek van Brabant (lange versie),None,None,0.355833
3307,Al te Ghent in die stede / Sijn wijf ende kindere mede,Kaerlen ende siin wiif mede / Heeft hi gevaen daer ter stede,al te NOU-P in die stede / zijn wijf en kind mede,NOU-P en zijn wijf mede / hebben hij vangen daar ter stede,Brabantsche yeesten (B5),Korte kroniek van Brabant (lange versie),None,None,0.364470
3730,Hoe hi huwelic heeft ghedaen / Aen tshertoghen dochter van Brabant,Dede hi huwelic scoon ende groot / Hi nam sint Elsbenen dochter,hoe hij huwelijk hebben doen / aan de hertog dochter van NOU-P,doen hij huwelijk schoon en groot / hij nemen NOU-P NOU-P dochter,Brabantsche yeesten (B5),Korte kroniek van Brabant (lange versie),None,None,0.367378
3074,Diet al wille weten vore ende na / Ic rade hem dat hi ten boeke ga,Dat hi dees yeesten leest voir of na / Ic raed hem dat hi ten boecke gha,die het al willen weten voor en na / ik raden hij dat hij ten beuk gaan,dat hij deze geeste lezen voor of na / ik raden hij dat hij ten beuk geven,Brabantsche yeesten (B5),Korte kroniek van Brabant (lange versie),None,None,0.367792
785,Van Tonenborch die grote here / Die here van der Sleiden mede,Ende van Gelre die graefnede / Ende die van Avaerne mede,van NOU-P die groot heer / die heer van de sleed mede,en van NOU-P die graafnede / en die van NOU-P mede,Brabantsche yeesten (B5),Korte kroniek van Brabant (lange versie),None,None,0.368775
1736,Des hertoghen te waren / Sonder die grave van Baren,Na hertooch Godevaert van Bulyoen / Die hertooch was van Lotrike,de hertog te zijn / zonder die graf van NOU-P,na hertog NOU-P van NOU-P / die hertog zijn van NOU-P,Brabantsche yeesten (B5),Korte kroniek van Brabant (lange versie),None,None,0.369908
2249,Van Manderscheit die here / Ende die here van Fancersine,Kaerle die grote wan Lodewiicke / Heer van Rome ende van Vrancrike,van manderscheid die heer / en die heer van NOU-P,NOU-P die groot winnen NOU-P / heer van NOU-P en van NOU-P,Brabantsche yeesten (B5),Korte kroniek van Brabant (lange versie),None,None,0.375095
3062,Tote Covelense in de stede / Ende wat hem die keiser dede,Dien die keiser Heinric dede / Martelen tot Riemen inder stede,tot kovelense in de stede / en wat hij die keizer doen,dat die keizer NOU-P doen / martelen tot NOU-P in de stede,Brabantsche yeesten (B5),Korte kroniek van Brabant (lange versie),None,None,0.375199
3387,Die hertoghe met sijnre ghewelt / Viel in dees side der Scelt,Die grave was met ghewelt / Bi Vlaendren neffens der Scelt,die hertog met zijn geweld / vallen in deze zijde de scheld,die graf zijn met geweld / bij NOU-P nevens de scheld,Brabantsche yeesten (B5),Korte kroniek van Brabant (lange versie),None,None,0.375224
2168,Die te Vilvoerden doen lach / Ende sonden op enen dach,So en was ridder optien dach / Dees Boudiin die lach,die te NOU-P toen lachen / en zenden op een dag,zo ne zijn ridder op die dag / deze NOU-P die lachen,Brabantsche yeesten (B5),Korte kroniek van Brabant (lange versie),None,None,0.376041
1702,Des hertoghen sone van Brabant / Diet lant soude comen in hant,Jegen die hertogen van Brabant / Die Oosteriken hadden in hant,de hertog zoon van NOU-P / die het land zullen komen in hand,jegen die hertog van NOU-P / die oosterrijk hebben in hand,Brabantsche yeesten (B5),Korte kroniek van Brabant (lange versie),None,None,0.378843
3685,Des graven moeder ende vader / Woenden in Vrancrike beide gader,Dit was sinte Geertruden vader / Ende vrou Begghen beide gader,de graf moeder en vader / wonen in NOU-P beide gader,dit zijn NOU-P NOU-P vader / en vrouw NOU-P beide gader,Brabantsche yeesten (B5),Korte kroniek van Brabant (lange versie),None,None,0.383150
2790,Ende met groter rijcheit besat / Sijn lant waren si hem ghehat,In dat lant van Lombaerdien / Ende heeft Paueyen beseten,en met groot rijkheid bezitten / zijn land zijn zij hij hebben,in dat land van NOU-P / en hebben NOU-P bezitten,Brabantsche yeesten (B5),Korte kroniek van Brabant (lange versie),None,None,0.385572
1942,Ende keerde weder achter waert / In Denremonde metter vaert,Ende keerde weder siinre vaerde / Met sinen gheselen in Vrancrike,en keren woeden achter waart / in NOU-P met de vaart,en keren woeden zijn vaart / met zijn gesel in NOU-P,Brabantsche yeesten (B5),Korte kroniek van Brabant (lange versie),None,None,0.388020
2804,Ende brachtse vore hem al te hant / Tote Brusele in sijn lant,Kaerle voer vechten in den lande / Ende hadde alle die stride in hande,en brengen zij voor hij al te hand / tot NOU-P in zijn land,NOU-P voor vechten in de land / en hebben al die strijd in hand,Brabantsche yeesten (B5),Korte kroniek van Brabant (lange versie),None,None,0.389994
4164,Screef dertien hondert ende L jare / Int jaer van gracien bekent,Doemen screef ziit seker des / Dertien hondert ende xij iaer,schrijven dertien honderd een vijftig jaar / in het jaar van gratie bekend,toen men schrijven zijn het zeker de / dertien honderd een twaalf jaar,Brabantsche yeesten (B5),Korte kroniek van Brabant (lange versie),None,None,0.391527
3803,Toten paus tAvengoen / Maer die paus en wouts niet doen,Die paeus Steven die na Zacharien / Paeus te Rome wart gecoren,tot de paus NOU-P / maar die paus ne willen dat niet doen,die paus NOU-P die na NOU-P / paus te NOU-P worden kiezen,Brabantsche yeesten (B5),Korte kroniek van Brabant (lange versie),None,None,0.391690
2334,Nochtan in allen manieren / Soe was hi hem goedertieren,Doe bleef daer Lodewiic die goedertieren / Die na siins vader manieren,nochtan in al manier / zo zijn hij hij goedertieren,toen blijven daar NOU-P die goedertieren / die na zijn vader manier,Brabantsche yeesten (B5),Korte kroniek van Brabant (lange versie),None,None,0.392691
772,Met groter cost met groter pinen / Om te verhoedene die sine,Tot Sissoen ende quam ten sinen / Met arbeden ende met groter pinen,met groot kost met groot pijn / om te verhoeden die zijne,tot NOU-P en komen ten zijne / met arbede en met groot pijn,Brabantsche yeesten (B5),Korte kroniek van Brabant (lange versie),None,None,0.393552
3403,Daer hi bleef ligghende dan / Moghentlike met meneghen man,Godevaert die mogentlike / Heer bleef van Lotrike,daar hij blijven liggen dan / mogenlijk met menig man,NOU-P die mogenlijk / heer blijven van NOU-P,Brabantsche yeesten (B5),Korte kroniek van Brabant (lange versie),None,None,0.394501
2250,Ende die here van Fancersine / Die daer leden grote pine,Met arbeden ende met groter pinen / Die grave van Vermendois Himbrecht,en die heer van NOU-P / die daar lijden groot pijn,met arbede en met groot pijn / die graf van NOU-P NOU-P,Brabantsche yeesten (B5),Korte kroniek van Brabant (lange versie),None,None,0.395960
3288,Spreken consti harde wel / Ende wart van groten ghewelde,Die si hadden in hoire gewelt / Kaerle die conste wale,spreken kunnen gij hard wel / en worden van groot geweld,die zij hebben in haar geweld / NOU-P die kunnen wel,Brabantsche yeesten (B5),Korte kroniek van Brabant (lange versie),None,None,0.396937
3973,Ende in dat vlien ende dat jaghen / Wert des volcs daer verslaghen,Angiis wart daer na verslegen / Van den genen die hem waer iegen,en in dat vlien en dat jagen / worden de volk daar verslaan,NOU-P worden daar na verslaan / van de geen die hij zijn jagen,Brabantsche yeesten (B5),Korte kroniek van Brabant (lange versie),None,None,0.399457
3236,Ende dat Eduwaert met sijnre ghewelt / Noch daer laghe op dat velt,Ende hine vluchtich maecte mit gewelt / Ende siin heer opt velt,en dat NOU-P met zijn geweld / nog daar liggen op dat veld,en hij hij vluchtig maken met geweld / en zijn heer op het veld,Brabantsche yeesten (B5),Korte kroniek van Brabant (lange versie),None,None,0.399565
3690,Dat sijn vader ende moeder doot ware / Quam hi saen in Vlaendrenlant,Want kueninc Lottaris was siin broeder / Siins vader kint ende siinre moeder,dat zijn vader en moeder dood zijn / komen hij zaan in NOU-P,want NOU-P NOU-P zijn zijn broeder / zijn vader kind en zijn moeder,Brabantsche yeesten (B5),Korte kroniek van Brabant (lange versie),None,None,0.399952
2298,In haghen in grachten in scuren / In scaepscoyen in ovenburen,Tactus febre loco / Karollus discessit in isto,in haag in gracht in schuur / in schaapschuid in NOU-P,tactus febre loco / karollus discessit in isto,Brabantsche yeesten (B5),Korte kroniek van Brabant (lange versie),None,None,0.403097
3010,Omtrent drie jare hier naer / Doe men screef ons Heren jaer,Die hi zelve dede maken / Doemen screef ons Heren jaer,omtrent drie jaar hier naar / toen men schrijven ons heer jaar,die hij zelf doen maken / toen men schrijven ons heer jaar,Brabantsche yeesten (B5),Korte kroniek van Brabant (lange versie),None,None,0.403559
2452,Van daer nam sine vaert / Al recht ter Masen waert,Ende Montaguut an siinre vaert / Daer na voer hi tot Riemen waert,van daar nemen zijn vaart / al recht ter NOU-P waart,en NOU-P aan zijn vaart / daar na voeren hij tot NOU-P waart,Brabantsche yeesten (B5),Korte kroniek van Brabant (lange versie),None,None,0.403924
2792,Ende wouden met ghesaemder hant / Hem af winnen alsoe sijn lant,Die van Lymboirch wan dat lant / Mit vromicheden mit siinre hant,en willen met gezamend hand / hij afvangen winnen alzo zijn land,die van NOU-P winnen dat land / met vromigheid met zijn hand,Brabantsche yeesten (B5),Korte kroniek van Brabant (lange versie),None,None,0.404563

In [23]:
nearest_df = nearest_verses('Sidrac', 'Melibeus',
                            base_df=df, vectorizer=vec, prop_filt=2)
nearest_df = nearest_df.sort_values(by='distance')
nearest_df.to_excel('../figures/parallel_verses/sidrac-melibeus.xlsx')
nearest_df.head(50)

,tokens1,tokens2,lemmas1,lemmas2,title1,title2,intertext1,intertext2,distance
221,Amen segt gemeenlike / Amen,Nu segt Amen ghemeynlike / AMEN,amen zeggen gemeenlijk / amen,nu zeggen amen gemeenlijk / amen,Sidrac,Melibeus,None,None,0.017344
107,Die beter es menichfout / Danne ghesteente zelver of gout,Dat wijf es beter menechfout / Dan ghesteynte silver of gout,die goed zijn menigvout / dan gesteente zelf of goud,dat wijf zijn goed menigvout / dan gesteente zilver of goud,Sidrac,Melibeus,None,None,0.157570
220,Ende na dit leven hemelrike / Amen segt gemeenlike,Gheloeft si God van hemelrike / Nu segt Amen ghemeynlike,en na dit leven hemelrijk / amen zeggen gemeenlijk,geloven zij NOU-P van hemelrijk / nu zeggen amen gemeenlijk,Sidrac,Melibeus,None,None,0.224515
17,Ende troest van allen goeden rade / An leren mach vroech ende spade,Daer om in ghedeelden rade / Salmen volghen vroech ende spade,en troosten van al goed raad / aan leren mogen vroeg en spade,daar om in gedeeld raad / zullen men volgen vroeg en spade,Sidrac,Melibeus,None,None,0.366514
35,Want die tijt es ons ghegeuen / Omme dat wy in dit leven,Al dat ons in dit leven / Van boven wert ghegheven,want die tijd zijn ons geven / om dat wij in dit leven,al dat ons in dit leven / van boven worden geven,Sidrac,Melibeus,None,None,0.385246
171,Ende die selve Sone es God / Seker hy es herde sot,Nochtan en sidi sot niet / Want die hem selven sot siet,en die zelf zoon zijn NOU-P / zeker hij zijn hard zot,nochtan ne zijn gij zot niet / want die hij zelf zot zien,Sidrac,Melibeus,None,None,0.419581
108,Danne ghesteente zelver of gout / Want vele beter es wijshede,Dat wijf es beter menechfout / Dan ghesteynte silver of gout,dan gesteente zelf of goud / want veel goed zijn wijsheid,dat wijf zijn goed menigvout / dan gesteente zilver of goud,Sidrac,Melibeus,None,None,0.434216
219,Ende sine helige minne mede / Ende na dit leven hemelrike,Ende God na dit corte leven / Sal hem hemelrike gheven,en zijn heilig minne mede / en na dit leven hemelrijk,en NOU-P na dit kort leven / zullen hij hemelrijk geven,Sidrac,Melibeus,None,None,0.436263
158,Die my int herte niet en ginc / Hebbic al gelaten uut,En hebbic niet in mi / Al woudic al laten varen,die ik in het hart niet ne gaan / hebben ik al laten uiten,ne hebben ik niet in ik / al willen ik al laten varen,Sidrac,Melibeus,None,None,0.467422
209,Al in die stat tAntwerpen / Wast dat ic dit translateerde,Ghetracteert uten latine / Al tAntwerpen in die poert,al in die stad te antwerpen / wassen dat ik dit translateren,trakteren uit dat NOU-P / al te antwerpen in die port,Sidrac,Melibeus,None,None,0.476276
27,Aldus eest ende anders niet / Die de dinc te rechte besiet,Es gheorloeft ende anders niet / Onder die droeve diet wel besiet,aldus zijn het en anders niet / die de ding te rechte bezien,zijn geoorloven en anders niet / onder die droef die het wel bezien,Sidrac,Melibeus,None,None,0.477950
79,Die anders doen sy doen quaet / Hoets hem elc dats mijn raet,Want sonder voersieneghen raet / Doetmen dicke dat es quaet,die anders doen zij doen kwaad / hoe zij hij elk dat zijn mijn raad,want zonder voorzienigen raad / doen men dik dat zijn kwaad,Sidrac,Melibeus,None,None,0.484095
48,Daer ic in bescreven vant / Vele duechden ende wijsheden,Die wijsheyt heeft in den sin / Heeft alle doghet daer in,daar ik in beschrijven vinden / veel deugd en wijsheid,die wijsheid hebben in de zin / hebben al deugd daar in,Sidrac,Melibeus,None,None,0.491289
110,Danne enighe erdsche rijchede / Want dese bouc hevet in,Sonder ertsche rijcheyt / Ende al dit ertsche beleyt,dan enig aards rijkheid / want deze boek hebben in,zonder aards rijkheid / en al dit aards beleid,Sidrac,Melibeus,None,None,0.492503
93,Beide ter zielen ende ten live / Die ic hier na bescrive,Beyde an ziele ende aen live / Want al dat ic hier scrive,beide ter ziel en ten lijf / die ik hier na beschrijven,beide aan ziel en aan lijf / want al dat ik hier schrijven,Sidrac,Melibeus,None,None,0.508413
127,Eenen onghelovighen coninc / Hiet Boctus die hem leerde dese dinc,Salomon leert ons die coninc / Dat vrient gaet boven alle dinc,een ongelovig koning / heten NOU-P die hij leren deze ding,NOU-P leren ons die koning / dat vriend gaan boven al ding,Sidrac,Melibeus,None,None,0.513215
18,An leren mach vroech ende spade / In weet wat sire inne menen,Dat ons hadde moghen vallen / Vrouwe nu willen wi vroech ende spade,aan leren mogen vroeg en spade / u weten wat zijn ik ne menen,dat ons hebben mogen vallen / vrouwe nu willen wij vroeg en spade,Sidrac,Melibeus,None,None,0.513868
113,Ende oec zal hi doen verstaen / Hoet metten achtersten zal gaen,Hoeden soude ende niet voert gaen / Ende doet mi oec mede verstaen,en ook zullen hij doen verstaan / hoe het met de achterste zullen gaan,hoeden zullen en niet voeren gaan / en doen ik ook mede verstaan,Sidrac,Melibeus,None,None,0.514641
184,Daer by eest openbare / Dat haer niet en es ontseit,Ende seyden openbaer / Dat haere raet niet goet en waer,daar bij zijn het openbaar / dat zij niet ne zijn ontzeggen,en zeggen openbaar / dat haar raad niet goed ne zijn,Sidrac,Melibeus,None,None,0.516264
181,Die een God sijn metten Vader / Dus heeft sy algader,Vanden ewighen Vader / Dat es volmaect algader,die een god zijn met de vader / dus hebben zij algader,van de eeuwig vader / dat zijn volmaakt algader,Sidrac,Melibeus,None,None,0.516321
34,Daer na weder verhalen en can / Want die tijt es ons ghegeuen,Tgoet machmen verhalen nochtan / Maer den tijt en verhaelt nieman,daar na weder verhalen ne kunnen / want die tijd zijn ons geven,het goed mogen men verhalen nochtan / maar de tijd ne verhalen niemand,Sidrac,Melibeus,None,None,0.520096
139,Dat ic dit werc bringhe toe / Ende mijn leven betren zoe,Ic salt u wel bringhen toe / Melibeus sprac doe,dat ik dit werk brengen toezenden / en mijn leven beteren zo,ik zullen het u wel brengen toezenden / NOU-P spreken toen,Sidrac,Melibeus,None,None,0.520759
218,Dat hi ons geve sine vrede / Ende sine helige minne mede,Waect ende heeft ghenen vrede / Ende waer dat vrede niet en es,dat hij ons geven zijn vrede / en zijn heilig minne mede,waken en hebben gene vrede / en waar dat vrede niet ne zijn,Sidrac,Melibeus,None,None,0.525595
109,Want vele beter es wijshede / Danne enighe erdsche rijchede,Sonder ertsche rijcheyt / Ende al dit ertsche beleyt,want veel goed zijn wijsheid / dan enig aards rijkheid,zonder aards rijkheid / en al dit aards beleid,Sidrac,Melibeus,None,None,0.525916
152,Ende vanden stenen die virtuit / Ende oec eenderhande sotterie,Maer ghi sult sueken twaren / Den sin ende sine vertuut,en van de steen die virtuut / en ook enerhande zotterij,maar gij zullen zoeken dat waar / de zin en zijn virtuut,Sidrac,Melibeus,None,None,0.528229
59,Omme dat ic van dier edelre leren / Een woert niet woude anders keren,Eest dan dat ghi u leren / Ter clergyen wert wilt keren,om dat ik van die edel leer / een woord niet willen anders keren,zijn het dan dat gij u leer / ter clergie waart willen keren,Sidrac,Melibeus,None,None,0.533918
2,Die hem ane die boeke houden / Daer sy clene profijt inne leren,Int boeke daer hi leert minnen / Een cleyne ader ende niet groet,die hij aan die beuk houden / daar zij klein profijt in leren,in het beuk daar hij leren minnen / een klein ader en niet groot,Sidrac,Melibeus,None,None,0.537018
208,Verre van mi wille werpen / Al in die stat tAntwerpen,Sonder mi en moghedi doen niet / Al t Andwerpen daer ic wone,ver van ik willen werpen / al in die stad te antwerpen,zonder ik ne mogen gij doen niet / al het antwerpen daar ik wonen,Sidrac,Melibeus,None,None,0.539737
138,Ende te levene zo langhe stonde / Dat ic dit werc bringhe toe,Ic salt u wel bringhen toe / Melibeus sprac doe,en te leven zo lang stonde / dat ik dit werk brengen toezenden,ik zullen het u wel brengen toezenden / NOU-P spreken toen,Sidrac,Melibeus,None,None,0.539783
29,Die den tijt onledich maken / Met onoerboerliken saken,Want si can voer alle saken / Den mensche wel met Gode maken,die de tijd onledig maken / met onoorbaarlijk zaak,want zij kunnen voor al zaak / de mens wel met NOU-P maken,Sidrac,Melibeus,None,None,0.540082
166,Wanen soe quam u dat / Dat God ende ghi allene,Dat ghi u so hilt ghepayt / Met enen rade allene,waan zo komen u dat / dat NOU-P en gij alleen,dat gij u zo houden paaien / met een raad alleen,Sidrac,Melibeus,None,None,0.543995
176,Dat hy sinen heylegen Geest sinde / In hore omme die dinc,Dat maect in hem een leven / Dan wercter die heylighe Gheest inne,dat hij zijn heilig geest einden / in haar om die ding,dat maken in hij een leven / dan werkt die heilig geest in,Sidrac,Melibeus,None,None,0.548722
15,Ende leggen die boeke onder voet / Daer men wijsheit doget ende goet,Ende hebben sulke boeke / Daer hi wijsheyt in besoeke,en leggen die beuk onder voet / daar men wijsheid doen en goed,en hebben zulk beuk / daar hij wijsheid in bezoeken,Sidrac,Melibeus,None,None,0.551823
98,Was philosophe ende astronomijn / Die God alsoe hadde vercoren,Hoe hemel ende erde sijn ghedaen / Wijsheyt vanghet astronomien,zijn filosoof en astronomijn / die NOU-P alzo hebben verkiezen,hoe hemel en aarde zijn doen / wijsheid vangen astronomijn,Sidrac,Melibeus,None,None,0.552252
191,Epiloog / Ghelooft zi God van hemelrike,Te bat varen aen ziele ende lijf / Gheloeft si God van hemelrike,epiloog / loven zij NOU-P van hemelrijk,te bet varen aan ziel en lijf / geloven zij NOU-P van hemelrijk,Sidrac,Melibeus,None,None,0.553930
151,Vanden cruden latic uut / Ende vanden stenen die virtuit,Maer ghi sult sueken twaren / Den sin ende sine vertuut,van de kruid laten ik uit / en van de steen die virtuut,maar gij zullen zoeken dat waar / de zin en zijn virtuut,Sidrac,Melibeus,None,None,0.554762
92,Want die leringe die es goet / Beide ter zielen ende ten live,Beyde an ziele ende aen live / Want al dat ic hier scrive,want die lering die zijn goed / beide ter ziel en ten lijf,beide aan ziel en aan lijf / want al dat ik hier schrijven,Sidrac,Melibeus,None,None,0.555343
101,Dat in de werelt soude gevallen / Ende hoe sy inden soude met allen,Hoe die dinc was ghevallen / Ende bat vriendelike hen allen,dat in de wereld zullen vallen / en hoe zij innen zullen met al,hoe die ding zijn vallen / en batten vriendelijk zij al,Sidrac,Melibeus,None,None,0.555839
161,Maria vol van genaden / Ende staet my in staden,Om dat si hem in daden / Ende in rade soude staen in staden,NOU-P vol van genade / en staan ik in stade,om dat zij hij in daad / en in raad zullen staan in stade,Sidrac,Melibeus,None,None,0.558011
33,Die nemmermeer no wijf no man / Daer na weder verhalen en can,Die nemen en can noch gheven / Noch noyt en hadde leven,die nimmermeer noch wijf noch man / daar na weder verhalen ne kunnen,die nemen ne kunnen noch geven / noch nooit ne hebben leven,Sidrac,Melibeus,None,None,0.560649
175,Die de Vader alsoe minde / Dat hy sinen heylegen Geest sinde,Die hi dien Chorienten sinde / Elc late hem ghenoeghen des,die de vader alzo minnen / dat hij zijn heilig geest einden,die hij dat choriënt einden / elk laten hij genoegen de,Sidrac,Melibeus,None,None,0.562183
13,Daer anders niet inne en leit / Dan der werelt ydelheit,Ende so verstijft in u rijcheyt / Dat al u dinc es ijdelheyt,daar anders niet in ne liggen / dan de wereld ijdelheid,en zo verstijven in u rijkheid / dat al u ding zijn ijdelheid,Sidrac,Melibeus,None,None,0.563074
131,Dit was naer Noe VIIIc iaer / Ende XLVII daer naer,Prudentia sprac daer naer / Die warenesse daer men met,dit zijn naar NOU-P achttiende jaar / en zevenenveertig daar naar,NOU-P spreken daar naar / die waarnis daar men met,Sidrac,Melibeus,None,None,0.564515
63,Want rime alsoe wijt vinden / Doet dicke die materie winden,Hi sprac Die scalke rade vinden / Dat si op hem selven winden,want rijm alzo wij het vinden / doen dik die materie winden,hij spreken die schalk raad vinden / dat zij op hij zelf winden,Sidrac,Melibeus,None,None,0.565056
55,Dat ic dit boec woude maken / Uten Walsche in Dietsche spraken,Salomon seghet Soete spraken / Connen vele vriende maken,dat ik dit boek willen maken / uit dat Waals in Diets spraak,NOU-P zeggen zoet spraak / kunnen veel vriend maken,Sidrac,Melibeus,None,None,0.565633
30,Met onoerboerliken saken / My dunct dat sy zere riesen,Nu hebdi uwen raet bedreven / Met jonghen sotten riesen,met onoorbaarlijk zaak / ik dunken dat zij zeer riezen,nu hebben gij uw raad bedrijven / met jong zot riezen,Sidrac,Melibeus,None,None,0.567285
16,Daer men wijsheit doget ende goet / Ende troest van allen goeden rade,Dat dien raet niet en waer goet / Want des volx menechfuldechede,daar men wijsheid doen en goed / en troosten van al goed raad,dat dat raad niet ne zijn goed / want de volk menigvoudigheid,Sidrac,Melibeus,None,None,0.568708
199,Dan omme gemene zalichede / Al der goonre dieze lezen,Sonder sake voer waer gheseyt / Maer al om uwe salicheyt,dan om gemeen zaligheid / al de gonder die zij lezen,zonder sake voor waar zeggen / maar al om uw zaligheid,Sidrac,Melibeus,None,None,0.568861
217,Daer hi sinen omoet in togede / Dat hi ons geve sine vrede,Daer bi willic uwen oetmoet / Aenscouwen oetmoet es so goet,daar hij zijn ootmoed in togen / dat hij ons geven zijn vrede,daar bij willen ik uw ootmoed / aanschouwen ootmoed zijn zo goed,Sidrac,Melibeus,None,None,0.571509
97,Na enen clerc wijs ende fijn / Was philosophe ende astronomijn,Philosophen ende medicinen / Andere clercken ende Surginen,na een klerk wijs en fijn / zijn filosoof en astronomijn,filosoof en medicijn / ander klerk en surgijn,Sidrac,Melibeus,None,None,0.572058

In [17]:
nearest_df = nearest_verses('Rijmbijbel', 'Boec Exemplaer',
                            base_df=df, vectorizer=vec, prop_filt=2)
nearest_df = nearest_df.sort_values(by='distance')
nearest_df.head(50)

# the high anmount of matches are to due to the XML file in the Corpus Middle Dutch

,tokens1,tokens2,lemmas1,lemmas2,title1,title2,intertext1,intertext2,distance
10214,Coninc van al sysrahel / Dit sacre leesmen iijwarf van hem,Dit zelue leest men van sapioene / Ooc leest men mede van cathoene,koning van al NOU-P / dit saker lezen men iewerf van hij,dit zelf lezen men van NOU-P / ook lezen men mede van NOU-P,Rijmbijbel,Boec Exemplaer,None,None,0.259530
1526,nachor / An,an ziele an lijf an eere an goet / verghetel maect zij den moet,nakoren zij / aan,aan ziel aan lijf aan eer aan goed / vergetel maken zij de moet,Rijmbijbel,Boec Exemplaer,None,None,0.307349
18927,van / brennus,Dus scrijft ons valerius zoo / Van cornelius van scipio,van / NOU-P,dus schrijven ons NOU-P zo / van NOU-P van NOU-P,Rijmbijbel,Boec Exemplaer,None,None,0.325176
8444,van / bethleem,Dus scrijft ons valerius zoo / Van cornelius van scipio,van / NOU-P,dus schrijven ons NOU-P zo / van NOU-P van NOU-P,Rijmbijbel,Boec Exemplaer,None,None,0.325176
18315,van / zorobabel,Dus scrijft ons valerius zoo / Van cornelius van scipio,van / NOU-P,dus schrijven ons NOU-P zo / van NOU-P van NOU-P,Rijmbijbel,Boec Exemplaer,None,None,0.325176
11354,samuel / Moghedi lesen dat men,Dit zelue leest men van sapioene / Ooc leest men mede van cathoene,NOU-P / mogen gij lezen dat men,dit zelf lezen men van NOU-P / ook lezen men mede van NOU-P,Rijmbijbel,Boec Exemplaer,None,None,0.331817
35327,murs / ande,an ziele an lijf an eere an goet / verghetel maect zij den moet,murs / aan de,aan ziel aan lijf aan eer aan goed / vergetel maken zij de moet,Rijmbijbel,Boec Exemplaer,None,None,0.335792
22273,An der / dedijt,an ziele an lijf an eere an goet / verghetel maect zij den moet,aan de / dedijt,aan ziel aan lijf aan eer aan goed / vergetel maken zij de moet,Rijmbijbel,Boec Exemplaer,None,None,0.335792
31177,Den sydumen al ghemanc / Die om gode dar waren comen,quam nemmermeer jn zijn ghemanc / Dit zelue leest men van sapioene,de sydume al gemang / die om NOU-P daar zijn komen,komen nimmermeer in zijn gemang / dit zelf lezen men van NOU-P,Rijmbijbel,Boec Exemplaer,None,None,0.336281
5088,Ende miragden iosephus / Seghet in sinen boeken aldus,Jnden bouc staet aldus / Dat de wijse anscipius,en miracht NOU-P / zeggen in zijn boek aldus,in de boek staan aldus / dat de wijs anscipius,Rijmbijbel,Boec Exemplaer,None,None,0.339137
28703,Desen stouten ionghelinc / Claghet iosephus van deser dinc,Valerius scrijft dese dinc / van eenen schonen jonghelinc,deze stout jongeling / klagen NOU-P van deze ding,NOU-P schrijven deze ding / van een schoon jongeling,Rijmbijbel,Boec Exemplaer,None,None,0.343257
1527,An / Loth,an ziele an lijf an eere an goet / verghetel maect zij den moet,aan / NOU-P,aan ziel aan lijf aan eer aan goed / vergetel maken zij de moet,Rijmbijbel,Boec Exemplaer,None,None,0.343416
12767,An / tarchen,an ziele an lijf an eere an goet / verghetel maect zij den moet,aan / NOU-P,aan ziel aan lijf aan eer aan goed / vergetel maken zij de moet,Rijmbijbel,Boec Exemplaer,None,None,0.343416
9411,Mens sal ons dat niet verwiten / Dese onbesnedene filisteen,Van scipioene affricane / Doemen hem aldus verweet,men dat zullen ons dat niet verwijten / deze onbesneden filisteen,van schipjoen NOU-P / toen men hij aldus verwijten,Rijmbijbel,Boec Exemplaer,None,None,0.348745
20075,alchimus / sende,Van cornelius van scipio / Dat de romeynen hem hadden ghesendt,NOU-P / zenden,van NOU-P van NOU-P / dat de Romein hij hebben zenden,Rijmbijbel,Boec Exemplaer,None,None,0.349073
17231,Ende seide die dit mach lesen / Ende ontbinden wat mach wesen,ende die alsoe ic hebbe ghelesen / mach vierande wesen,en zeggen die dit mogen lezen / en ontbinden wat mogen wezen,en die alzo ik hebben lezen / mogen vierande wezen,Rijmbijbel,Boec Exemplaer,None,None,0.349386
9570,Hets recht want hi heuets verdient / Jonathas sprac alse die vrient,De ghene die dat hadde verdient / Dat volc en ware zijn vrient,het zijn recht want hij hebben dat verdienen / NOU-P spreken als die vriend,de gene die dat hebben verdienen / dat volk ne zijn zijn vriend,Rijmbijbel,Boec Exemplaer,None,None,0.350317
16917,Wie haren god lachter sprake / Hi ende alle sine sake,toe sprac zine onghebordicheit / louch hij daer mede om de sake,wie haar NOU-P lachen spreken / hij en al zijn sake,toegespreken spreken zijn ongebordigheid / lachen hij daar mede om de sake,Rijmbijbel,Boec Exemplaer,None,None,0.357511
18130,Dranc hi van ioien so den wijn / Dat hi ghinc slapen als een suijn,Dat hij hem met zulken wijne / alse droncken de knechten zijne,drinken hij van NOU-P zo de wijn / dat hij gaan slapen als een suin,dat hij hij met zulk wijn / als drinken de knecht zijn,Rijmbijbel,Boec Exemplaer,None,None,0.360665
26070,Die also ontlijft soude wesen / Hebdi seit hi hiet ghelesen,ende die alsoe ic hebbe ghelesen / mach vierande wesen,die alzo ontlijven zullen wezen / hebben gij zeggen hij iet lezen,en die alzo ik hebben lezen / mogen vierande wezen,Rijmbijbel,Boec Exemplaer,None,None,0.362810
18129,Ende als hi siet dat dat hi beghert / Dranc hi van ioien so den wijn,Dat hij hem met zulken wijne / alse droncken de knechten zijne,en als hij zien dat dat hij begeren / drinken hij van NOU-P zo de wijn,dat hij hij met zulk wijn / als drinken de knecht zijn,Rijmbijbel,Boec Exemplaer,None,None,0.367435
7214,Ende dien van ruben wat sals me / Ghi hebt ghedaen ghi moghet keren,ghij doet daer ghij hu toe hebt ghekeert / ende icke dat ic hebbe gheleert,en dat van NOU-P wat zullen het ik / gij hebben doen gij mogen keren,gij doen daar gij u toe hebben keren / en ik dat ik hebben leren,Rijmbijbel,Boec Exemplaer,None,None,0.369130
17936,Die houerdadechte tarquinus / Van hem lesen wi aldus,Voort leest men ooc aldus / vanden keyser vespacianus,die hoverdoden NOU-P / van hij lezen wij aldus,voort lezen men ook aldus / van de keizer NOU-P,Rijmbijbel,Boec Exemplaer,None,None,0.371593
16092,Te sine wiue dese dinc / Sie hoe wel dese ionghelinc,Valerius scrijft dese dinc / van eenen schonen jonghelinc,te zijn wijf deze ding / zij hoe wel deze jongeling,NOU-P schrijven deze ding / van een schoon jongeling,Rijmbijbel,Boec Exemplaer,None,None,0.378507
27406,Met sysopen vul van asysine / Ende gaf hem van sulken wine,Ooc leest men mede van cathoene / Dat hij hem met zulken wijne,met sysoop vol van asysine / en geven hij van zulk wijn,ook lezen men mede van NOU-P / dat hij hij met zulk wijn,Rijmbijbel,Boec Exemplaer,None,None,0.382098
7145,Ende cauelen dat land / Dar ons god in heuet ghesand,Dat de romeynen hem hadden ghesendt / tote haren volke jn spaengen landt,en kavelen dat land / daar ons NOU-P in hebben zenden,dat de Romein hij hebben zenden / tot haar volk in NOU-P land,Rijmbijbel,Boec Exemplaer,None,None,0.382742
1457,Ghesciede twonder van den tonghen / Falech wan ragu den ionghen,waert dat quame van lichter tonghen / waest van ouden of van jonghen,geschieden het wonder van de tong / faleg winnen NOU-P de jongen,zijn het dat komen van licht tong / zijn het van oude of van jongen,Rijmbijbel,Boec Exemplaer,None,None,0.384084
1930,Maer si begonden hem verwiten / Dat hi een incomelinc ware,Van scipioene affricane / Doemen hem aldus verweet,maar zij beginnen hij verwijten / dat hij een inkomeling zijn,van schipjoen NOU-P / toen men hij aldus verwijten,Rijmbijbel,Boec Exemplaer,None,None,0.386265
1791,ghenaturt / An agar,an ziele an lijf an eere an goet / verghetel maect zij den moet,naturen / aan NOU-P,aan ziel aan lijf aan eer aan goed / vergetel maken zij de moet,Rijmbijbel,Boec Exemplaer,None,None,0.390991
1883,Vor hem riepen omme wrake / Ende hi sien wilde de sake,louch hij daer mede om de sake / Daer ne volghede andre wrake,voor hij roepen om wrake / en hij zien willen de sake,lachen hij daar mede om de sake / daar ne volgen ander wrake,Rijmbijbel,Boec Exemplaer,None,None,0.394496
10215,Dit sacre leesmen iijwarf van hem / Eerstwarf in bethleem,Dit zelue leest men van sapioene / Ooc leest men mede van cathoene,dit saker lezen men iewerf van hij / eerstwerf in NOU-P,dit zelf lezen men van NOU-P / ook lezen men mede van NOU-P,Rijmbijbel,Boec Exemplaer,None,None,0.394981
28980,Die hem der romeine ontsaghen / Cestius sende in dien daghen,Van cornelius van scipio / Dat de romeynen hem hadden ghesendt,die hij de Romein ontzien / NOU-P zenden in dat dag,van NOU-P van NOU-P / dat de Romein hij hebben zenden,Rijmbijbel,Boec Exemplaer,None,None,0.396935
26900,Doe leedden onsen here die manne / Tote eens mans huvs hier anne,Doe tote hem zeide een man / tyeran tyeran tyeran,toen leiden ons heer die man / tot een man huis hier aan,toen tot hij zeggen een man / thuran tieran tieran,Rijmbijbel,Boec Exemplaer,None,None,0.402159
15961,Thobias sprac seg ionghelinc / Ende berecht mi eere dinc,Valerius scrijft dese dinc / van eenen schonen jonghelinc,NOU-P spreken zeggen jongeling / en berechten ik een ding,NOU-P schrijven deze ding / van een schoon jongeling,Rijmbijbel,Boec Exemplaer,None,None,0.404366
22383,Mar hi dede om dese dinghe / Alle die edelste ionghelinghe,Valerius scrijft dese dinc / van eenen schonen jonghelinc,maar hij doen om deze ding / al die edel jongeling,NOU-P schrijven deze ding / van een schoon jongeling,Rijmbijbel,Boec Exemplaer,None,None,0.408514
3431,IOseph benediedi mede / Ende seide dat om sine sconede,ende jn zijn aenschijn mede / also dat zine scoonhede,NOU-P benedijen hij mede / en zeggen dat om zijn schoonheid,en in zijn aanschijn mede / alzo dat zijn schoonheid,Rijmbijbel,Boec Exemplaer,None,None,0.409518
30888,Dus onboden si die romeine / Doe sender vaspasiaen,Van cornelius van scipio / Dat de romeynen hem hadden ghesendt,dus ontbieden zij die Romein / toen zenden er NOU-P,van NOU-P van NOU-P / dat de Romein hij hebben zenden,Rijmbijbel,Boec Exemplaer,None,None,0.409807
1929,Sine wilder niet de sodomiten / Maer si begonden hem verwiten,Van scipioene affricane / Doemen hem aldus verweet,zijn willen niet de sodomiet / maar zij beginnen hij verwijten,van schipjoen NOU-P / toen men hij aldus verwijten,Rijmbijbel,Boec Exemplaer,None,None,0.410515
35722,Desen casteel maecte herodes / Ende was tachterste dies sijt ghewes,Dats ghedoochzaemicheit zijt ghewes / ende weet dat die vierande es,deze kasteel maken NOU-P / en zijn tachterst dies zijn gewis,dat zijn gedoogzamigheid zijn gewis / en weten dat die vierande zijn,Rijmbijbel,Boec Exemplaer,None,None,0.410976
16053,Thobias die andworde dan / Men seghet dat vii man,Van senophen den wijsen man / Dat hij ooc andwoorde dan,NOU-P die antwoorden dan / men zeggen dat zeven man,van NOU-P de wijs man / dat hij ook antwoorden dan,Rijmbijbel,Boec Exemplaer,None,None,0.412560
18602,Assuerus ghedronken van wine / Ende hiet dat men de vrouwe sine,Dat hij hem met zulken wijne / alse droncken de knechten zijne,NOU-P drinken van wijn / en heten dat men de vrouwe zijn,dat hij hij met zulk wijn / als drinken de knecht zijn,Rijmbijbel,Boec Exemplaer,None,None,0.412743
4767,Dat niemen wert ghecranct sijn lijf / Mar help dar du moghes den kaitijf,zoo blent ende zoo crancket dlijf / ende maect den mensche keytijf,dat niemand worden kranken zijn lijf / maar helpen daar du mogen de katijf,zo blind en zo kranken het lijf / en maken de mens katijf,Rijmbijbel,Boec Exemplaer,None,None,0.413160
13169,Si keren best want hem herde ghebrect / Achab verstaet an dat hi sprect,want hem daer haer ghebrac / Tot hem een rudder dus sprac,zij keren goed want hij hard gebreken / NOU-P verstaan onnen dat hij spreken,want hij daar zij gebreken / tot hij een ridder dus spreken,Rijmbijbel,Boec Exemplaer,None,None,0.414310
14536,Van dien van assiria / Die duanc osee derna,Dus scrijft ons valerius zoo / Van cornelius van scipio,van dat van NOU-P / die duang osee derna,dus schrijven ons NOU-P zo / van NOU-P van NOU-P,Rijmbijbel,Boec Exemplaer,None,None,0.420246
22198,So ward hi ghedaghet saen / Vor den keiser augustus,Vanden keyser augustus / Doe tote hem zeide een man,zo worden hij dagen zaan / voor de keizer augustus,van de keizer augustus / toen tot hij zeggen een man,Rijmbijbel,Boec Exemplaer,None,None,0.421224
28800,Rouedi / Sefforis,Dus scrijft ons valerius zoo / Van cornelius van scipio,NOU-P / sefforis,dus schrijven ons NOU-P zo / van NOU-P van NOU-P,Rijmbijbel,Boec Exemplaer,None,None,0.422575
35326,ipicus / murs,Dus scrijft ons valerius zoo / Van cornelius van scipio,NOU-P / murs,dus schrijven ons NOU-P zo / van NOU-P van NOU-P,Rijmbijbel,Boec Exemplaer,None,None,0.422575
2403,Isis / foroneus,Dus scrijft ons valerius zoo / Van cornelius van scipio,NOU-P / foroneus,dus schrijven ons NOU-P zo / van NOU-P van NOU-P,Rijmbijbel,Boec Exemplaer,None,None,0.422575
7495,cusan / minos,Dus scrijft ons valerius zoo / Van cornelius van scipio,NOU-P / minos,dus schrijven ons NOU-P zo / van NOU-P van NOU-P,Rijmbijbel,Boec Exemplaer,None,None,0.422575
10298,iebus / lesent,Dus scrijft ons valerius zoo / Van cornelius van scipio,NOU-P / lezent,dus schrijven ons NOU-P zo / van NOU-P van NOU-P,Rijmbijbel,Boec Exemplaer,None,None,0.422575

## Save the amount of parallel verses per text pair

Save the **number** of parallel verses below the threshold between two texts. It was not feasible to save all parallel verses for every text combination, as the resulting file would be too large. Therefore, only the count of retrieved verses is stored for each exhaustively combined pair. This will be used in the notebook 05-quantifying-intertexts.*

In [15]:
OUTPUT_PATH = '../data/parallel_counts_exhaustive.xlsx'
titles = sorted(df['title'].unique())

# Load existing results if available
if os.path.exists(OUTPUT_PATH):
    done_df = pd.read_excel(OUTPUT_PATH)
    done_pairs = set(tuple(sorted([row['work1'], row['work2']])) for _, row in done_df.iterrows())
    results = done_df.to_dict(orient='records')
    print(f"Resuming from previous run: {len(done_pairs)} pairs already processed.")
else:
    done_pairs = set()
    results = []
    print("Starting fresh.")

# Perform batched comparisons
total_pairs = len(titles) * (len(titles) - 1) // 2
progress_bar = tqdm(total=total_pairs - len(done_pairs), desc="Batched comparisons")

for i, title1 in enumerate(titles):
    for title2 in titles[i+1:]:
        pair_key = tuple(sorted([title1, title2]))

        if pair_key in done_pairs:
            continue

        try:
            nearest_df = nearest_verses(title1, title2, base_df=df, vectorizer=vec, prop_filt=2, rhyme_weight=0)
            count = (nearest_df['distance'] < optim_th).sum()

            results.append({
                'work1': title1,
                'work2': title2,
                'parallel_count_below_threshold': count
            })

            # Save results incrementally
            pd.DataFrame(results).to_excel(OUTPUT_PATH, index=False)

        except Exception as e:
            print(f"Error comparing {title1} and {title2}: {e}")
            continue

        progress_bar.update(1)

progress_bar.close()
print(f"Finished all comparisons. Final results saved to: {OUTPUT_PATH}")

Resuming from previous run: 20310 pairs already processed.

Batched comparisons:  92%|██████████ | 13337/14555 [23:17:52<2:07:39,  6.29s/it]

Batched comparisons:   0%|                   | 1/1218 [00:08<3:00:49,  8.91s/it]
Batched comparisons:   0%|                   | 2/1218 [00:15<2:36:17,  7.71s/it]
Batched comparisons:   0%|                   | 3/1218 [00:18<1:51:20,  5.50s/it]
Batched comparisons:   0%|                   | 4/1218 [00:20<1:25:16,  4.21s/it]
Batched comparisons:   0%|                   | 5/1218 [00:23<1:12:14,  3.57s/it]
Batched comparisons:   0%|                   | 6/1218 [00:25<1:04:15,  3.18s/it]
Batched comparisons:   1%|                   | 7/1218 [00:28<1:03:50,  3.16s/it]
Batched comparisons:   1%|▏                    | 8/1218 [00:30<55:26,  2.75s/it]
Batched comparisons:   1%|▏                    | 9/1218 [00:32<49:26,  2.45s/it]
Batched comparisons:   1%|▏                   | 10/1218 [00:34<45:54,  2.28s/it]
Batched comparisons:   1%|▏                   | 11/1218 [00:36<43:35,  2.17s/it]
Batched comparisons:   1%|▏                   | 12/1218 [00:38<42:13,  2.10s/it]
Batched comparisons:   1%|▏                   | 13/1218 [00:40<42:52,  2.13s/it]
Batched comparisons:   1%|▏                   | 14/1218 [00:42<40:55,  2.04s/it]
Batched comparisons:   1%|▏                   | 15/1218 [00:45<50:05,  2.50s/it]
Batched comparisons:   1%|▎                   | 16/1218 [00:48<50:09,  2.50s/it]
Batched comparisons:   1%|▎                   | 17/1218 [00:50<45:57,  2.30s/it]
Batched comparisons:   1%|▎                   | 18/1218 [00:52<43:02,  2.15s/it]
Batched comparisons:   2%|▎                   | 19/1218 [00:54<42:01,  2.10s/it]
Batched comparisons:   2%|▎                   | 20/1218 [00:55<40:21,  2.02s/it]
Batched comparisons:   2%|▎                   | 21/1218 [00:57<38:42,  1.94s/it]
Batched comparisons:   2%|▎                   | 22/1218 [00:59<37:55,  1.90s/it]
Batched comparisons:   2%|▍                   | 23/1218 [01:01<38:16,  1.92s/it]
Batched comparisons:   2%|▍                   | 24/1218 [01:03<40:12,  2.02s/it]
Batched comparisons:   2%|▍                   | 25/1218 [01:05<40:09,  2.02s/it]
Batched comparisons:   2%|▍                   | 26/1218 [01:07<39:28,  1.99s/it]
Batched comparisons:   2%|▍                   | 27/1218 [01:10<42:54,  2.16s/it]
Batched comparisons:   2%|▍                   | 28/1218 [01:12<41:38,  2.10s/it]
Batched comparisons:   2%|▍                   | 29/1218 [01:14<43:25,  2.19s/it]
Batched comparisons:   2%|▍                   | 30/1218 [01:16<42:48,  2.16s/it]
Batched comparisons:   3%|▌                   | 31/1218 [01:21<56:48,  2.87s/it]
Batched comparisons:   3%|▌                   | 32/1218 [01:23<51:54,  2.63s/it]
Batched comparisons:   3%|▌                   | 33/1218 [01:25<47:17,  2.39s/it]
Batched comparisons:   3%|▌                   | 34/1218 [01:27<46:09,  2.34s/it]
Batched comparisons:   3%|▌                   | 35/1218 [01:29<45:02,  2.28s/it]
Batched comparisons:   3%|▌                   | 36/1218 [01:32<47:55,  2.43s/it]
Batched comparisons:   3%|▌                   | 37/1218 [01:36<59:35,  3.03s/it]
Batched comparisons:   3%|▌                   | 38/1218 [01:39<59:01,  3.00s/it]
Batched comparisons:   3%|▋                   | 39/1218 [01:42<59:37,  3.03s/it]
Batched comparisons:   3%|▋                   | 40/1218 [01:45<55:40,  2.84s/it]
Batched comparisons:   3%|▋                   | 41/1218 [01:46<50:25,  2.57s/it]
Batched comparisons:   3%|▋                   | 42/1218 [01:50<54:25,  2.78s/it]
Batched comparisons:   4%|▋                   | 43/1218 [01:50<40:47,  2.08s/it]
Batched comparisons:   4%|▋                   | 44/1218 [01:51<31:24,  1.60s/it]
Batched comparisons:   4%|▋                   | 45/1218 [01:51<24:42,  1.26s/it]
Batched comparisons:   4%|▊                   | 46/1218 [01:53<26:17,  1.35s/it]
Batched comparisons:   4%|▊                   | 47/1218 [01:53<22:22,  1.15s/it]
Batched comparisons:   4%|▊                   | 48/1218 [01:54<18:35,  1.05it/s]
Batched comparisons:   4%|▊                   | 49/1218 [01:54<16:19,  1.19it/s]
Batched comparisons:   4%|▊                   | 50/1218 [01:55<14:15,  1.37it/s]
Batched comparisons:   4%|▊                   | 51/1218 [01:55<12:45,  1.52it/s]
Batched comparisons:   4%|▊                   | 52/1218 [01:56<11:39,  1.67it/s]
Batched comparisons:   4%|▊                   | 53/1218 [01:56<10:55,  1.78it/s]
Batched comparisons:   4%|▉                   | 54/1218 [01:57<10:09,  1.91it/s]
Batched comparisons:   5%|▉                   | 55/1218 [01:57<09:53,  1.96it/s]
Batched comparisons:   5%|▉                   | 56/1218 [01:58<09:35,  2.02it/s]
Batched comparisons:   5%|▉                   | 57/1218 [01:58<09:21,  2.07it/s]
Batched comparisons:   5%|▉                   | 58/1218 [01:59<09:15,  2.09it/s]
Batched comparisons:   5%|▉                   | 59/1218 [01:59<09:12,  2.10it/s]
Batched comparisons:   5%|▉                   | 60/1218 [02:00<09:07,  2.12it/s]
Batched comparisons:   5%|█                   | 61/1218 [02:00<09:08,  2.11it/s]
Batched comparisons:   5%|█                   | 62/1218 [02:00<08:45,  2.20it/s]
Batched comparisons:   5%|█                   | 63/1218 [02:01<08:55,  2.16it/s]
Batched comparisons:   5%|█                   | 64/1218 [02:01<08:58,  2.14it/s]
Batched comparisons:   5%|█                   | 65/1218 [02:02<08:59,  2.14it/s]
Batched comparisons:   5%|█                   | 66/1218 [02:02<09:35,  2.00it/s]
Batched comparisons:   6%|█                   | 67/1218 [02:03<09:04,  2.11it/s]
Batched comparisons:   6%|█                   | 68/1218 [02:03<09:27,  2.03it/s]
Batched comparisons:   6%|█▏                  | 69/1218 [02:04<09:22,  2.04it/s]
Batched comparisons:   6%|█▏                  | 70/1218 [02:04<08:56,  2.14it/s]
Batched comparisons:   6%|█▏                  | 71/1218 [02:05<08:57,  2.13it/s]
Batched comparisons:   6%|█▏                  | 72/1218 [02:05<08:58,  2.13it/s]
Batched comparisons:   6%|█▏                  | 73/1218 [02:06<08:42,  2.19it/s]
Batched comparisons:   6%|█▏                  | 74/1218 [02:06<08:43,  2.18it/s]
Batched comparisons:   6%|█▏                  | 75/1218 [02:07<08:48,  2.16it/s]
Batched comparisons:   6%|█▏                  | 76/1218 [02:07<08:53,  2.14it/s]
Batched comparisons:   6%|█▎                  | 77/1218 [02:08<09:00,  2.11it/s]
Batched comparisons:   6%|█▎                  | 78/1218 [02:08<08:39,  2.19it/s]
Batched comparisons:   6%|█▎                  | 79/1218 [02:08<08:53,  2.14it/s]
Batched comparisons:   7%|█▎                  | 80/1218 [02:09<08:53,  2.14it/s]
Batched comparisons:   7%|█▎                  | 81/1218 [02:10<09:20,  2.03it/s]
Batched comparisons:   7%|█▎                  | 82/1218 [02:10<08:57,  2.11it/s]
Batched comparisons:   7%|█▎                  | 83/1218 [02:10<08:54,  2.12it/s]
Batched comparisons:   7%|█▍                  | 84/1218 [02:11<08:58,  2.11it/s]
Batched comparisons:   7%|█▍                  | 85/1218 [02:11<09:13,  2.05it/s]
Batched comparisons:   7%|█▍                  | 86/1218 [02:12<09:12,  2.05it/s]
Batched comparisons:   7%|█▍                  | 87/1218 [02:12<08:52,  2.12it/s]
Batched comparisons:   7%|█▍                  | 88/1218 [02:13<08:53,  2.12it/s]
Batched comparisons:   7%|█▍                  | 89/1218 [02:13<08:51,  2.12it/s]
Batched comparisons:   7%|█▍                  | 90/1218 [02:14<08:40,  2.17it/s]
Batched comparisons:   7%|█▍                  | 91/1218 [02:14<09:07,  2.06it/s]
Batched comparisons:   8%|█▌                  | 92/1218 [02:15<09:25,  1.99it/s]
Batched comparisons:   8%|█▌                  | 93/1218 [02:18<23:29,  1.25s/it]
Batched comparisons:   8%|█▌                  | 94/1218 [02:19<24:00,  1.28s/it]
Batched comparisons:   8%|█▌                  | 95/1218 [02:20<20:33,  1.10s/it]
Batched comparisons:   8%|█▌                  | 96/1218 [02:21<20:03,  1.07s/it]

Batched comparisons:   8%|█▌                  | 97/1218 [02:22<19:07,  1.02s/it]
Batched comparisons:   8%|█▌                  | 98/1218 [02:22<17:02,  1.10it/s]
Batched comparisons:   8%|█▋                  | 99/1218 [02:23<15:05,  1.24it/s]
Batched comparisons:   8%|█▌                 | 100/1218 [02:24<13:39,  1.36it/s]
Batched comparisons:   8%|█▌                 | 101/1218 [02:24<12:49,  1.45it/s]
Batched comparisons:   8%|█▌                 | 102/1218 [02:25<12:25,  1.50it/s]
Batched comparisons:   8%|█▌                 | 103/1218 [02:25<11:40,  1.59it/s]
Batched comparisons:   9%|█▌                 | 104/1218 [02:26<11:11,  1.66it/s]
Batched comparisons:   9%|█▋                 | 105/1218 [02:26<10:30,  1.77it/s]
Batched comparisons:   9%|█▋                 | 106/1218 [02:27<10:23,  1.78it/s]
Batched comparisons:   9%|█▋                 | 107/1218 [02:27<10:26,  1.77it/s]
Batched comparisons:   9%|█▋                 | 108/1218 [02:28<10:06,  1.83it/s]
Batched comparisons:   9%|█▋                 | 109/1218 [02:28<10:02,  1.84it/s]
Batched comparisons:   9%|█▋                 | 110/1218 [02:29<10:31,  1.75it/s]
Batched comparisons:   9%|█▋                 | 111/1218 [02:30<10:41,  1.72it/s]
Batched comparisons:   9%|█▋                 | 112/1218 [02:30<10:27,  1.76it/s]
Batched comparisons:   9%|█▊                 | 113/1218 [02:31<09:57,  1.85it/s]
Batched comparisons:   9%|█▊                 | 114/1218 [02:31<10:03,  1.83it/s]
Batched comparisons:   9%|█▊                 | 115/1218 [02:32<09:57,  1.85it/s]
Batched comparisons:  10%|█▊                 | 116/1218 [02:32<09:53,  1.86it/s]
Batched comparisons:  10%|█▊                 | 117/1218 [02:33<09:51,  1.86it/s]
Batched comparisons:  10%|█▊                 | 118/1218 [02:33<09:55,  1.85it/s]
Batched comparisons:  10%|█▊                 | 119/1218 [02:34<09:35,  1.91it/s]
Batched comparisons:  10%|█▊                 | 120/1218 [02:34<09:36,  1.91it/s]
Batched comparisons:  10%|█▉                 | 121/1218 [02:35<09:39,  1.89it/s]
Batched comparisons:  10%|█▉                 | 122/1218 [02:36<10:06,  1.81it/s]
Batched comparisons:  10%|█▉                 | 123/1218 [02:36<10:16,  1.78it/s]
Batched comparisons:  10%|█▉                 | 124/1218 [02:37<10:06,  1.80it/s]
Batched comparisons:  10%|█▉                 | 125/1218 [02:37<09:59,  1.82it/s]
Batched comparisons:  10%|█▉                 | 126/1218 [02:38<10:29,  1.74it/s]
Batched comparisons:  10%|█▉                 | 127/1218 [02:39<11:19,  1.61it/s]
Batched comparisons:  11%|█▉                 | 128/1218 [02:39<10:53,  1.67it/s]
Batched comparisons:  11%|██                 | 129/1218 [02:40<10:29,  1.73it/s]
Batched comparisons:  11%|██                 | 130/1218 [02:40<10:20,  1.75it/s]
Batched comparisons:  11%|██                 | 131/1218 [02:41<10:31,  1.72it/s]
Batched comparisons:  11%|██                 | 132/1218 [02:42<11:21,  1.59it/s]
Batched comparisons:  11%|██                 | 133/1218 [02:42<11:13,  1.61it/s]
Batched comparisons:  11%|██                 | 134/1218 [02:43<11:21,  1.59it/s]
Batched comparisons:  11%|██                 | 135/1218 [02:43<10:42,  1.69it/s]
Batched comparisons:  11%|██                 | 136/1218 [02:44<10:24,  1.73it/s]
Batched comparisons:  11%|██▏                | 137/1218 [02:44<10:41,  1.69it/s]
Batched comparisons:  11%|██▏                | 138/1218 [02:45<10:46,  1.67it/s]
Batched comparisons:  11%|██▏                | 139/1218 [02:50<36:01,  2.00s/it]
Batched comparisons:  11%|██▏                | 140/1218 [02:53<36:49,  2.05s/it]
Batched comparisons:  12%|██▏                | 141/1218 [02:53<30:20,  1.69s/it]
Batched comparisons:  12%|██▏                | 142/1218 [02:55<29:10,  1.63s/it]
Batched comparisons:  12%|██▏                | 143/1218 [02:56<27:04,  1.51s/it]
Batched comparisons:  12%|██▏                | 144/1218 [02:57<22:49,  1.28s/it]
Batched comparisons:  12%|██▎                | 145/1218 [02:57<19:30,  1.09s/it]
Batched comparisons:  12%|██▎                | 146/1218 [02:58<16:53,  1.06it/s]
Batched comparisons:  12%|██▎                | 147/1218 [02:59<15:28,  1.15it/s]
Batched comparisons:  12%|██▎                | 148/1218 [03:00<14:46,  1.21it/s]
Batched comparisons:  12%|██▎                | 149/1218 [03:00<13:36,  1.31it/s]
Batched comparisons:  12%|██▎                | 150/1218 [03:01<12:56,  1.38it/s]
Batched comparisons:  12%|██▎                | 151/1218 [03:01<12:08,  1.47it/s]
Batched comparisons:  12%|██▎                | 152/1218 [03:02<12:09,  1.46it/s]
Batched comparisons:  13%|██▍                | 153/1218 [03:03<12:02,  1.47it/s]
Batched comparisons:  13%|██▍                | 154/1218 [03:03<12:19,  1.44it/s]
Batched comparisons:  13%|██▍                | 155/1218 [03:04<12:02,  1.47it/s]
Batched comparisons:  13%|██▍                | 156/1218 [03:05<13:27,  1.32it/s]
Batched comparisons:  13%|██▍                | 157/1218 [03:06<12:41,  1.39it/s]
Batched comparisons:  13%|██▍                | 158/1218 [03:06<12:10,  1.45it/s]
Batched comparisons:  13%|██▍                | 159/1218 [03:07<11:52,  1.49it/s]
Batched comparisons:  13%|██▍                | 160/1218 [03:08<12:09,  1.45it/s]
Batched comparisons:  13%|██▌                | 161/1218 [03:08<11:25,  1.54it/s]
Batched comparisons:  13%|██▌                | 162/1218 [03:09<11:09,  1.58it/s]
Batched comparisons:  13%|██▌                | 163/1218 [03:09<11:12,  1.57it/s]
Batched comparisons:  13%|██▌                | 164/1218 [03:10<11:10,  1.57it/s]
Batched comparisons:  14%|██▌                | 165/1218 [03:11<10:43,  1.64it/s]
Batched comparisons:  14%|██▌                | 166/1218 [03:11<10:49,  1.62it/s]
Batched comparisons:  14%|██▌                | 167/1218 [03:12<11:02,  1.59it/s]
Batched comparisons:  14%|██▌                | 168/1218 [03:13<11:17,  1.55it/s]
Batched comparisons:  14%|██▋                | 169/1218 [03:13<11:00,  1.59it/s]
Batched comparisons:  14%|██▋                | 170/1218 [03:14<11:11,  1.56it/s]
Batched comparisons:  14%|██▋                | 171/1218 [03:14<11:00,  1.58it/s]
Batched comparisons:  14%|██▋                | 172/1218 [03:15<11:48,  1.48it/s]
Batched comparisons:  14%|██▋                | 173/1218 [03:16<11:35,  1.50it/s]
Batched comparisons:  14%|██▋                | 174/1218 [03:16<11:16,  1.54it/s]
Batched comparisons:  14%|██▋                | 175/1218 [03:17<10:53,  1.60it/s]
Batched comparisons:  14%|██▋                | 176/1218 [03:18<10:57,  1.58it/s]
Batched comparisons:  15%|██▊                | 177/1218 [03:18<11:28,  1.51it/s]
Batched comparisons:  15%|██▊                | 178/1218 [03:19<12:24,  1.40it/s]
Batched comparisons:  15%|██▊                | 179/1218 [03:20<12:35,  1.38it/s]
Batched comparisons:  15%|██▊                | 180/1218 [03:21<12:44,  1.36it/s]
Batched comparisons:  15%|██▊                | 181/1218 [03:22<12:46,  1.35it/s]
Batched comparisons:  15%|██▊                | 182/1218 [03:22<12:02,  1.43it/s]
Batched comparisons:  15%|██▊                | 183/1218 [03:23<13:03,  1.32it/s]
Batched comparisons:  15%|██▊                | 184/1218 [03:24<16:17,  1.06it/s]
Batched comparisons:  15%|██▉                | 185/1218 [03:25<15:20,  1.12it/s]
Batched comparisons:  15%|██▉                | 186/1218 [03:26<13:37,  1.26it/s]
Batched comparisons:  15%|██▉                | 187/1218 [03:26<13:17,  1.29it/s]
Batched comparisons:  15%|██▉                | 188/1218 [03:27<12:38,  1.36it/s]
Batched comparisons:  16%|██▉                | 189/1218 [03:28<11:59,  1.43it/s]
Batched comparisons:  16%|██▉                | 190/1218 [03:28<11:01,  1.55it/s]
Batched comparisons:  16%|██▉                | 191/1218 [03:29<10:01,  1.71it/s]
Batched comparisons:  16%|██▉                | 192/1218 [03:29<09:38,  1.77it/s]
Batched comparisons:  16%|███                | 193/1218 [03:30<09:23,  1.82it/s]

Batched comparisons:  16%|███                | 194/1218 [03:30<08:46,  1.95it/s]
Batched comparisons:  16%|███                | 195/1218 [03:31<08:35,  1.99it/s]
Batched comparisons:  16%|███                | 196/1218 [03:31<08:28,  2.01it/s]
Batched comparisons:  16%|███                | 197/1218 [03:32<08:23,  2.03it/s]
Batched comparisons:  16%|███                | 198/1218 [03:32<08:22,  2.03it/s]
Batched comparisons:  16%|███                | 199/1218 [03:33<08:22,  2.03it/s]
Batched comparisons:  16%|███                | 200/1218 [03:33<08:01,  2.11it/s]
Batched comparisons:  17%|███▏               | 201/1218 [03:34<08:16,  2.05it/s]
Batched comparisons:  17%|███▏               | 202/1218 [03:34<08:23,  2.02it/s]
Batched comparisons:  17%|███▏               | 203/1218 [03:35<08:23,  2.02it/s]
Batched comparisons:  17%|███▏               | 204/1218 [03:35<08:03,  2.10it/s]
Batched comparisons:  17%|███▏               | 205/1218 [03:35<08:05,  2.09it/s]
Batched comparisons:  17%|███▏               | 206/1218 [03:36<08:08,  2.07it/s]
Batched comparisons:  17%|███▏               | 207/1218 [03:36<08:08,  2.07it/s]
Batched comparisons:  17%|███▏               | 208/1218 [03:37<07:52,  2.14it/s]
Batched comparisons:  17%|███▎               | 209/1218 [03:37<08:01,  2.10it/s]
Batched comparisons:  17%|███▎               | 210/1218 [03:38<08:09,  2.06it/s]
Batched comparisons:  17%|███▎               | 211/1218 [03:38<08:15,  2.03it/s]
Batched comparisons:  17%|███▎               | 212/1218 [03:39<08:18,  2.02it/s]
Batched comparisons:  17%|███▎               | 213/1218 [03:39<08:19,  2.01it/s]
Batched comparisons:  18%|███▎               | 214/1218 [03:40<08:09,  2.05it/s]
Batched comparisons:  18%|███▎               | 215/1218 [03:40<08:14,  2.03it/s]
Batched comparisons:  18%|███▎               | 216/1218 [03:41<08:14,  2.03it/s]
Batched comparisons:  18%|███▍               | 217/1218 [03:41<08:05,  2.06it/s]
Batched comparisons:  18%|███▍               | 218/1218 [03:42<08:06,  2.06it/s]
Batched comparisons:  18%|███▍               | 219/1218 [03:42<08:07,  2.05it/s]
Batched comparisons:  18%|███▍               | 220/1218 [03:43<08:09,  2.04it/s]
Batched comparisons:  18%|███▍               | 221/1218 [03:43<07:57,  2.09it/s]
Batched comparisons:  18%|███▍               | 222/1218 [03:44<08:03,  2.06it/s]
Batched comparisons:  18%|███▍               | 223/1218 [03:44<08:23,  1.98it/s]
Batched comparisons:  18%|███▍               | 224/1218 [03:45<08:11,  2.02it/s]
Batched comparisons:  18%|███▌               | 225/1218 [03:45<08:18,  1.99it/s]
Batched comparisons:  19%|███▌               | 226/1218 [03:46<08:16,  2.00it/s]
Batched comparisons:  19%|███▌               | 227/1218 [03:46<08:11,  2.02it/s]
Batched comparisons:  19%|███▌               | 228/1218 [03:47<08:16,  1.99it/s]
Batched comparisons:  19%|███             | 229/1218 [08:42<24:25:13, 88.89s/it]
Batched comparisons:  19%|███             | 230/1218 [09:50<22:38:29, 82.50s/it]
Batched comparisons:  19%|██▊            | 231/1218 [12:37<29:38:30, 108.12s/it]
Batched comparisons:  19%|██▊            | 232/1218 [14:43<31:00:29, 113.21s/it]
Batched comparisons:  19%|███             | 233/1218 [15:30<25:34:26, 93.47s/it]
Batched comparisons:  19%|███             | 234/1218 [16:06<20:50:58, 76.28s/it]
Batched comparisons:  19%|███             | 235/1218 [16:44<17:40:34, 64.74s/it]
Batched comparisons:  19%|███             | 236/1218 [17:23<15:34:42, 57.11s/it]
Batched comparisons:  19%|███             | 237/1218 [18:13<14:55:55, 54.80s/it]
Batched comparisons:  20%|███▏            | 238/1218 [18:39<12:34:01, 46.16s/it]
Batched comparisons:  20%|███▏            | 239/1218 [19:04<10:53:14, 40.04s/it]
Batched comparisons:  20%|███▎             | 240/1218 [19:31<9:47:00, 36.01s/it]
Batched comparisons:  20%|███▎             | 241/1218 [19:58<9:02:15, 33.30s/it]
Batched comparisons:  20%|███▍             | 242/1218 [20:27<8:38:59, 31.91s/it]
Batched comparisons:  20%|██▉            | 243/1218 [30:03<52:53:42, 195.31s/it]
Batched comparisons:  20%|███            | 244/1218 [30:30<39:08:17, 144.66s/it]
Batched comparisons:  20%|███            | 245/1218 [31:22<31:39:00, 117.10s/it]
Batched comparisons:  20%|███▏            | 246/1218 [31:58<25:01:30, 92.69s/it]
Batched comparisons:  20%|███▏            | 247/1218 [32:24<19:37:38, 72.77s/it]
Batched comparisons:  20%|███▎            | 248/1218 [32:50<15:47:16, 58.59s/it]
Batched comparisons:  20%|███▎            | 249/1218 [33:19<13:22:53, 49.71s/it]
Batched comparisons:  21%|███▎            | 250/1218 [33:45<11:26:58, 42.58s/it]
Batched comparisons:  21%|███▎            | 251/1218 [34:11<10:04:36, 37.51s/it]
Batched comparisons:  21%|███▌             | 252/1218 [34:36<9:07:29, 34.01s/it]
Batched comparisons:  21%|███▌             | 253/1218 [35:03<8:33:05, 31.90s/it]
Batched comparisons:  21%|███▌             | 254/1218 [35:30<8:05:44, 30.23s/it]
Batched comparisons:  21%|███▌             | 255/1218 [35:55<7:43:21, 28.87s/it]
Batched comparisons:  21%|███▌             | 256/1218 [36:21<7:28:23, 27.97s/it]
Batched comparisons:  21%|███▍            | 257/1218 [40:18<24:09:20, 90.49s/it]
Batched comparisons:  21%|███▍            | 258/1218 [40:45<19:03:56, 71.50s/it]
Batched comparisons:  21%|███▍            | 259/1218 [41:22<16:19:13, 61.27s/it]
Batched comparisons:  21%|███▍            | 260/1218 [41:50<13:38:20, 51.25s/it]
Batched comparisons:  21%|███▍            | 261/1218 [42:47<14:02:31, 52.82s/it]
Batched comparisons:  22%|███▍            | 262/1218 [43:16<12:07:28, 45.66s/it]
Batched comparisons:  22%|███▍            | 263/1218 [43:41<10:32:22, 39.73s/it]
Batched comparisons:  22%|███▋             | 264/1218 [44:12<9:48:01, 36.98s/it]
Batched comparisons:  22%|███▋             | 265/1218 [44:48<9:42:44, 36.69s/it]
Batched comparisons:  22%|███▍            | 266/1218 [45:31<10:12:26, 38.60s/it]
Batched comparisons:  22%|███▌            | 267/1218 [46:50<13:21:16, 50.55s/it]
Batched comparisons:  22%|███▌            | 268/1218 [47:37<13:06:04, 49.65s/it]
Batched comparisons:  22%|███▌            | 269/1218 [48:26<13:02:07, 49.45s/it]
Batched comparisons:  22%|███▌            | 270/1218 [49:02<11:59:24, 45.53s/it]
Batched comparisons:  22%|███▌            | 271/1218 [49:31<10:35:58, 40.29s/it]
Batched comparisons:  22%|███▌            | 272/1218 [50:28<11:55:49, 45.40s/it]
Batched comparisons:  22%|███▌            | 273/1218 [50:55<10:30:32, 40.03s/it]
Batched comparisons:  22%|███▌            | 274/1218 [52:00<12:28:03, 47.55s/it]
Batched comparisons:  23%|███▌            | 275/1218 [52:53<12:52:06, 49.13s/it]
Batched comparisons:  23%|███▋            | 276/1218 [53:12<10:27:00, 39.94s/it]
Batched comparisons:  23%|███▊             | 277/1218 [53:29<8:40:07, 33.16s/it]
Batched comparisons:  23%|███▉             | 278/1218 [53:44<7:12:42, 27.62s/it]
Batched comparisons:  23%|███▉             | 279/1218 [54:00<6:20:45, 24.33s/it]
Batched comparisons:  23%|███▉             | 280/1218 [54:21<6:02:20, 23.18s/it]
Batched comparisons:  23%|███▉             | 281/1218 [54:32<5:03:28, 19.43s/it]
Batched comparisons:  23%|███▉             | 282/1218 [54:42<4:21:08, 16.74s/it]
Batched comparisons:  23%|███▉             | 283/1218 [54:53<3:53:12, 14.97s/it]
Batched comparisons:  23%|███▉             | 284/1218 [55:04<3:33:38, 13.72s/it]
Batched comparisons:  23%|███▉             | 285/1218 [55:15<3:23:56, 13.11s/it]
Batched comparisons:  23%|███▉             | 286/1218 [55:29<3:25:02, 13.20s/it]
Batched comparisons:  24%|████             | 287/1218 [55:41<3:21:19, 12.97s/it]
Batched comparisons:  24%|████             | 288/1218 [56:04<4:04:51, 15.80s/it]
Batched comparisons:  24%|████             | 289/1218 [56:19<4:02:10, 15.64s/it]
Batched comparisons:  24%|████             | 290/1218 [56:30<3:39:16, 14.18s/it]

Batched comparisons:  24%|████             | 291/1218 [56:40<3:22:28, 13.10s/it]
Batched comparisons:  24%|████             | 292/1218 [56:52<3:16:28, 12.73s/it]
Batched comparisons:  24%|████             | 293/1218 [57:03<3:05:22, 12.02s/it]
Batched comparisons:  24%|████             | 294/1218 [57:13<2:57:15, 11.51s/it]
Batched comparisons:  24%|████             | 295/1218 [57:23<2:52:29, 11.21s/it]
Batched comparisons:  24%|████▏            | 296/1218 [57:34<2:50:49, 11.12s/it]
Batched comparisons:  24%|████▏            | 297/1218 [57:45<2:48:20, 10.97s/it]
Batched comparisons:  24%|████▏            | 298/1218 [57:55<2:45:36, 10.80s/it]
Batched comparisons:  25%|████▏            | 299/1218 [58:06<2:43:52, 10.70s/it]
Batched comparisons:  25%|████▏            | 300/1218 [58:21<3:04:42, 12.07s/it]
Batched comparisons:  25%|████▏            | 301/1218 [58:32<2:58:41, 11.69s/it]
Batched comparisons:  25%|████▏            | 302/1218 [58:47<3:13:09, 12.65s/it]
Batched comparisons:  25%|████▏            | 303/1218 [58:58<3:05:06, 12.14s/it]
Batched comparisons:  25%|████▏            | 304/1218 [59:21<3:56:09, 15.50s/it]
Batched comparisons:  25%|████▎            | 305/1218 [59:34<3:42:35, 14.63s/it]
Batched comparisons:  25%|████▎            | 306/1218 [59:44<3:23:55, 13.42s/it]
Batched comparisons:  25%|████▎            | 307/1218 [59:57<3:21:48, 13.29s/it]
Batched comparisons:  25%|███▊           | 308/1218 [1:00:12<3:26:28, 13.61s/it]
Batched comparisons:  25%|███▊           | 309/1218 [1:00:29<3:43:45, 14.77s/it]
Batched comparisons:  25%|███▊           | 310/1218 [1:01:01<5:02:05, 19.96s/it]
Batched comparisons:  26%|███▊           | 311/1218 [1:01:22<5:06:43, 20.29s/it]
Batched comparisons:  26%|███▊           | 312/1218 [1:01:42<5:06:09, 20.28s/it]
Batched comparisons:  26%|███▊           | 313/1218 [1:01:59<4:48:24, 19.12s/it]
Batched comparisons:  26%|███▊           | 314/1218 [1:02:10<4:13:03, 16.80s/it]
Batched comparisons:  26%|███▉           | 315/1218 [1:02:31<4:31:07, 18.01s/it]
Batched comparisons:  26%|███▉           | 316/1218 [1:02:45<4:13:28, 16.86s/it]
Batched comparisons:  26%|███▉           | 317/1218 [1:02:55<3:42:00, 14.78s/it]
Batched comparisons:  26%|███▉           | 318/1218 [1:02:59<2:53:20, 11.56s/it]
Batched comparisons:  26%|███▉           | 319/1218 [1:03:03<2:16:49,  9.13s/it]
Batched comparisons:  26%|███▉           | 320/1218 [1:03:06<1:51:04,  7.42s/it]
Batched comparisons:  26%|███▉           | 321/1218 [1:03:10<1:36:13,  6.44s/it]
Batched comparisons:  26%|███▉           | 322/1218 [1:03:15<1:26:34,  5.80s/it]
Batched comparisons:  27%|███▉           | 323/1218 [1:03:18<1:14:09,  4.97s/it]
Batched comparisons:  27%|███▉           | 324/1218 [1:03:20<1:03:10,  4.24s/it]
Batched comparisons:  27%|████▌            | 325/1218 [1:03:23<57:45,  3.88s/it]
Batched comparisons:  27%|████▌            | 326/1218 [1:03:26<51:59,  3.50s/it]
Batched comparisons:  27%|████▌            | 327/1218 [1:03:29<49:18,  3.32s/it]
Batched comparisons:  27%|████▌            | 328/1218 [1:03:32<47:38,  3.21s/it]
Batched comparisons:  27%|████▌            | 329/1218 [1:03:35<47:22,  3.20s/it]
Batched comparisons:  27%|████▌            | 330/1218 [1:03:39<53:39,  3.63s/it]
Batched comparisons:  27%|████▌            | 331/1218 [1:03:43<52:18,  3.54s/it]
Batched comparisons:  27%|████▋            | 332/1218 [1:03:45<47:21,  3.21s/it]
Batched comparisons:  27%|████▋            | 333/1218 [1:03:48<44:05,  2.99s/it]
Batched comparisons:  27%|████▋            | 334/1218 [1:03:50<43:16,  2.94s/it]
Batched comparisons:  28%|████▋            | 335/1218 [1:03:53<41:00,  2.79s/it]
Batched comparisons:  28%|████▋            | 336/1218 [1:03:55<39:06,  2.66s/it]
Batched comparisons:  28%|████▋            | 337/1218 [1:03:58<37:54,  2.58s/it]
Batched comparisons:  28%|████▋            | 338/1218 [1:04:00<37:23,  2.55s/it]
Batched comparisons:  28%|████▋            | 339/1218 [1:04:03<37:34,  2.56s/it]
Batched comparisons:  28%|████▋            | 340/1218 [1:04:05<36:42,  2.51s/it]
Batched comparisons:  28%|████▊            | 341/1218 [1:04:08<36:22,  2.49s/it]
Batched comparisons:  28%|████▊            | 342/1218 [1:04:12<42:45,  2.93s/it]
Batched comparisons:  28%|████▊            | 343/1218 [1:04:14<42:40,  2.93s/it]
Batched comparisons:  28%|████▊            | 344/1218 [1:04:18<45:04,  3.09s/it]
Batched comparisons:  28%|████▊            | 345/1218 [1:04:20<42:18,  2.91s/it]
Batched comparisons:  28%|████▊            | 346/1218 [1:04:26<54:28,  3.75s/it]
Batched comparisons:  28%|████▊            | 347/1218 [1:04:29<49:30,  3.41s/it]
Batched comparisons:  29%|████▊            | 348/1218 [1:04:31<44:39,  3.08s/it]
Batched comparisons:  29%|████▊            | 349/1218 [1:04:34<42:46,  2.95s/it]
Batched comparisons:  29%|████▉            | 350/1218 [1:04:37<42:40,  2.95s/it]
Batched comparisons:  29%|████▉            | 351/1218 [1:04:40<45:46,  3.17s/it]
Batched comparisons:  29%|████▉            | 352/1218 [1:04:47<59:12,  4.10s/it]
Batched comparisons:  29%|████▉            | 353/1218 [1:04:51<58:48,  4.08s/it]
Batched comparisons:  29%|████▉            | 354/1218 [1:04:55<58:31,  4.06s/it]
Batched comparisons:  29%|████▉            | 355/1218 [1:04:58<54:23,  3.78s/it]
Batched comparisons:  29%|████▉            | 356/1218 [1:05:00<48:42,  3.39s/it]
Batched comparisons:  29%|████▉            | 357/1218 [1:05:05<52:26,  3.65s/it]
Batched comparisons:  29%|████▍          | 358/1218 [1:05:34<2:45:12, 11.53s/it]
Batched comparisons:  29%|████▍          | 359/1218 [1:05:45<2:42:54, 11.38s/it]
Batched comparisons:  30%|████▍          | 360/1218 [1:05:55<2:32:57, 10.70s/it]
Batched comparisons:  30%|████▍          | 361/1218 [1:06:04<2:27:08, 10.30s/it]
Batched comparisons:  30%|████▍          | 362/1218 [1:06:13<2:21:32,  9.92s/it]
Batched comparisons:  30%|████▍          | 363/1218 [1:06:25<2:29:08, 10.47s/it]
Batched comparisons:  30%|████▍          | 364/1218 [1:06:31<2:09:53,  9.13s/it]
Batched comparisons:  30%|████▍          | 365/1218 [1:06:37<1:56:08,  8.17s/it]
Batched comparisons:  30%|████▌          | 366/1218 [1:06:43<1:47:25,  7.56s/it]
Batched comparisons:  30%|████▌          | 367/1218 [1:06:49<1:41:48,  7.18s/it]
Batched comparisons:  30%|████▌          | 368/1218 [1:06:56<1:39:50,  7.05s/it]
Batched comparisons:  30%|████▌          | 369/1218 [1:07:03<1:42:21,  7.23s/it]
Batched comparisons:  30%|████▌          | 370/1218 [1:07:10<1:38:10,  6.95s/it]
Batched comparisons:  30%|████▌          | 371/1218 [1:07:23<2:03:01,  8.71s/it]
Batched comparisons:  31%|████▌          | 372/1218 [1:07:32<2:04:24,  8.82s/it]
Batched comparisons:  31%|████▌          | 373/1218 [1:07:38<1:53:30,  8.06s/it]
Batched comparisons:  31%|████▌          | 374/1218 [1:07:44<1:44:55,  7.46s/it]
Batched comparisons:  31%|████▌          | 375/1218 [1:07:51<1:44:02,  7.41s/it]
Batched comparisons:  31%|████▋          | 376/1218 [1:07:57<1:38:11,  7.00s/it]
Batched comparisons:  31%|████▋          | 377/1218 [1:08:03<1:34:13,  6.72s/it]
Batched comparisons:  31%|████▋          | 378/1218 [1:08:10<1:31:24,  6.53s/it]
Batched comparisons:  31%|████▋          | 379/1218 [1:08:16<1:30:01,  6.44s/it]
Batched comparisons:  31%|████▋          | 380/1218 [1:08:22<1:30:09,  6.46s/it]
Batched comparisons:  31%|████▋          | 381/1218 [1:08:29<1:30:43,  6.50s/it]
Batched comparisons:  31%|████▋          | 382/1218 [1:08:35<1:29:11,  6.40s/it]
Batched comparisons:  31%|████▋          | 383/1218 [1:08:44<1:38:22,  7.07s/it]
Batched comparisons:  32%|████▋          | 384/1218 [1:08:50<1:34:58,  6.83s/it]
Batched comparisons:  32%|████▋          | 385/1218 [1:08:59<1:45:57,  7.63s/it]
Batched comparisons:  32%|████▊          | 386/1218 [1:09:06<1:40:17,  7.23s/it]
Batched comparisons:  32%|████▊          | 387/1218 [1:09:19<2:04:23,  8.98s/it]

Batched comparisons:  32%|████▊          | 388/1218 [1:09:26<1:56:12,  8.40s/it]
Batched comparisons:  32%|████▊          | 389/1218 [1:09:32<1:47:08,  7.75s/it]
Batched comparisons:  32%|████▊          | 390/1218 [1:09:39<1:44:54,  7.60s/it]
Batched comparisons:  32%|████▊          | 391/1218 [1:09:47<1:44:22,  7.57s/it]
Batched comparisons:  32%|████▊          | 392/1218 [1:09:57<1:56:54,  8.49s/it]
Batched comparisons:  32%|████▊          | 393/1218 [1:10:16<2:38:02, 11.49s/it]
Batched comparisons:  32%|████▊          | 394/1218 [1:10:27<2:34:38, 11.26s/it]
Batched comparisons:  32%|████▊          | 395/1218 [1:10:38<2:35:35, 11.34s/it]
Batched comparisons:  33%|████▉          | 396/1218 [1:10:46<2:22:23, 10.39s/it]
Batched comparisons:  33%|████▉          | 397/1218 [1:10:53<2:05:15,  9.15s/it]
Batched comparisons:  33%|████▉          | 398/1218 [1:11:05<2:18:15, 10.12s/it]
Batched comparisons:  33%|████▉          | 399/1218 [1:11:13<2:09:04,  9.46s/it]
Batched comparisons:  33%|████▉          | 400/1218 [1:11:19<1:56:19,  8.53s/it]
Batched comparisons:  33%|████▉          | 401/1218 [1:11:27<1:51:03,  8.16s/it]
Batched comparisons:  33%|████▉          | 402/1218 [1:11:34<1:48:25,  7.97s/it]
Batched comparisons:  33%|████▉          | 403/1218 [1:11:43<1:53:10,  8.33s/it]
Batched comparisons:  33%|████▉          | 404/1218 [1:11:48<1:38:31,  7.26s/it]
Batched comparisons:  33%|████▉          | 405/1218 [1:11:53<1:28:04,  6.50s/it]
Batched comparisons:  33%|█████          | 406/1218 [1:11:57<1:20:23,  5.94s/it]
Batched comparisons:  33%|█████          | 407/1218 [1:12:02<1:15:50,  5.61s/it]
Batched comparisons:  33%|█████          | 408/1218 [1:12:08<1:14:18,  5.50s/it]
Batched comparisons:  34%|█████          | 409/1218 [1:12:14<1:17:11,  5.73s/it]
Batched comparisons:  34%|█████          | 410/1218 [1:12:19<1:13:32,  5.46s/it]
Batched comparisons:  34%|█████          | 411/1218 [1:12:29<1:31:35,  6.81s/it]
Batched comparisons:  34%|█████          | 412/1218 [1:12:35<1:29:16,  6.65s/it]
Batched comparisons:  34%|█████          | 413/1218 [1:12:40<1:21:41,  6.09s/it]
Batched comparisons:  34%|█████          | 414/1218 [1:12:44<1:15:43,  5.65s/it]
Batched comparisons:  34%|█████          | 415/1218 [1:12:50<1:14:30,  5.57s/it]
Batched comparisons:  34%|█████          | 416/1218 [1:12:54<1:10:47,  5.30s/it]
Batched comparisons:  34%|█████▏         | 417/1218 [1:12:59<1:07:49,  5.08s/it]
Batched comparisons:  34%|█████▏         | 418/1218 [1:13:03<1:05:39,  4.92s/it]
Batched comparisons:  34%|█████▏         | 419/1218 [1:13:08<1:04:57,  4.88s/it]
Batched comparisons:  34%|█████▏         | 420/1218 [1:13:13<1:03:52,  4.80s/it]
Batched comparisons:  35%|█████▏         | 421/1218 [1:13:18<1:04:02,  4.82s/it]
Batched comparisons:  35%|█████▏         | 422/1218 [1:13:22<1:03:22,  4.78s/it]
Batched comparisons:  35%|█████▏         | 423/1218 [1:13:29<1:10:48,  5.34s/it]
Batched comparisons:  35%|█████▏         | 424/1218 [1:13:34<1:07:58,  5.14s/it]
Batched comparisons:  35%|█████▏         | 425/1218 [1:13:40<1:12:48,  5.51s/it]
Batched comparisons:  35%|█████▏         | 426/1218 [1:13:45<1:10:11,  5.32s/it]
Batched comparisons:  35%|█████▎         | 427/1218 [1:13:55<1:29:37,  6.80s/it]
Batched comparisons:  35%|█████▎         | 428/1218 [1:14:00<1:23:21,  6.33s/it]
Batched comparisons:  35%|█████▎         | 429/1218 [1:14:05<1:16:14,  5.80s/it]
Batched comparisons:  35%|█████▎         | 430/1218 [1:14:11<1:17:19,  5.89s/it]
Batched comparisons:  35%|█████▎         | 431/1218 [1:14:17<1:16:51,  5.86s/it]
Batched comparisons:  35%|█████▎         | 432/1218 [1:14:25<1:24:56,  6.48s/it]
Batched comparisons:  36%|█████▎         | 433/1218 [1:14:39<1:53:40,  8.69s/it]
Batched comparisons:  36%|█████▎         | 434/1218 [1:14:48<1:54:45,  8.78s/it]
Batched comparisons:  36%|█████▎         | 435/1218 [1:14:58<1:59:44,  9.18s/it]
Batched comparisons:  36%|█████▎         | 436/1218 [1:15:05<1:51:18,  8.54s/it]
Batched comparisons:  36%|█████▍         | 437/1218 [1:15:10<1:36:40,  7.43s/it]
Batched comparisons:  36%|█████▍         | 438/1218 [1:15:19<1:45:58,  8.15s/it]
Batched comparisons:  36%|█████▍         | 439/1218 [1:15:21<1:21:26,  6.27s/it]
Batched comparisons:  36%|█████▍         | 440/1218 [1:15:23<1:04:32,  4.98s/it]
Batched comparisons:  36%|██████▏          | 441/1218 [1:15:25<53:08,  4.10s/it]
Batched comparisons:  36%|██████▏          | 442/1218 [1:15:28<48:04,  3.72s/it]
Batched comparisons:  36%|██████▏          | 443/1218 [1:15:30<39:09,  3.03s/it]
Batched comparisons:  36%|██████▏          | 444/1218 [1:15:31<33:15,  2.58s/it]
Batched comparisons:  37%|██████▏          | 445/1218 [1:15:33<29:22,  2.28s/it]
Batched comparisons:  37%|██████▏          | 446/1218 [1:15:35<27:55,  2.17s/it]
Batched comparisons:  37%|██████▏          | 447/1218 [1:15:36<25:48,  2.01s/it]
Batched comparisons:  37%|██████▎          | 448/1218 [1:15:38<25:27,  1.98s/it]
Batched comparisons:  37%|██████▎          | 449/1218 [1:15:40<23:41,  1.85s/it]
Batched comparisons:  37%|██████▎          | 450/1218 [1:15:42<26:36,  2.08s/it]
Batched comparisons:  37%|██████▎          | 451/1218 [1:15:44<25:41,  2.01s/it]
Batched comparisons:  37%|██████▎          | 452/1218 [1:15:46<23:35,  1.85s/it]
Batched comparisons:  37%|██████▎          | 453/1218 [1:15:47<22:05,  1.73s/it]
Batched comparisons:  37%|██████▎          | 454/1218 [1:15:49<21:37,  1.70s/it]
Batched comparisons:  37%|██████▎          | 455/1218 [1:15:50<20:40,  1.63s/it]
Batched comparisons:  37%|██████▎          | 456/1218 [1:15:52<21:49,  1.72s/it]
Batched comparisons:  38%|██████▍          | 457/1218 [1:15:54<23:01,  1.82s/it]
Batched comparisons:  38%|██████▍          | 458/1218 [1:15:56<22:02,  1.74s/it]
Batched comparisons:  38%|██████▍          | 459/1218 [1:15:57<20:59,  1.66s/it]
Batched comparisons:  38%|██████▍          | 460/1218 [1:15:59<20:27,  1.62s/it]
Batched comparisons:  38%|██████▍          | 461/1218 [1:16:00<19:55,  1.58s/it]
Batched comparisons:  38%|██████▍          | 462/1218 [1:16:02<21:19,  1.69s/it]
Batched comparisons:  38%|██████▍          | 463/1218 [1:16:04<20:33,  1.63s/it]
Batched comparisons:  38%|██████▍          | 464/1218 [1:16:06<22:53,  1.82s/it]
Batched comparisons:  38%|██████▍          | 465/1218 [1:16:08<21:57,  1.75s/it]
Batched comparisons:  38%|██████▌          | 466/1218 [1:16:10<25:51,  2.06s/it]
Batched comparisons:  38%|██████▌          | 467/1218 [1:16:12<24:24,  1.95s/it]
Batched comparisons:  38%|██████▌          | 468/1218 [1:16:13<22:21,  1.79s/it]
Batched comparisons:  39%|██████▌          | 469/1218 [1:16:15<21:45,  1.74s/it]
Batched comparisons:  39%|██████▌          | 470/1218 [1:16:17<21:35,  1.73s/it]
Batched comparisons:  39%|██████▌          | 471/1218 [1:16:19<23:03,  1.85s/it]
Batched comparisons:  39%|██████▌          | 472/1218 [1:16:22<28:41,  2.31s/it]
Batched comparisons:  39%|██████▌          | 473/1218 [1:16:25<28:36,  2.30s/it]
Batched comparisons:  39%|██████▌          | 474/1218 [1:16:27<28:46,  2.32s/it]
Batched comparisons:  39%|██████▋          | 475/1218 [1:16:29<27:03,  2.18s/it]
Batched comparisons:  39%|██████▋          | 476/1218 [1:16:30<24:27,  1.98s/it]
Batched comparisons:  39%|██████▋          | 477/1218 [1:16:33<26:24,  2.14s/it]
Batched comparisons:  39%|██████▋          | 478/1218 [1:16:34<23:37,  1.92s/it]
Batched comparisons:  39%|██████▋          | 479/1218 [1:16:35<21:21,  1.73s/it]
Batched comparisons:  39%|██████▋          | 480/1218 [1:16:37<20:16,  1.65s/it]
Batched comparisons:  39%|██████▋          | 481/1218 [1:16:38<17:58,  1.46s/it]
Batched comparisons:  40%|██████▋          | 482/1218 [1:16:39<16:21,  1.33s/it]
Batched comparisons:  40%|██████▋          | 483/1218 [1:16:40<15:16,  1.25s/it]
Batched comparisons:  40%|██████▊          | 484/1218 [1:16:41<14:32,  1.19s/it]

Batched comparisons:  40%|██████▊          | 485/1218 [1:16:42<13:57,  1.14s/it]
Batched comparisons:  40%|██████▊          | 486/1218 [1:16:43<14:04,  1.15s/it]
Batched comparisons:  40%|██████▊          | 487/1218 [1:16:44<13:39,  1.12s/it]
Batched comparisons:  40%|██████▊          | 488/1218 [1:16:46<15:23,  1.27s/it]
Batched comparisons:  40%|██████▊          | 489/1218 [1:16:47<15:17,  1.26s/it]
Batched comparisons:  40%|██████▊          | 490/1218 [1:16:48<14:30,  1.20s/it]
Batched comparisons:  40%|██████▊          | 491/1218 [1:16:49<13:48,  1.14s/it]
Batched comparisons:  40%|██████▊          | 492/1218 [1:16:50<13:43,  1.13s/it]
Batched comparisons:  40%|██████▉          | 493/1218 [1:16:51<13:17,  1.10s/it]
Batched comparisons:  41%|██████▉          | 494/1218 [1:16:52<12:59,  1.08s/it]
Batched comparisons:  41%|██████▉          | 495/1218 [1:16:53<12:47,  1.06s/it]
Batched comparisons:  41%|██████▉          | 496/1218 [1:16:54<12:36,  1.05s/it]
Batched comparisons:  41%|██████▉          | 497/1218 [1:16:55<12:32,  1.04s/it]
Batched comparisons:  41%|██████▉          | 498/1218 [1:16:57<12:28,  1.04s/it]
Batched comparisons:  41%|██████▉          | 499/1218 [1:16:58<12:28,  1.04s/it]
Batched comparisons:  41%|██████▉          | 500/1218 [1:16:59<13:05,  1.09s/it]
Batched comparisons:  41%|██████▉          | 501/1218 [1:17:00<12:51,  1.08s/it]
Batched comparisons:  41%|███████          | 502/1218 [1:17:01<13:28,  1.13s/it]
Batched comparisons:  41%|███████          | 503/1218 [1:17:02<13:12,  1.11s/it]
Batched comparisons:  41%|███████          | 504/1218 [1:17:04<16:46,  1.41s/it]
Batched comparisons:  41%|███████          | 505/1218 [1:17:05<15:38,  1.32s/it]
Batched comparisons:  42%|███████          | 506/1218 [1:17:06<14:36,  1.23s/it]
Batched comparisons:  42%|███████          | 507/1218 [1:17:08<14:14,  1.20s/it]
Batched comparisons:  42%|███████          | 508/1218 [1:17:09<14:06,  1.19s/it]
Batched comparisons:  42%|███████          | 509/1218 [1:17:10<14:41,  1.24s/it]
Batched comparisons:  42%|███████          | 510/1218 [1:17:12<17:33,  1.49s/it]
Batched comparisons:  42%|███████▏         | 511/1218 [1:17:14<17:26,  1.48s/it]
Batched comparisons:  42%|███████▏         | 512/1218 [1:17:15<17:27,  1.48s/it]
Batched comparisons:  42%|███████▏         | 513/1218 [1:17:16<16:31,  1.41s/it]
Batched comparisons:  42%|███████▏         | 514/1218 [1:17:17<15:16,  1.30s/it]
Batched comparisons:  42%|███████▏         | 515/1218 [1:17:19<15:57,  1.36s/it]
Batched comparisons:  42%|███████▏         | 516/1218 [1:17:20<16:13,  1.39s/it]
Batched comparisons:  42%|███████▏         | 517/1218 [1:17:22<17:02,  1.46s/it]
Batched comparisons:  43%|███████▏         | 518/1218 [1:17:23<15:16,  1.31s/it]
Batched comparisons:  43%|███████▏         | 519/1218 [1:17:24<14:14,  1.22s/it]
Batched comparisons:  43%|███████▎         | 520/1218 [1:17:25<13:29,  1.16s/it]
Batched comparisons:  43%|███████▎         | 521/1218 [1:17:26<13:02,  1.12s/it]
Batched comparisons:  43%|███████▎         | 522/1218 [1:17:27<12:48,  1.10s/it]
Batched comparisons:  43%|███████▎         | 523/1218 [1:17:28<14:08,  1.22s/it]
Batched comparisons:  43%|███████▎         | 524/1218 [1:17:30<13:45,  1.19s/it]
Batched comparisons:  43%|███████▎         | 525/1218 [1:17:31<16:00,  1.39s/it]
Batched comparisons:  43%|███████▎         | 526/1218 [1:17:33<15:22,  1.33s/it]
Batched comparisons:  43%|███████▎         | 527/1218 [1:17:34<14:18,  1.24s/it]
Batched comparisons:  43%|███████▎         | 528/1218 [1:17:35<13:18,  1.16s/it]
Batched comparisons:  43%|███████▍         | 529/1218 [1:17:36<12:58,  1.13s/it]
Batched comparisons:  44%|███████▍         | 530/1218 [1:17:37<12:35,  1.10s/it]
Batched comparisons:  44%|███████▍         | 531/1218 [1:17:38<12:12,  1.07s/it]
Batched comparisons:  44%|███████▍         | 532/1218 [1:17:39<11:46,  1.03s/it]
Batched comparisons:  44%|███████▍         | 533/1218 [1:17:40<12:26,  1.09s/it]
Batched comparisons:  44%|███████▍         | 534/1218 [1:17:41<12:39,  1.11s/it]
Batched comparisons:  44%|███████▍         | 535/1218 [1:17:42<12:14,  1.08s/it]
Batched comparisons:  44%|███████▍         | 536/1218 [1:17:43<12:01,  1.06s/it]
Batched comparisons:  44%|███████▍         | 537/1218 [1:17:44<12:46,  1.13s/it]
Batched comparisons:  44%|███████▌         | 538/1218 [1:17:45<12:16,  1.08s/it]
Batched comparisons:  44%|███████▌         | 539/1218 [1:17:47<13:24,  1.19s/it]
Batched comparisons:  44%|███████▌         | 540/1218 [1:17:48<13:14,  1.17s/it]
Batched comparisons:  44%|███████▌         | 541/1218 [1:17:50<14:53,  1.32s/it]
Batched comparisons:  44%|███████▌         | 542/1218 [1:17:51<14:19,  1.27s/it]
Batched comparisons:  45%|███████▌         | 543/1218 [1:17:52<13:54,  1.24s/it]
Batched comparisons:  45%|███████▌         | 544/1218 [1:17:53<13:26,  1.20s/it]
Batched comparisons:  45%|███████▌         | 545/1218 [1:17:54<13:23,  1.19s/it]
Batched comparisons:  45%|███████▌         | 546/1218 [1:17:56<13:57,  1.25s/it]
Batched comparisons:  45%|███████▋         | 547/1218 [1:17:58<16:57,  1.52s/it]
Batched comparisons:  45%|███████▋         | 548/1218 [1:17:59<16:41,  1.49s/it]
Batched comparisons:  45%|███████▋         | 549/1218 [1:18:01<16:36,  1.49s/it]
Batched comparisons:  45%|███████▋         | 550/1218 [1:18:02<15:41,  1.41s/it]
Batched comparisons:  45%|███████▋         | 551/1218 [1:18:03<14:34,  1.31s/it]
Batched comparisons:  45%|███████▋         | 552/1218 [1:18:04<15:08,  1.36s/it]
Batched comparisons:  45%|███████▋         | 553/1218 [1:18:06<16:39,  1.50s/it]
Batched comparisons:  45%|███████▋         | 554/1218 [1:18:07<15:44,  1.42s/it]
Batched comparisons:  46%|███████▋         | 555/1218 [1:18:09<15:03,  1.36s/it]
Batched comparisons:  46%|███████▊         | 556/1218 [1:18:10<14:27,  1.31s/it]
Batched comparisons:  46%|███████▊         | 557/1218 [1:18:11<14:06,  1.28s/it]
Batched comparisons:  46%|███████▊         | 558/1218 [1:18:12<13:48,  1.25s/it]
Batched comparisons:  46%|███████▊         | 559/1218 [1:18:14<14:10,  1.29s/it]
Batched comparisons:  46%|███████▊         | 560/1218 [1:18:15<13:58,  1.27s/it]
Batched comparisons:  46%|███████▊         | 561/1218 [1:18:17<16:10,  1.48s/it]
Batched comparisons:  46%|███████▊         | 562/1218 [1:18:18<16:10,  1.48s/it]
Batched comparisons:  46%|███████▊         | 563/1218 [1:18:20<15:18,  1.40s/it]
Batched comparisons:  46%|███████▊         | 564/1218 [1:18:21<14:44,  1.35s/it]
Batched comparisons:  46%|███████▉         | 565/1218 [1:18:22<14:27,  1.33s/it]
Batched comparisons:  46%|███████▉         | 566/1218 [1:18:23<14:00,  1.29s/it]
Batched comparisons:  47%|███████▉         | 567/1218 [1:18:25<14:05,  1.30s/it]
Batched comparisons:  47%|███████▉         | 568/1218 [1:18:26<15:03,  1.39s/it]
Batched comparisons:  47%|███████▉         | 569/1218 [1:18:28<16:45,  1.55s/it]
Batched comparisons:  47%|███████▉         | 570/1218 [1:18:30<17:42,  1.64s/it]
Batched comparisons:  47%|███████▉         | 571/1218 [1:18:31<16:16,  1.51s/it]
Batched comparisons:  47%|███████▉         | 572/1218 [1:18:32<15:23,  1.43s/it]
Batched comparisons:  47%|███████▉         | 573/1218 [1:18:34<15:42,  1.46s/it]
Batched comparisons:  47%|████████         | 574/1218 [1:18:35<14:52,  1.39s/it]
Batched comparisons:  47%|████████         | 575/1218 [1:18:37<15:37,  1.46s/it]
Batched comparisons:  47%|████████         | 576/1218 [1:18:38<14:58,  1.40s/it]
Batched comparisons:  47%|████████         | 577/1218 [1:18:40<17:19,  1.62s/it]
Batched comparisons:  47%|████████         | 578/1218 [1:18:41<16:14,  1.52s/it]
Batched comparisons:  48%|████████         | 579/1218 [1:18:43<15:11,  1.43s/it]
Batched comparisons:  48%|████████         | 580/1218 [1:18:44<15:15,  1.44s/it]
Batched comparisons:  48%|████████         | 581/1218 [1:18:45<14:58,  1.41s/it]

Batched comparisons:  48%|████████         | 582/1218 [1:18:47<15:45,  1.49s/it]
Batched comparisons:  48%|████████▏        | 583/1218 [1:18:50<19:06,  1.80s/it]
Batched comparisons:  48%|████████▏        | 584/1218 [1:18:52<19:36,  1.85s/it]
Batched comparisons:  48%|████████▏        | 585/1218 [1:18:53<19:17,  1.83s/it]
Batched comparisons:  48%|████████▏        | 586/1218 [1:18:55<18:07,  1.72s/it]
Batched comparisons:  48%|████████▏        | 587/1218 [1:18:56<16:35,  1.58s/it]
Batched comparisons:  48%|████████▏        | 588/1218 [1:18:58<17:34,  1.67s/it]
Batched comparisons:  48%|████████▏        | 589/1218 [1:19:00<17:06,  1.63s/it]
Batched comparisons:  48%|████████▏        | 590/1218 [1:19:01<16:52,  1.61s/it]
Batched comparisons:  49%|████████▏        | 591/1218 [1:19:03<17:13,  1.65s/it]
Batched comparisons:  49%|████████▎        | 592/1218 [1:19:05<17:24,  1.67s/it]
Batched comparisons:  49%|████████▎        | 593/1218 [1:19:06<17:23,  1.67s/it]
Batched comparisons:  49%|████████▎        | 594/1218 [1:19:08<18:06,  1.74s/it]
Batched comparisons:  49%|████████▎        | 595/1218 [1:19:10<17:44,  1.71s/it]
Batched comparisons:  49%|████████▎        | 596/1218 [1:19:13<21:12,  2.05s/it]
Batched comparisons:  49%|████████▎        | 597/1218 [1:19:15<21:11,  2.05s/it]
Batched comparisons:  49%|████████▎        | 598/1218 [1:19:16<19:40,  1.90s/it]
Batched comparisons:  49%|████████▎        | 599/1218 [1:19:18<18:53,  1.83s/it]
Batched comparisons:  49%|████████▎        | 600/1218 [1:19:20<19:00,  1.85s/it]
Batched comparisons:  49%|████████▍        | 601/1218 [1:19:21<17:59,  1.75s/it]
Batched comparisons:  49%|████████▍        | 602/1218 [1:19:23<17:20,  1.69s/it]
Batched comparisons:  50%|████████▍        | 603/1218 [1:19:24<17:00,  1.66s/it]
Batched comparisons:  50%|████████▍        | 604/1218 [1:19:26<17:03,  1.67s/it]
Batched comparisons:  50%|████████▍        | 605/1218 [1:19:28<16:58,  1.66s/it]
Batched comparisons:  50%|████████▍        | 606/1218 [1:19:29<16:43,  1.64s/it]
Batched comparisons:  50%|████████▍        | 607/1218 [1:19:31<16:32,  1.62s/it]
Batched comparisons:  50%|████████▍        | 608/1218 [1:19:33<17:58,  1.77s/it]
Batched comparisons:  50%|████████▌        | 609/1218 [1:19:35<17:38,  1.74s/it]
Batched comparisons:  50%|████████▌        | 610/1218 [1:19:37<18:58,  1.87s/it]
Batched comparisons:  50%|████████▌        | 611/1218 [1:19:39<18:03,  1.79s/it]
Batched comparisons:  50%|████████▌        | 612/1218 [1:19:42<22:26,  2.22s/it]
Batched comparisons:  50%|████████▌        | 613/1218 [1:19:43<20:53,  2.07s/it]
Batched comparisons:  50%|████████▌        | 614/1218 [1:19:45<19:31,  1.94s/it]
Batched comparisons:  50%|████████▌        | 615/1218 [1:19:47<18:59,  1.89s/it]
Batched comparisons:  51%|████████▌        | 616/1218 [1:19:49<18:38,  1.86s/it]
Batched comparisons:  51%|████████▌        | 617/1218 [1:19:51<19:54,  1.99s/it]
Batched comparisons:  51%|████████▋        | 618/1218 [1:19:55<25:43,  2.57s/it]
Batched comparisons:  51%|████████▋        | 619/1218 [1:19:57<25:28,  2.55s/it]
Batched comparisons:  51%|████████▋        | 620/1218 [1:20:00<25:27,  2.55s/it]
Batched comparisons:  51%|████████▋        | 621/1218 [1:20:02<24:09,  2.43s/it]
Batched comparisons:  51%|████████▋        | 622/1218 [1:20:04<21:46,  2.19s/it]
Batched comparisons:  51%|████████▋        | 623/1218 [1:20:06<23:18,  2.35s/it]
Batched comparisons:  51%|████████▋        | 624/1218 [1:20:07<17:49,  1.80s/it]
Batched comparisons:  51%|████████▋        | 625/1218 [1:20:07<14:03,  1.42s/it]
Batched comparisons:  51%|████████▋        | 626/1218 [1:20:08<11:11,  1.13s/it]
Batched comparisons:  51%|████████▊        | 627/1218 [1:20:08<09:21,  1.05it/s]
Batched comparisons:  52%|████████▊        | 628/1218 [1:20:09<08:05,  1.22it/s]
Batched comparisons:  52%|████████▊        | 629/1218 [1:20:10<07:10,  1.37it/s]
Batched comparisons:  52%|████████▊        | 630/1218 [1:20:10<06:42,  1.46it/s]
Batched comparisons:  52%|████████▊        | 631/1218 [1:20:11<06:16,  1.56it/s]
Batched comparisons:  52%|████████▊        | 632/1218 [1:20:11<05:44,  1.70it/s]
Batched comparisons:  52%|████████▊        | 633/1218 [1:20:12<05:31,  1.77it/s]
Batched comparisons:  52%|████████▊        | 634/1218 [1:20:12<05:23,  1.81it/s]
Batched comparisons:  52%|████████▊        | 635/1218 [1:20:13<05:16,  1.84it/s]
Batched comparisons:  52%|████████▉        | 636/1218 [1:20:13<05:10,  1.87it/s]
Batched comparisons:  52%|████████▉        | 637/1218 [1:20:14<05:07,  1.89it/s]
Batched comparisons:  52%|████████▉        | 638/1218 [1:20:14<04:55,  1.97it/s]
Batched comparisons:  52%|████████▉        | 639/1218 [1:20:15<04:55,  1.96it/s]
Batched comparisons:  53%|████████▉        | 640/1218 [1:20:15<04:55,  1.96it/s]
Batched comparisons:  53%|████████▉        | 641/1218 [1:20:16<04:55,  1.95it/s]
Batched comparisons:  53%|████████▉        | 642/1218 [1:20:16<04:59,  1.92it/s]
Batched comparisons:  53%|████████▉        | 643/1218 [1:20:17<04:58,  1.92it/s]
Batched comparisons:  53%|████████▉        | 644/1218 [1:20:17<05:01,  1.90it/s]
Batched comparisons:  53%|█████████        | 645/1218 [1:20:18<04:50,  1.97it/s]
Batched comparisons:  53%|█████████        | 646/1218 [1:20:18<05:01,  1.90it/s]
Batched comparisons:  53%|█████████        | 647/1218 [1:20:19<05:02,  1.89it/s]
Batched comparisons:  53%|█████████        | 648/1218 [1:20:19<04:58,  1.91it/s]
Batched comparisons:  53%|█████████        | 649/1218 [1:20:20<04:58,  1.91it/s]
Batched comparisons:  53%|█████████        | 650/1218 [1:20:20<04:58,  1.90it/s]
Batched comparisons:  53%|█████████        | 651/1218 [1:20:21<05:02,  1.87it/s]
Batched comparisons:  54%|█████████        | 652/1218 [1:20:22<05:06,  1.85it/s]
Batched comparisons:  54%|█████████        | 653/1218 [1:20:22<05:10,  1.82it/s]
Batched comparisons:  54%|█████████▏       | 654/1218 [1:20:23<05:11,  1.81it/s]
Batched comparisons:  54%|█████████▏       | 655/1218 [1:20:23<05:07,  1.83it/s]
Batched comparisons:  54%|█████████▏       | 656/1218 [1:20:24<05:01,  1.86it/s]
Batched comparisons:  54%|█████████▏       | 657/1218 [1:20:24<05:06,  1.83it/s]
Batched comparisons:  54%|█████████▏       | 658/1218 [1:20:25<04:58,  1.88it/s]
Batched comparisons:  54%|█████████▏       | 659/1218 [1:20:25<04:52,  1.91it/s]
Batched comparisons:  54%|█████████▏       | 660/1218 [1:20:26<04:39,  1.99it/s]
Batched comparisons:  54%|█████████▏       | 661/1218 [1:20:26<04:40,  1.98it/s]
Batched comparisons:  54%|█████████▏       | 662/1218 [1:20:27<04:40,  1.98it/s]
Batched comparisons:  54%|█████████▎       | 663/1218 [1:20:27<04:36,  2.00it/s]
Batched comparisons:  55%|█████████▎       | 664/1218 [1:20:28<04:38,  1.99it/s]
Batched comparisons:  55%|█████████▎       | 665/1218 [1:20:28<04:37,  1.99it/s]
Batched comparisons:  55%|█████████▎       | 666/1218 [1:20:29<04:35,  2.00it/s]
Batched comparisons:  55%|█████████▎       | 667/1218 [1:20:29<04:36,  1.99it/s]
Batched comparisons:  55%|█████████▎       | 668/1218 [1:20:30<04:35,  2.00it/s]
Batched comparisons:  55%|█████████▎       | 669/1218 [1:20:30<04:34,  2.00it/s]
Batched comparisons:  55%|█████████▎       | 670/1218 [1:20:31<04:34,  2.00it/s]
Batched comparisons:  55%|█████████▎       | 671/1218 [1:20:31<04:24,  2.07it/s]
Batched comparisons:  55%|█████████▍       | 672/1218 [1:20:32<04:26,  2.05it/s]
Batched comparisons:  55%|█████████▍       | 673/1218 [1:20:32<04:27,  2.04it/s]
Batched comparisons:  55%|█████████▍       | 674/1218 [1:20:33<04:28,  2.03it/s]
Batched comparisons:  55%|█████████▍       | 675/1218 [1:20:33<04:31,  2.00it/s]
Batched comparisons:  56%|█████████▍       | 676/1218 [1:20:34<04:31,  2.00it/s]
Batched comparisons:  56%|█████████▍       | 677/1218 [1:20:34<04:34,  1.97it/s]
Batched comparisons:  56%|█████████▍       | 678/1218 [1:20:35<04:32,  1.98it/s]

Batched comparisons:  56%|█████████▍       | 679/1218 [1:20:35<04:30,  1.99it/s]
Batched comparisons:  56%|█████████▍       | 680/1218 [1:20:36<04:29,  1.99it/s]
Batched comparisons:  56%|█████████▌       | 681/1218 [1:20:36<04:28,  2.00it/s]
Batched comparisons:  56%|█████████▌       | 682/1218 [1:20:37<04:29,  1.99it/s]
Batched comparisons:  56%|█████████▌       | 683/1218 [1:20:37<04:20,  2.05it/s]
Batched comparisons:  56%|█████████▌       | 684/1218 [1:20:38<04:34,  1.94it/s]
Batched comparisons:  56%|█████████▌       | 685/1218 [1:20:38<04:35,  1.93it/s]
Batched comparisons:  56%|█████████▌       | 686/1218 [1:20:39<04:36,  1.92it/s]
Batched comparisons:  56%|█████████▌       | 687/1218 [1:20:39<04:39,  1.90it/s]
Batched comparisons:  56%|█████████▌       | 688/1218 [1:20:40<04:37,  1.91it/s]
Batched comparisons:  57%|█████████▌       | 689/1218 [1:20:40<04:25,  1.99it/s]
Batched comparisons:  57%|█████████▋       | 690/1218 [1:20:41<04:31,  1.95it/s]
Batched comparisons:  57%|█████████▋       | 691/1218 [1:20:41<04:38,  1.89it/s]
Batched comparisons:  57%|█████████▋       | 692/1218 [1:20:42<04:35,  1.91it/s]
Batched comparisons:  57%|█████████▋       | 693/1218 [1:20:43<04:42,  1.86it/s]
Batched comparisons:  57%|█████████▋       | 694/1218 [1:20:43<04:44,  1.84it/s]
Batched comparisons:  57%|█████████▋       | 695/1218 [1:20:44<05:01,  1.74it/s]
Batched comparisons:  57%|█████████▋       | 696/1218 [1:20:44<04:52,  1.78it/s]
Batched comparisons:  57%|█████████▋       | 697/1218 [1:20:45<04:50,  1.79it/s]
Batched comparisons:  57%|█████████▋       | 698/1218 [1:20:45<04:49,  1.80it/s]
Batched comparisons:  57%|█████████▊       | 699/1218 [1:20:46<04:49,  1.80it/s]
Batched comparisons:  57%|█████████▊       | 700/1218 [1:20:46<04:47,  1.80it/s]
Batched comparisons:  58%|█████████▊       | 701/1218 [1:20:47<04:45,  1.81it/s]
Batched comparisons:  58%|█████████▊       | 702/1218 [1:20:48<05:01,  1.71it/s]
Batched comparisons:  58%|█████████▊       | 703/1218 [1:20:48<05:05,  1.69it/s]
Batched comparisons:  58%|█████████▊       | 704/1218 [1:20:49<05:07,  1.67it/s]
Batched comparisons:  58%|█████████▊       | 705/1218 [1:20:49<04:58,  1.72it/s]
Batched comparisons:  58%|█████████▊       | 706/1218 [1:20:50<04:58,  1.71it/s]
Batched comparisons:  58%|█████████▊       | 707/1218 [1:20:51<05:02,  1.69it/s]
Batched comparisons:  58%|█████████▉       | 708/1218 [1:20:51<04:58,  1.71it/s]
Batched comparisons:  58%|█████████▉       | 709/1218 [1:20:52<04:50,  1.75it/s]
Batched comparisons:  58%|█████████▉       | 710/1218 [1:20:52<04:48,  1.76it/s]
Batched comparisons:  58%|█████████▉       | 711/1218 [1:20:53<05:00,  1.69it/s]
Batched comparisons:  58%|█████████▉       | 712/1218 [1:20:53<04:54,  1.72it/s]
Batched comparisons:  59%|█████████▉       | 713/1218 [1:20:54<04:48,  1.75it/s]
Batched comparisons:  59%|█████████▉       | 714/1218 [1:20:55<04:46,  1.76it/s]
Batched comparisons:  59%|█████████▉       | 715/1218 [1:20:55<04:45,  1.76it/s]
Batched comparisons:  59%|█████████▉       | 716/1218 [1:20:56<04:51,  1.72it/s]
Batched comparisons:  59%|██████████       | 717/1218 [1:20:57<05:17,  1.58it/s]
Batched comparisons:  59%|██████████       | 718/1218 [1:20:57<05:19,  1.57it/s]
Batched comparisons:  59%|██████████       | 719/1218 [1:20:58<05:08,  1.62it/s]
Batched comparisons:  59%|██████████       | 720/1218 [1:20:58<05:03,  1.64it/s]
Batched comparisons:  59%|██████████       | 721/1218 [1:20:59<04:54,  1.69it/s]
Batched comparisons:  59%|██████████       | 722/1218 [1:21:00<05:01,  1.65it/s]
Batched comparisons:  59%|██████████       | 723/1218 [1:21:00<04:48,  1.72it/s]
Batched comparisons:  59%|██████████       | 724/1218 [1:21:01<04:49,  1.71it/s]
Batched comparisons:  60%|██████████       | 725/1218 [1:21:01<04:45,  1.73it/s]
Batched comparisons:  60%|██████████▏      | 726/1218 [1:21:02<05:00,  1.64it/s]
Batched comparisons:  60%|██████████▏      | 727/1218 [1:21:03<04:58,  1.65it/s]
Batched comparisons:  60%|██████████▏      | 728/1218 [1:21:03<04:51,  1.68it/s]
Batched comparisons:  60%|██████████▏      | 729/1218 [1:21:04<04:45,  1.71it/s]
Batched comparisons:  60%|██████████▏      | 730/1218 [1:21:04<04:47,  1.70it/s]
Batched comparisons:  60%|██████████▏      | 731/1218 [1:21:05<04:44,  1.71it/s]
Batched comparisons:  60%|██████████▏      | 732/1218 [1:21:05<04:46,  1.70it/s]
Batched comparisons:  60%|██████████▏      | 733/1218 [1:21:06<04:47,  1.69it/s]
Batched comparisons:  60%|██████████▏      | 734/1218 [1:21:07<04:47,  1.69it/s]
Batched comparisons:  60%|██████████▎      | 735/1218 [1:21:07<04:43,  1.70it/s]
Batched comparisons:  60%|██████████▎      | 736/1218 [1:21:08<04:41,  1.71it/s]
Batched comparisons:  61%|██████████▎      | 737/1218 [1:21:08<04:39,  1.72it/s]
Batched comparisons:  61%|██████████▎      | 738/1218 [1:21:09<04:44,  1.69it/s]
Batched comparisons:  61%|██████████▎      | 739/1218 [1:21:10<04:49,  1.66it/s]
Batched comparisons:  61%|██████████▎      | 740/1218 [1:21:10<05:29,  1.45it/s]
Batched comparisons:  61%|██████████▎      | 741/1218 [1:21:11<05:36,  1.42it/s]
Batched comparisons:  61%|██████████▎      | 742/1218 [1:21:12<05:51,  1.35it/s]
Batched comparisons:  61%|██████████▎      | 743/1218 [1:21:13<05:35,  1.42it/s]
Batched comparisons:  61%|██████████▍      | 744/1218 [1:21:13<05:15,  1.50it/s]
Batched comparisons:  61%|██████████▍      | 745/1218 [1:21:14<05:03,  1.56it/s]
Batched comparisons:  61%|██████████▍      | 746/1218 [1:21:14<04:56,  1.59it/s]
Batched comparisons:  61%|██████████▍      | 747/1218 [1:21:15<05:26,  1.44it/s]
Batched comparisons:  61%|██████████▍      | 748/1218 [1:21:16<06:17,  1.25it/s]
Batched comparisons:  61%|██████████▍      | 749/1218 [1:21:17<06:06,  1.28it/s]
Batched comparisons:  62%|██████████▍      | 750/1218 [1:21:18<05:50,  1.33it/s]
Batched comparisons:  62%|██████████▍      | 751/1218 [1:21:18<05:30,  1.41it/s]
Batched comparisons:  62%|██████████▍      | 752/1218 [1:21:19<05:12,  1.49it/s]
Batched comparisons:  62%|██████████▌      | 753/1218 [1:21:20<05:11,  1.49it/s]
Batched comparisons:  62%|██████████▌      | 754/1218 [1:21:20<05:15,  1.47it/s]
Batched comparisons:  62%|██████████▌      | 755/1218 [1:21:21<05:11,  1.49it/s]
Batched comparisons:  62%|██████████▌      | 756/1218 [1:21:22<05:37,  1.37it/s]
Batched comparisons:  62%|██████████▌      | 757/1218 [1:21:23<05:35,  1.37it/s]
Batched comparisons:  62%|██████████▌      | 758/1218 [1:21:23<05:24,  1.42it/s]
Batched comparisons:  62%|██████████▌      | 759/1218 [1:21:24<05:18,  1.44it/s]
Batched comparisons:  62%|██████████▌      | 760/1218 [1:21:25<05:20,  1.43it/s]
Batched comparisons:  62%|██████████▌      | 761/1218 [1:21:25<05:12,  1.46it/s]
Batched comparisons:  63%|██████████▋      | 762/1218 [1:21:26<05:10,  1.47it/s]
Batched comparisons:  63%|██████████▋      | 763/1218 [1:21:27<05:07,  1.48it/s]
Batched comparisons:  63%|██████████▋      | 764/1218 [1:21:27<05:13,  1.45it/s]
Batched comparisons:  63%|██████████▋      | 765/1218 [1:21:28<05:02,  1.50it/s]
Batched comparisons:  63%|██████████▋      | 766/1218 [1:21:29<04:59,  1.51it/s]
Batched comparisons:  63%|██████████▋      | 767/1218 [1:21:29<04:57,  1.52it/s]
Batched comparisons:  63%|██████████▋      | 768/1218 [1:21:30<05:27,  1.37it/s]
Batched comparisons:  63%|██████████▋      | 769/1218 [1:21:31<05:48,  1.29it/s]
Batched comparisons:  63%|██████████▋      | 770/1218 [1:21:32<05:48,  1.29it/s]
Batched comparisons:  63%|██████████▊      | 771/1218 [1:21:32<05:32,  1.34it/s]
Batched comparisons:  63%|██████████▊      | 772/1218 [1:21:33<05:50,  1.27it/s]
Batched comparisons:  63%|██████████▊      | 773/1218 [1:21:34<05:35,  1.33it/s]
Batched comparisons:  64%|██████████▊      | 774/1218 [1:21:35<05:14,  1.41it/s]
Batched comparisons:  64%|██████████▊      | 775/1218 [1:21:35<05:10,  1.43it/s]

Batched comparisons:  64%|██████████▊      | 776/1218 [1:21:36<05:09,  1.43it/s]
Batched comparisons:  64%|██████████▊      | 777/1218 [1:21:37<05:27,  1.35it/s]
Batched comparisons:  64%|██████████▊      | 778/1218 [1:21:38<06:24,  1.14it/s]
Batched comparisons:  64%|██████████▊      | 779/1218 [1:21:39<06:19,  1.16it/s]
Batched comparisons:  64%|██████████▉      | 780/1218 [1:21:40<06:26,  1.13it/s]
Batched comparisons:  64%|██████████▉      | 781/1218 [1:21:40<06:06,  1.19it/s]
Batched comparisons:  64%|██████████▉      | 782/1218 [1:21:41<05:35,  1.30it/s]
Batched comparisons:  64%|██████████▉      | 783/1218 [1:21:42<05:45,  1.26it/s]
Batched comparisons:  64%|██████████▉      | 784/1218 [1:21:43<05:54,  1.23it/s]
Batched comparisons:  64%|██████████▉      | 785/1218 [1:21:44<06:54,  1.04it/s]
Batched comparisons:  65%|██████████▉      | 786/1218 [1:21:45<06:59,  1.03it/s]
Batched comparisons:  65%|██████████▉      | 787/1218 [1:21:46<06:45,  1.06it/s]
Batched comparisons:  65%|██████████▉      | 788/1218 [1:21:47<06:33,  1.09it/s]
Batched comparisons:  65%|███████████      | 789/1218 [1:21:48<06:31,  1.10it/s]
Batched comparisons:  65%|███████████      | 790/1218 [1:21:49<06:22,  1.12it/s]
Batched comparisons:  65%|███████████      | 791/1218 [1:21:49<06:15,  1.14it/s]
Batched comparisons:  65%|███████████      | 792/1218 [1:21:50<06:11,  1.15it/s]
Batched comparisons:  65%|███████████      | 793/1218 [1:21:51<06:10,  1.15it/s]
Batched comparisons:  65%|███████████      | 794/1218 [1:21:52<06:15,  1.13it/s]
Batched comparisons:  65%|███████████      | 795/1218 [1:21:53<06:14,  1.13it/s]
Batched comparisons:  65%|███████████      | 796/1218 [1:21:54<06:10,  1.14it/s]
Batched comparisons:  65%|███████████      | 797/1218 [1:21:55<06:32,  1.07it/s]
Batched comparisons:  66%|███████████▏     | 798/1218 [1:21:56<06:23,  1.09it/s]
Batched comparisons:  66%|███████████▏     | 799/1218 [1:21:57<06:37,  1.06it/s]
Batched comparisons:  66%|███████████▏     | 800/1218 [1:21:58<06:26,  1.08it/s]
Batched comparisons:  66%|███████████▏     | 801/1218 [1:21:59<07:22,  1.06s/it]
Batched comparisons:  66%|███████████▏     | 802/1218 [1:22:00<07:01,  1.01s/it]
Batched comparisons:  66%|███████████▏     | 803/1218 [1:22:01<06:42,  1.03it/s]
Batched comparisons:  66%|███████████▏     | 804/1218 [1:22:02<06:36,  1.05it/s]
Batched comparisons:  66%|███████████▏     | 805/1218 [1:22:03<06:27,  1.07it/s]
Batched comparisons:  66%|███████████▏     | 806/1218 [1:22:04<06:47,  1.01it/s]
Batched comparisons:  66%|███████████▎     | 807/1218 [1:22:05<08:15,  1.20s/it]
Batched comparisons:  66%|███████████▎     | 808/1218 [1:22:07<08:11,  1.20s/it]
Batched comparisons:  66%|███████████▎     | 809/1218 [1:22:08<08:11,  1.20s/it]
Batched comparisons:  67%|███████████▎     | 810/1218 [1:22:09<07:39,  1.13s/it]
Batched comparisons:  67%|███████████▎     | 811/1218 [1:22:10<07:07,  1.05s/it]
Batched comparisons:  67%|███████████▎     | 812/1218 [1:22:11<07:30,  1.11s/it]
Batched comparisons:  67%|███████████▎     | 813/1218 [1:22:12<06:35,  1.02it/s]
Batched comparisons:  67%|███████████▎     | 814/1218 [1:22:12<05:48,  1.16it/s]
Batched comparisons:  67%|███████████▍     | 815/1218 [1:22:13<05:11,  1.30it/s]
Batched comparisons:  67%|███████████▍     | 816/1218 [1:22:13<04:37,  1.45it/s]
Batched comparisons:  67%|███████████▍     | 817/1218 [1:22:14<04:21,  1.53it/s]
Batched comparisons:  67%|███████████▍     | 818/1218 [1:22:14<04:10,  1.59it/s]
Batched comparisons:  67%|███████████▍     | 819/1218 [1:22:15<04:14,  1.57it/s]
Batched comparisons:  67%|███████████▍     | 820/1218 [1:22:16<04:08,  1.60it/s]
Batched comparisons:  67%|███████████▍     | 821/1218 [1:22:16<03:55,  1.68it/s]
Batched comparisons:  67%|███████████▍     | 822/1218 [1:22:17<03:51,  1.71it/s]
Batched comparisons:  68%|███████████▍     | 823/1218 [1:22:17<03:47,  1.74it/s]
Batched comparisons:  68%|███████████▌     | 824/1218 [1:22:18<03:44,  1.75it/s]
Batched comparisons:  68%|███████████▌     | 825/1218 [1:22:18<03:41,  1.77it/s]
Batched comparisons:  68%|███████████▌     | 826/1218 [1:22:19<03:42,  1.76it/s]
Batched comparisons:  68%|███████████▌     | 827/1218 [1:22:20<03:45,  1.73it/s]
Batched comparisons:  68%|███████████▌     | 828/1218 [1:22:20<03:43,  1.75it/s]
Batched comparisons:  68%|███████████▌     | 829/1218 [1:22:21<03:47,  1.71it/s]
Batched comparisons:  68%|███████████▌     | 830/1218 [1:22:21<03:44,  1.73it/s]
Batched comparisons:  68%|███████████▌     | 831/1218 [1:22:22<03:40,  1.75it/s]
Batched comparisons:  68%|███████████▌     | 832/1218 [1:22:22<03:39,  1.76it/s]
Batched comparisons:  68%|███████████▋     | 833/1218 [1:22:23<03:40,  1.75it/s]
Batched comparisons:  68%|███████████▋     | 834/1218 [1:22:24<03:45,  1.70it/s]
Batched comparisons:  69%|███████████▋     | 835/1218 [1:22:24<04:04,  1.57it/s]
Batched comparisons:  69%|███████████▋     | 836/1218 [1:22:25<04:04,  1.56it/s]
Batched comparisons:  69%|███████████▋     | 837/1218 [1:22:26<04:03,  1.57it/s]
Batched comparisons:  69%|███████████▋     | 838/1218 [1:22:26<03:56,  1.60it/s]
Batched comparisons:  69%|███████████▋     | 839/1218 [1:22:27<03:54,  1.61it/s]
Batched comparisons:  69%|███████████▋     | 840/1218 [1:22:27<03:52,  1.63it/s]
Batched comparisons:  69%|███████████▋     | 841/1218 [1:22:30<06:56,  1.10s/it]
Batched comparisons:  69%|███████████▊     | 842/1218 [1:22:31<08:12,  1.31s/it]
Batched comparisons:  69%|███████████▊     | 843/1218 [1:22:33<09:00,  1.44s/it]
Batched comparisons:  69%|███████████▊     | 844/1218 [1:22:35<09:47,  1.57s/it]
Batched comparisons:  69%|███████████▊     | 845/1218 [1:22:37<10:05,  1.62s/it]
Batched comparisons:  69%|███████████▊     | 846/1218 [1:22:39<10:17,  1.66s/it]
Batched comparisons:  70%|███████████▊     | 847/1218 [1:22:40<10:45,  1.74s/it]
Batched comparisons:  70%|███████████▊     | 848/1218 [1:22:42<10:55,  1.77s/it]
Batched comparisons:  70%|███████████▊     | 849/1218 [1:22:44<11:11,  1.82s/it]
Batched comparisons:  70%|███████████▊     | 850/1218 [1:22:46<11:05,  1.81s/it]
Batched comparisons:  70%|███████████▉     | 851/1218 [1:22:48<10:59,  1.80s/it]
Batched comparisons:  70%|███████████▉     | 852/1218 [1:22:51<12:49,  2.10s/it]
Batched comparisons:  70%|███████████▉     | 853/1218 [1:22:52<12:15,  2.02s/it]
Batched comparisons:  70%|███████████▉     | 854/1218 [1:22:55<12:46,  2.11s/it]
Batched comparisons:  70%|███████████▉     | 855/1218 [1:22:57<12:11,  2.02s/it]
Batched comparisons:  70%|███████████▉     | 856/1218 [1:23:00<14:34,  2.42s/it]
Batched comparisons:  70%|███████████▉     | 857/1218 [1:23:02<13:38,  2.27s/it]
Batched comparisons:  70%|███████████▉     | 858/1218 [1:23:04<12:39,  2.11s/it]
Batched comparisons:  71%|███████████▉     | 859/1218 [1:23:06<12:22,  2.07s/it]
Batched comparisons:  71%|████████████     | 860/1218 [1:23:08<12:54,  2.16s/it]
Batched comparisons:  71%|████████████     | 861/1218 [1:23:11<13:37,  2.29s/it]
Batched comparisons:  71%|████████████     | 862/1218 [1:23:15<18:11,  3.07s/it]
Batched comparisons:  71%|████████████     | 863/1218 [1:23:18<17:44,  3.00s/it]
Batched comparisons:  71%|████████████     | 864/1218 [1:23:21<18:07,  3.07s/it]
Batched comparisons:  71%|████████████     | 865/1218 [1:23:24<16:40,  2.83s/it]
Batched comparisons:  71%|████████████     | 866/1218 [1:23:26<14:52,  2.54s/it]
Batched comparisons:  71%|████████████     | 867/1218 [1:23:29<16:05,  2.75s/it]
Batched comparisons:  71%|████████████     | 868/1218 [1:23:30<13:17,  2.28s/it]
Batched comparisons:  71%|████████████▏    | 869/1218 [1:23:31<10:59,  1.89s/it]
Batched comparisons:  71%|████████████▏    | 870/1218 [1:23:32<09:29,  1.64s/it]
Batched comparisons:  72%|████████████▏    | 871/1218 [1:23:33<08:18,  1.44s/it]
Batched comparisons:  72%|████████████▏    | 872/1218 [1:23:34<07:28,  1.30s/it]

Batched comparisons:  72%|████████████▏    | 873/1218 [1:23:35<06:52,  1.20s/it]
Batched comparisons:  72%|████████████▏    | 874/1218 [1:23:36<06:30,  1.14s/it]
Batched comparisons:  72%|████████████▏    | 875/1218 [1:23:37<06:14,  1.09s/it]
Batched comparisons:  72%|████████████▏    | 876/1218 [1:23:38<06:02,  1.06s/it]
Batched comparisons:  72%|████████████▏    | 877/1218 [1:23:39<05:54,  1.04s/it]
Batched comparisons:  72%|████████████▎    | 878/1218 [1:23:40<06:16,  1.11s/it]
Batched comparisons:  72%|████████████▎    | 879/1218 [1:23:41<06:17,  1.11s/it]
Batched comparisons:  72%|████████████▎    | 880/1218 [1:23:43<06:50,  1.21s/it]
Batched comparisons:  72%|████████████▎    | 881/1218 [1:23:44<06:27,  1.15s/it]
Batched comparisons:  72%|████████████▎    | 882/1218 [1:23:45<07:21,  1.31s/it]
Batched comparisons:  72%|████████████▎    | 883/1218 [1:23:47<07:02,  1.26s/it]
Batched comparisons:  73%|████████████▎    | 884/1218 [1:23:48<06:32,  1.17s/it]
Batched comparisons:  73%|████████████▎    | 885/1218 [1:23:49<06:19,  1.14s/it]
Batched comparisons:  73%|████████████▎    | 886/1218 [1:23:50<06:15,  1.13s/it]
Batched comparisons:  73%|████████████▍    | 887/1218 [1:23:51<06:40,  1.21s/it]
Batched comparisons:  73%|████████████▍    | 888/1218 [1:23:53<07:53,  1.44s/it]
Batched comparisons:  73%|████████████▍    | 889/1218 [1:23:55<07:54,  1.44s/it]
Batched comparisons:  73%|████████████▍    | 890/1218 [1:23:56<08:21,  1.53s/it]
Batched comparisons:  73%|████████████▍    | 891/1218 [1:23:58<08:01,  1.47s/it]
Batched comparisons:  73%|████████████▍    | 892/1218 [1:23:59<07:13,  1.33s/it]
Batched comparisons:  73%|████████████▍    | 893/1218 [1:24:00<07:33,  1.40s/it]
Batched comparisons:  73%|████████████▍    | 894/1218 [1:24:01<06:09,  1.14s/it]
Batched comparisons:  73%|████████████▍    | 895/1218 [1:24:01<05:17,  1.02it/s]
Batched comparisons:  74%|████████████▌    | 896/1218 [1:24:02<04:34,  1.17it/s]
Batched comparisons:  74%|████████████▌    | 897/1218 [1:24:02<04:03,  1.32it/s]
Batched comparisons:  74%|████████████▌    | 898/1218 [1:24:03<03:41,  1.44it/s]
Batched comparisons:  74%|████████████▌    | 899/1218 [1:24:04<03:26,  1.54it/s]
Batched comparisons:  74%|████████████▌    | 900/1218 [1:24:04<03:16,  1.62it/s]
Batched comparisons:  74%|████████████▌    | 901/1218 [1:24:05<03:08,  1.68it/s]
Batched comparisons:  74%|████████████▌    | 902/1218 [1:24:05<03:02,  1.73it/s]
Batched comparisons:  74%|████████████▌    | 903/1218 [1:24:06<03:01,  1.73it/s]
Batched comparisons:  74%|████████████▌    | 904/1218 [1:24:06<03:01,  1.73it/s]
Batched comparisons:  74%|████████████▋    | 905/1218 [1:24:07<03:01,  1.72it/s]
Batched comparisons:  74%|████████████▋    | 906/1218 [1:24:07<02:58,  1.75it/s]
Batched comparisons:  74%|████████████▋    | 907/1218 [1:24:08<03:05,  1.68it/s]
Batched comparisons:  75%|████████████▋    | 908/1218 [1:24:09<03:00,  1.71it/s]
Batched comparisons:  75%|████████████▋    | 909/1218 [1:24:09<02:56,  1.75it/s]
Batched comparisons:  75%|████████████▋    | 910/1218 [1:24:10<02:54,  1.76it/s]
Batched comparisons:  75%|████████████▋    | 911/1218 [1:24:10<02:53,  1.76it/s]
Batched comparisons:  75%|████████████▋    | 912/1218 [1:24:11<02:56,  1.74it/s]
Batched comparisons:  75%|████████████▋    | 913/1218 [1:24:12<03:08,  1.62it/s]
Batched comparisons:  75%|████████████▊    | 914/1218 [1:24:12<03:08,  1.61it/s]
Batched comparisons:  75%|████████████▊    | 915/1218 [1:24:13<03:08,  1.61it/s]
Batched comparisons:  75%|████████████▊    | 916/1218 [1:24:13<03:03,  1.65it/s]
Batched comparisons:  75%|████████████▊    | 917/1218 [1:24:14<03:00,  1.67it/s]
Batched comparisons:  75%|████████████▊    | 918/1218 [1:24:15<03:03,  1.64it/s]
Batched comparisons:  75%|████████████▊    | 919/1218 [1:24:15<02:53,  1.73it/s]
Batched comparisons:  76%|████████████▊    | 920/1218 [1:24:16<02:45,  1.80it/s]
Batched comparisons:  76%|████████████▊    | 921/1218 [1:24:16<02:39,  1.87it/s]
Batched comparisons:  76%|████████████▊    | 922/1218 [1:24:17<02:34,  1.91it/s]
Batched comparisons:  76%|████████████▉    | 923/1218 [1:24:17<02:32,  1.94it/s]
Batched comparisons:  76%|████████████▉    | 924/1218 [1:24:18<02:30,  1.96it/s]
Batched comparisons:  76%|████████████▉    | 925/1218 [1:24:18<02:30,  1.94it/s]
Batched comparisons:  76%|████████████▉    | 926/1218 [1:24:19<02:29,  1.95it/s]
Batched comparisons:  76%|████████████▉    | 927/1218 [1:24:19<02:29,  1.95it/s]
Batched comparisons:  76%|████████████▉    | 928/1218 [1:24:20<02:27,  1.97it/s]
Batched comparisons:  76%|████████████▉    | 929/1218 [1:24:20<02:32,  1.90it/s]
Batched comparisons:  76%|████████████▉    | 930/1218 [1:24:21<02:25,  1.98it/s]
Batched comparisons:  76%|████████████▉    | 931/1218 [1:24:21<02:29,  1.92it/s]
Batched comparisons:  77%|█████████████    | 932/1218 [1:24:22<02:27,  1.94it/s]
Batched comparisons:  77%|█████████████    | 933/1218 [1:24:22<02:26,  1.95it/s]
Batched comparisons:  77%|█████████████    | 934/1218 [1:24:23<02:20,  2.03it/s]
Batched comparisons:  77%|█████████████    | 935/1218 [1:24:23<02:20,  2.01it/s]
Batched comparisons:  77%|█████████████    | 936/1218 [1:24:24<02:22,  1.98it/s]
Batched comparisons:  77%|█████████████    | 937/1218 [1:24:24<02:28,  1.89it/s]
Batched comparisons:  77%|█████████████    | 938/1218 [1:24:25<02:27,  1.89it/s]
Batched comparisons:  77%|█████████████    | 939/1218 [1:24:25<02:27,  1.89it/s]
Batched comparisons:  77%|█████████████    | 940/1218 [1:24:26<02:25,  1.91it/s]
Batched comparisons:  77%|█████████████▏   | 941/1218 [1:24:26<02:28,  1.87it/s]
Batched comparisons:  77%|█████████████▏   | 942/1218 [1:24:27<02:30,  1.83it/s]
Batched comparisons:  77%|█████████████▏   | 943/1218 [1:24:28<02:42,  1.69it/s]
Batched comparisons:  78%|█████████████▏   | 944/1218 [1:24:28<02:49,  1.62it/s]
Batched comparisons:  78%|█████████████▏   | 945/1218 [1:24:29<02:53,  1.57it/s]
Batched comparisons:  78%|█████████████▏   | 946/1218 [1:24:30<03:04,  1.47it/s]
Batched comparisons:  78%|█████████████▏   | 947/1218 [1:24:31<03:02,  1.49it/s]
Batched comparisons:  78%|█████████████▏   | 948/1218 [1:24:31<03:11,  1.41it/s]
Batched comparisons:  78%|█████████████▏   | 949/1218 [1:24:32<03:16,  1.37it/s]
Batched comparisons:  78%|█████████████▎   | 950/1218 [1:24:33<03:21,  1.33it/s]
Batched comparisons:  78%|█████████████▎   | 951/1218 [1:24:34<03:11,  1.40it/s]
Batched comparisons:  78%|█████████████▎   | 952/1218 [1:24:34<03:17,  1.34it/s]
Batched comparisons:  78%|█████████████▎   | 953/1218 [1:24:35<03:13,  1.37it/s]
Batched comparisons:  78%|█████████████▎   | 954/1218 [1:24:36<03:31,  1.25it/s]
Batched comparisons:  78%|█████████████▎   | 955/1218 [1:24:37<03:19,  1.32it/s]
Batched comparisons:  78%|█████████████▎   | 956/1218 [1:24:37<03:13,  1.36it/s]
Batched comparisons:  79%|█████████████▎   | 957/1218 [1:24:38<03:18,  1.31it/s]
Batched comparisons:  79%|█████████████▎   | 958/1218 [1:24:39<03:18,  1.31it/s]
Batched comparisons:  79%|█████████████▍   | 959/1218 [1:24:40<03:22,  1.28it/s]
Batched comparisons:  79%|█████████████▍   | 960/1218 [1:24:41<03:54,  1.10it/s]
Batched comparisons:  79%|█████████████▍   | 961/1218 [1:24:42<03:50,  1.11it/s]
Batched comparisons:  79%|█████████████▍   | 962/1218 [1:24:43<03:54,  1.09it/s]
Batched comparisons:  79%|█████████████▍   | 963/1218 [1:24:44<04:32,  1.07s/it]
Batched comparisons:  79%|█████████████▍   | 964/1218 [1:24:45<04:09,  1.02it/s]
Batched comparisons:  79%|█████████████▍   | 965/1218 [1:24:46<04:04,  1.03it/s]
Batched comparisons:  79%|█████████████▍   | 966/1218 [1:24:46<03:27,  1.22it/s]
Batched comparisons:  79%|█████████████▍   | 967/1218 [1:24:47<03:03,  1.37it/s]
Batched comparisons:  79%|█████████████▌   | 968/1218 [1:24:47<02:46,  1.50it/s]
Batched comparisons:  80%|█████████████▌   | 969/1218 [1:24:48<02:34,  1.61it/s]

Batched comparisons:  80%|█████████████▌   | 970/1218 [1:24:48<02:21,  1.75it/s]
Batched comparisons:  80%|█████████████▌   | 971/1218 [1:24:49<02:16,  1.82it/s]
Batched comparisons:  80%|█████████████▌   | 972/1218 [1:24:49<02:14,  1.83it/s]
Batched comparisons:  80%|█████████████▌   | 973/1218 [1:24:50<02:15,  1.80it/s]
Batched comparisons:  80%|█████████████▌   | 974/1218 [1:24:51<02:10,  1.87it/s]
Batched comparisons:  80%|█████████████▌   | 975/1218 [1:24:51<02:08,  1.90it/s]
Batched comparisons:  80%|█████████████▌   | 976/1218 [1:24:52<02:09,  1.86it/s]
Batched comparisons:  80%|█████████████▋   | 977/1218 [1:24:52<02:07,  1.88it/s]
Batched comparisons:  80%|█████████████▋   | 978/1218 [1:24:53<02:01,  1.97it/s]
Batched comparisons:  80%|█████████████▋   | 979/1218 [1:24:53<02:01,  1.97it/s]
Batched comparisons:  80%|█████████████▋   | 980/1218 [1:24:54<02:01,  1.96it/s]
Batched comparisons:  81%|█████████████▋   | 981/1218 [1:24:54<02:02,  1.94it/s]
Batched comparisons:  81%|█████████████▋   | 982/1218 [1:24:55<02:07,  1.85it/s]
Batched comparisons:  81%|█████████████▋   | 983/1218 [1:24:55<02:06,  1.86it/s]
Batched comparisons:  81%|█████████████▋   | 984/1218 [1:24:56<02:06,  1.86it/s]
Batched comparisons:  81%|█████████████▋   | 985/1218 [1:24:56<02:04,  1.87it/s]
Batched comparisons:  81%|█████████████▊   | 986/1218 [1:24:57<02:01,  1.90it/s]
Batched comparisons:  81%|█████████████▊   | 987/1218 [1:24:57<02:02,  1.88it/s]
Batched comparisons:  81%|█████████████▊   | 988/1218 [1:24:58<01:59,  1.92it/s]
Batched comparisons:  81%|█████████████▊   | 989/1218 [1:24:58<01:57,  1.94it/s]
Batched comparisons:  81%|█████████████▊   | 990/1218 [1:24:59<01:55,  1.97it/s]
Batched comparisons:  81%|█████████████▊   | 991/1218 [1:24:59<01:54,  1.98it/s]
Batched comparisons:  81%|█████████████▊   | 992/1218 [1:25:00<01:53,  1.99it/s]
Batched comparisons:  82%|█████████████▊   | 993/1218 [1:25:00<01:54,  1.96it/s]
Batched comparisons:  82%|█████████████▊   | 994/1218 [1:25:01<01:54,  1.96it/s]
Batched comparisons:  82%|█████████████▉   | 995/1218 [1:25:01<01:54,  1.96it/s]
Batched comparisons:  82%|█████████████▉   | 996/1218 [1:25:02<01:52,  1.97it/s]
Batched comparisons:  82%|█████████████▉   | 997/1218 [1:25:02<01:54,  1.94it/s]
Batched comparisons:  82%|█████████████▉   | 998/1218 [1:25:03<01:52,  1.96it/s]
Batched comparisons:  82%|█████████████▉   | 999/1218 [1:25:03<01:50,  1.98it/s]
Batched comparisons:  82%|█████████████▏  | 1000/1218 [1:25:04<01:50,  1.98it/s]
Batched comparisons:  82%|█████████████▏  | 1001/1218 [1:25:04<01:49,  1.98it/s]
Batched comparisons:  82%|█████████████▏  | 1002/1218 [1:25:05<01:49,  1.97it/s]
Batched comparisons:  82%|█████████████▏  | 1003/1218 [1:25:06<01:58,  1.81it/s]
Batched comparisons:  82%|█████████████▏  | 1004/1218 [1:25:06<01:57,  1.81it/s]
Batched comparisons:  83%|█████████████▏  | 1005/1218 [1:25:07<02:02,  1.74it/s]
Batched comparisons:  83%|█████████████▏  | 1006/1218 [1:25:07<01:54,  1.86it/s]
Batched comparisons:  83%|█████████████▏  | 1007/1218 [1:25:08<01:51,  1.90it/s]
Batched comparisons:  83%|█████████████▏  | 1008/1218 [1:25:08<01:52,  1.87it/s]
Batched comparisons:  83%|█████████████▎  | 1009/1218 [1:25:09<01:51,  1.88it/s]
Batched comparisons:  83%|█████████████▎  | 1010/1218 [1:25:10<02:10,  1.59it/s]
Batched comparisons:  83%|█████████████▎  | 1011/1218 [1:25:10<02:01,  1.70it/s]
Batched comparisons:  83%|█████████████▎  | 1012/1218 [1:25:11<01:56,  1.77it/s]
Batched comparisons:  83%|█████████████▎  | 1013/1218 [1:25:11<01:52,  1.82it/s]
Batched comparisons:  83%|█████████████▎  | 1014/1218 [1:25:12<01:49,  1.87it/s]
Batched comparisons:  83%|█████████████▎  | 1015/1218 [1:25:12<01:44,  1.95it/s]
Batched comparisons:  83%|█████████████▎  | 1016/1218 [1:25:13<01:42,  1.97it/s]
Batched comparisons:  83%|█████████████▎  | 1017/1218 [1:25:13<01:44,  1.92it/s]
Batched comparisons:  84%|█████████████▎  | 1018/1218 [1:25:14<01:43,  1.93it/s]
Batched comparisons:  84%|█████████████▍  | 1019/1218 [1:25:14<01:42,  1.93it/s]
Batched comparisons:  84%|█████████████▍  | 1020/1218 [1:25:15<01:38,  2.01it/s]
Batched comparisons:  84%|█████████████▍  | 1021/1218 [1:25:15<01:38,  2.00it/s]
Batched comparisons:  84%|█████████████▍  | 1022/1218 [1:25:16<01:39,  1.98it/s]
Batched comparisons:  84%|█████████████▍  | 1023/1218 [1:25:16<01:42,  1.91it/s]
Batched comparisons:  84%|█████████████▍  | 1024/1218 [1:25:17<01:41,  1.90it/s]
Batched comparisons:  84%|█████████████▍  | 1025/1218 [1:25:17<01:42,  1.88it/s]
Batched comparisons:  84%|█████████████▍  | 1026/1218 [1:25:18<01:41,  1.89it/s]
Batched comparisons:  84%|█████████████▍  | 1027/1218 [1:25:18<01:39,  1.92it/s]
Batched comparisons:  84%|█████████████▌  | 1028/1218 [1:25:19<01:37,  1.96it/s]
Batched comparisons:  84%|█████████████▌  | 1029/1218 [1:25:19<01:39,  1.90it/s]
Batched comparisons:  85%|█████████████▌  | 1030/1218 [1:25:20<01:41,  1.86it/s]
Batched comparisons:  85%|█████████████▌  | 1031/1218 [1:25:21<01:41,  1.83it/s]
Batched comparisons:  85%|█████████████▌  | 1032/1218 [1:25:21<01:44,  1.77it/s]
Batched comparisons:  85%|█████████████▌  | 1033/1218 [1:25:22<01:44,  1.77it/s]
Batched comparisons:  85%|█████████████▌  | 1034/1218 [1:25:22<01:43,  1.78it/s]
Batched comparisons:  85%|█████████████▌  | 1035/1218 [1:25:23<01:42,  1.78it/s]
Batched comparisons:  85%|█████████████▌  | 1036/1218 [1:25:24<01:51,  1.63it/s]
Batched comparisons:  85%|█████████████▌  | 1037/1218 [1:25:24<01:45,  1.71it/s]
Batched comparisons:  85%|█████████████▋  | 1038/1218 [1:25:25<01:43,  1.73it/s]
Batched comparisons:  85%|█████████████▋  | 1039/1218 [1:25:25<01:43,  1.73it/s]
Batched comparisons:  85%|█████████████▋  | 1040/1218 [1:25:26<01:43,  1.72it/s]
Batched comparisons:  85%|█████████████▋  | 1041/1218 [1:25:26<01:45,  1.68it/s]
Batched comparisons:  86%|█████████████▋  | 1042/1218 [1:25:27<01:50,  1.59it/s]
Batched comparisons:  86%|█████████████▋  | 1043/1218 [1:25:28<01:50,  1.58it/s]
Batched comparisons:  86%|█████████████▋  | 1044/1218 [1:25:28<01:50,  1.57it/s]
Batched comparisons:  86%|█████████████▋  | 1045/1218 [1:25:29<01:49,  1.58it/s]
Batched comparisons:  86%|█████████████▋  | 1046/1218 [1:25:30<01:47,  1.61it/s]
Batched comparisons:  86%|█████████████▊  | 1047/1218 [1:25:30<01:48,  1.58it/s]
Batched comparisons:  86%|█████████████▊  | 1048/1218 [1:25:31<01:48,  1.57it/s]
Batched comparisons:  86%|█████████████▊  | 1049/1218 [1:25:32<01:50,  1.53it/s]
Batched comparisons:  86%|█████████████▊  | 1050/1218 [1:25:32<01:52,  1.49it/s]
Batched comparisons:  86%|█████████████▊  | 1051/1218 [1:25:33<01:46,  1.56it/s]
Batched comparisons:  86%|█████████████▊  | 1052/1218 [1:25:34<01:52,  1.47it/s]
Batched comparisons:  86%|█████████████▊  | 1053/1218 [1:25:35<02:02,  1.35it/s]
Batched comparisons:  87%|█████████████▊  | 1054/1218 [1:25:35<01:57,  1.39it/s]
Batched comparisons:  87%|█████████████▊  | 1055/1218 [1:25:36<01:49,  1.49it/s]
Batched comparisons:  87%|█████████████▊  | 1056/1218 [1:25:37<01:52,  1.44it/s]
Batched comparisons:  87%|█████████████▉  | 1057/1218 [1:25:37<01:53,  1.42it/s]
Batched comparisons:  87%|█████████████▉  | 1058/1218 [1:25:38<01:46,  1.50it/s]
Batched comparisons:  87%|█████████████▉  | 1059/1218 [1:25:38<01:42,  1.55it/s]
Batched comparisons:  87%|█████████████▉  | 1060/1218 [1:25:40<02:30,  1.05it/s]
Batched comparisons:  87%|█████████████▉  | 1061/1218 [1:25:41<02:16,  1.15it/s]
Batched comparisons:  87%|█████████████▉  | 1062/1218 [1:25:41<02:04,  1.25it/s]
Batched comparisons:  87%|█████████████▉  | 1063/1218 [1:25:42<01:54,  1.36it/s]
Batched comparisons:  87%|█████████████▉  | 1064/1218 [1:25:43<01:42,  1.50it/s]
Batched comparisons:  87%|█████████████▉  | 1065/1218 [1:25:43<01:40,  1.52it/s]
Batched comparisons:  88%|██████████████  | 1066/1218 [1:25:44<01:33,  1.62it/s]

Batched comparisons:  88%|██████████████  | 1067/1218 [1:25:44<01:29,  1.68it/s]
Batched comparisons:  88%|██████████████  | 1068/1218 [1:25:45<01:23,  1.79it/s]
Batched comparisons:  88%|██████████████  | 1069/1218 [1:25:45<01:23,  1.79it/s]
Batched comparisons:  88%|██████████████  | 1070/1218 [1:25:46<01:23,  1.76it/s]
Batched comparisons:  88%|██████████████  | 1071/1218 [1:25:47<01:27,  1.67it/s]
Batched comparisons:  88%|██████████████  | 1072/1218 [1:25:47<01:24,  1.73it/s]
Batched comparisons:  88%|██████████████  | 1073/1218 [1:25:48<01:23,  1.73it/s]
Batched comparisons:  88%|██████████████  | 1074/1218 [1:25:48<01:21,  1.76it/s]
Batched comparisons:  88%|██████████████  | 1075/1218 [1:25:49<01:22,  1.72it/s]
Batched comparisons:  88%|██████████████▏ | 1076/1218 [1:25:49<01:20,  1.77it/s]
Batched comparisons:  88%|██████████████▏ | 1077/1218 [1:25:50<01:21,  1.73it/s]
Batched comparisons:  89%|██████████████▏ | 1078/1218 [1:25:50<01:20,  1.75it/s]
Batched comparisons:  89%|██████████████▏ | 1079/1218 [1:25:51<01:19,  1.76it/s]
Batched comparisons:  89%|██████████████▏ | 1080/1218 [1:25:52<01:18,  1.76it/s]
Batched comparisons:  89%|██████████████▏ | 1081/1218 [1:25:52<01:13,  1.86it/s]
Batched comparisons:  89%|██████████████▏ | 1082/1218 [1:25:53<01:15,  1.81it/s]
Batched comparisons:  89%|██████████████▏ | 1083/1218 [1:25:53<01:14,  1.82it/s]
Batched comparisons:  89%|██████████████▏ | 1084/1218 [1:25:54<01:12,  1.85it/s]
Batched comparisons:  89%|██████████████▎ | 1085/1218 [1:25:54<01:09,  1.90it/s]
Batched comparisons:  89%|██████████████▎ | 1086/1218 [1:25:55<01:09,  1.90it/s]
Batched comparisons:  89%|██████████████▎ | 1087/1218 [1:25:55<01:13,  1.79it/s]
Batched comparisons:  89%|██████████████▎ | 1088/1218 [1:25:56<01:08,  1.89it/s]
Batched comparisons:  89%|██████████████▎ | 1089/1218 [1:25:56<01:08,  1.89it/s]
Batched comparisons:  89%|██████████████▎ | 1090/1218 [1:25:57<01:07,  1.90it/s]
Batched comparisons:  90%|██████████████▎ | 1091/1218 [1:25:57<01:07,  1.89it/s]
Batched comparisons:  90%|██████████████▎ | 1092/1218 [1:25:58<01:07,  1.88it/s]
Batched comparisons:  90%|██████████████▎ | 1093/1218 [1:25:59<01:07,  1.86it/s]
Batched comparisons:  90%|██████████████▎ | 1094/1218 [1:25:59<01:07,  1.85it/s]
Batched comparisons:  90%|██████████████▍ | 1095/1218 [1:26:00<01:07,  1.83it/s]
Batched comparisons:  90%|██████████████▍ | 1096/1218 [1:26:00<01:06,  1.83it/s]
Batched comparisons:  90%|██████████████▍ | 1097/1218 [1:26:01<01:05,  1.86it/s]
Batched comparisons:  90%|██████████████▍ | 1098/1218 [1:26:01<01:03,  1.89it/s]
Batched comparisons:  90%|██████████████▍ | 1099/1218 [1:26:02<01:25,  1.40it/s]
Batched comparisons:  90%|██████████████▍ | 1100/1218 [1:26:04<01:48,  1.09it/s]
Batched comparisons:  90%|██████████████▍ | 1101/1218 [1:26:05<01:55,  1.01it/s]
Batched comparisons:  90%|██████████████▍ | 1102/1218 [1:26:07<02:25,  1.26s/it]
Batched comparisons:  91%|██████████████▍ | 1103/1218 [1:26:08<02:22,  1.24s/it]
Batched comparisons:  91%|██████████████▌ | 1104/1218 [1:26:09<02:17,  1.20s/it]
Batched comparisons:  91%|██████████████▌ | 1105/1218 [1:26:10<02:17,  1.21s/it]
Batched comparisons:  91%|██████████████▌ | 1106/1218 [1:26:12<02:19,  1.25s/it]
Batched comparisons:  91%|██████████████▌ | 1107/1218 [1:26:13<02:33,  1.38s/it]
Batched comparisons:  91%|██████████████▌ | 1108/1218 [1:26:16<03:08,  1.72s/it]
Batched comparisons:  91%|██████████████▌ | 1109/1218 [1:26:18<03:05,  1.70s/it]
Batched comparisons:  91%|██████████████▌ | 1110/1218 [1:26:19<03:03,  1.70s/it]
Batched comparisons:  91%|██████████████▌ | 1111/1218 [1:26:21<02:51,  1.60s/it]
Batched comparisons:  91%|██████████████▌ | 1112/1218 [1:26:22<02:34,  1.46s/it]
Batched comparisons:  91%|██████████████▌ | 1113/1218 [1:26:23<02:43,  1.55s/it]
Batched comparisons:  91%|██████████████▋ | 1114/1218 [1:26:24<02:11,  1.27s/it]
Batched comparisons:  92%|██████████████▋ | 1115/1218 [1:26:25<01:49,  1.06s/it]
Batched comparisons:  92%|██████████████▋ | 1116/1218 [1:26:25<01:37,  1.05it/s]
Batched comparisons:  92%|██████████████▋ | 1117/1218 [1:26:26<01:23,  1.21it/s]
Batched comparisons:  92%|██████████████▋ | 1118/1218 [1:26:26<01:15,  1.32it/s]
Batched comparisons:  92%|██████████████▋ | 1119/1218 [1:26:27<01:07,  1.46it/s]
Batched comparisons:  92%|██████████████▋ | 1120/1218 [1:26:28<01:04,  1.53it/s]
Batched comparisons:  92%|██████████████▋ | 1121/1218 [1:26:28<01:02,  1.55it/s]
Batched comparisons:  92%|██████████████▋ | 1122/1218 [1:26:29<01:04,  1.48it/s]
Batched comparisons:  92%|██████████████▊ | 1123/1218 [1:26:30<01:07,  1.41it/s]
Batched comparisons:  92%|██████████████▊ | 1124/1218 [1:26:30<01:03,  1.47it/s]
Batched comparisons:  92%|██████████████▊ | 1125/1218 [1:26:31<01:06,  1.41it/s]
Batched comparisons:  92%|██████████████▊ | 1126/1218 [1:26:32<01:01,  1.49it/s]
Batched comparisons:  93%|██████████████▊ | 1127/1218 [1:26:32<01:00,  1.50it/s]
Batched comparisons:  93%|██████████████▊ | 1128/1218 [1:26:33<01:11,  1.26it/s]
Batched comparisons:  93%|██████████████▊ | 1129/1218 [1:26:35<01:35,  1.07s/it]
Batched comparisons:  93%|██████████████▊ | 1130/1218 [1:26:36<01:36,  1.09s/it]
Batched comparisons:  93%|██████████████▊ | 1131/1218 [1:26:38<01:38,  1.13s/it]
Batched comparisons:  93%|██████████████▊ | 1132/1218 [1:26:39<01:37,  1.13s/it]
Batched comparisons:  93%|██████████████▉ | 1133/1218 [1:26:40<01:38,  1.16s/it]
Batched comparisons:  93%|██████████████▉ | 1134/1218 [1:26:41<01:43,  1.24s/it]
Batched comparisons:  93%|██████████████▉ | 1135/1218 [1:26:44<02:10,  1.58s/it]
Batched comparisons:  93%|██████████████▉ | 1136/1218 [1:26:45<02:09,  1.58s/it]
Batched comparisons:  93%|██████████████▉ | 1137/1218 [1:26:47<02:09,  1.60s/it]
Batched comparisons:  93%|██████████████▉ | 1138/1218 [1:26:48<02:00,  1.50s/it]
Batched comparisons:  94%|██████████████▉ | 1139/1218 [1:26:49<01:47,  1.36s/it]
Batched comparisons:  94%|██████████████▉ | 1140/1218 [1:26:51<01:52,  1.44s/it]
Batched comparisons:  94%|██████████████▉ | 1141/1218 [1:26:52<01:33,  1.22s/it]
Batched comparisons:  94%|███████████████ | 1142/1218 [1:26:52<01:17,  1.03s/it]
Batched comparisons:  94%|███████████████ | 1143/1218 [1:26:53<01:06,  1.12it/s]
Batched comparisons:  94%|███████████████ | 1144/1218 [1:26:53<00:57,  1.28it/s]
Batched comparisons:  94%|███████████████ | 1145/1218 [1:26:54<00:52,  1.38it/s]
Batched comparisons:  94%|███████████████ | 1146/1218 [1:26:54<00:50,  1.44it/s]
Batched comparisons:  94%|███████████████ | 1147/1218 [1:26:55<00:51,  1.38it/s]
Batched comparisons:  94%|███████████████ | 1148/1218 [1:26:56<00:49,  1.43it/s]
Batched comparisons:  94%|███████████████ | 1149/1218 [1:26:57<00:47,  1.45it/s]
Batched comparisons:  94%|███████████████ | 1150/1218 [1:26:57<00:45,  1.51it/s]
Batched comparisons:  94%|███████████████ | 1151/1218 [1:26:58<00:42,  1.57it/s]
Batched comparisons:  95%|███████████████▏| 1152/1218 [1:26:58<00:41,  1.58it/s]
Batched comparisons:  95%|███████████████▏| 1153/1218 [1:27:00<01:08,  1.06s/it]
Batched comparisons:  95%|███████████████▏| 1154/1218 [1:27:02<01:23,  1.30s/it]
Batched comparisons:  95%|███████████████▏| 1155/1218 [1:27:04<01:37,  1.54s/it]
Batched comparisons:  95%|███████████████▏| 1156/1218 [1:27:07<01:48,  1.74s/it]
Batched comparisons:  95%|███████████████▏| 1157/1218 [1:27:09<02:05,  2.06s/it]
Batched comparisons:  95%|███████████████▏| 1158/1218 [1:27:14<02:52,  2.87s/it]
Batched comparisons:  95%|███████████████▏| 1159/1218 [1:27:17<02:52,  2.93s/it]
Batched comparisons:  95%|███████████████▏| 1160/1218 [1:27:20<02:53,  2.99s/it]
Batched comparisons:  95%|███████████████▎| 1161/1218 [1:27:23<02:40,  2.82s/it]
Batched comparisons:  95%|███████████████▎| 1162/1218 [1:27:25<02:22,  2.55s/it]
Batched comparisons:  95%|███████████████▎| 1163/1218 [1:27:29<02:43,  2.97s/it]

Batched comparisons:  96%|███████████████▎| 1164/1218 [1:27:29<02:03,  2.28s/it]
Batched comparisons:  96%|███████████████▎| 1165/1218 [1:27:30<01:35,  1.80s/it]
Batched comparisons:  96%|███████████████▎| 1166/1218 [1:27:31<01:16,  1.47s/it]
Batched comparisons:  96%|███████████████▎| 1167/1218 [1:27:32<01:04,  1.26s/it]
Batched comparisons:  96%|███████████████▎| 1168/1218 [1:27:33<00:59,  1.20s/it]
Batched comparisons:  96%|███████████████▎| 1169/1218 [1:27:33<00:53,  1.09s/it]
Batched comparisons:  96%|███████████████▎| 1170/1218 [1:27:34<00:48,  1.01s/it]
Batched comparisons:  96%|███████████████▍| 1171/1218 [1:27:35<00:42,  1.10it/s]
Batched comparisons:  96%|███████████████▍| 1172/1218 [1:27:36<00:38,  1.19it/s]
Batched comparisons:  96%|███████████████▍| 1173/1218 [1:27:36<00:37,  1.18it/s]
Batched comparisons:  96%|███████████████▍| 1174/1218 [1:27:37<00:32,  1.35it/s]
Batched comparisons:  96%|███████████████▍| 1175/1218 [1:27:37<00:28,  1.48it/s]
Batched comparisons:  97%|███████████████▍| 1176/1218 [1:27:38<00:26,  1.58it/s]
Batched comparisons:  97%|███████████████▍| 1177/1218 [1:27:39<00:25,  1.62it/s]
Batched comparisons:  97%|███████████████▍| 1178/1218 [1:27:39<00:23,  1.69it/s]
Batched comparisons:  97%|███████████████▍| 1179/1218 [1:27:40<00:21,  1.79it/s]
Batched comparisons:  97%|███████████████▌| 1180/1218 [1:27:40<00:20,  1.83it/s]
Batched comparisons:  97%|███████████████▌| 1181/1218 [1:27:41<00:19,  1.87it/s]
Batched comparisons:  97%|███████████████▌| 1182/1218 [1:27:41<00:19,  1.86it/s]
Batched comparisons:  97%|███████████████▌| 1183/1218 [1:27:42<00:21,  1.63it/s]
Batched comparisons:  97%|███████████████▌| 1184/1218 [1:27:43<00:23,  1.43it/s]
Batched comparisons:  97%|███████████████▌| 1185/1218 [1:27:44<00:29,  1.11it/s]
Batched comparisons:  97%|███████████████▌| 1186/1218 [1:27:45<00:29,  1.09it/s]
Batched comparisons:  97%|███████████████▌| 1187/1218 [1:27:46<00:28,  1.09it/s]
Batched comparisons:  98%|███████████████▌| 1188/1218 [1:27:47<00:26,  1.12it/s]
Batched comparisons:  98%|███████████████▌| 1189/1218 [1:27:48<00:24,  1.18it/s]
Batched comparisons:  98%|███████████████▋| 1190/1218 [1:27:49<00:24,  1.13it/s]
Batched comparisons:  98%|███████████████▋| 1191/1218 [1:27:50<00:25,  1.07it/s]
Batched comparisons:  98%|███████████████▋| 1192/1218 [1:27:51<00:28,  1.10s/it]
Batched comparisons:  98%|███████████████▋| 1193/1218 [1:27:52<00:27,  1.10s/it]
Batched comparisons:  98%|███████████████▋| 1194/1218 [1:27:53<00:26,  1.11s/it]
Batched comparisons:  98%|███████████████▋| 1195/1218 [1:27:54<00:24,  1.05s/it]
Batched comparisons:  98%|███████████████▋| 1196/1218 [1:27:55<00:21,  1.02it/s]
Batched comparisons:  98%|███████████████▋| 1197/1218 [1:27:56<00:21,  1.04s/it]
Batched comparisons:  98%|███████████████▋| 1198/1218 [1:27:59<00:31,  1.57s/it]
Batched comparisons:  98%|███████████████▊| 1199/1218 [1:28:01<00:32,  1.68s/it]
Batched comparisons:  99%|███████████████▊| 1200/1218 [1:28:03<00:31,  1.77s/it]
Batched comparisons:  99%|███████████████▊| 1201/1218 [1:28:05<00:29,  1.71s/it]
Batched comparisons:  99%|███████████████▊| 1202/1218 [1:28:06<00:25,  1.58s/it]
Batched comparisons:  99%|███████████████▊| 1203/1218 [1:28:08<00:25,  1.73s/it]
Batched comparisons:  99%|███████████████▊| 1204/1218 [1:28:13<00:36,  2.60s/it]
Batched comparisons:  99%|███████████████▊| 1205/1218 [1:28:18<00:43,  3.31s/it]
Batched comparisons:  99%|███████████████▊| 1206/1218 [1:28:21<00:40,  3.40s/it]
Batched comparisons:  99%|███████████████▊| 1207/1218 [1:28:24<00:35,  3.22s/it]
Batched comparisons:  99%|███████████████▊| 1208/1218 [1:28:29<00:37,  3.79s/it]
Batched comparisons:  99%|███████████████▉| 1209/1218 [1:28:31<00:30,  3.37s/it]
Batched comparisons:  99%|███████████████▉| 1210/1218 [1:28:33<00:23,  2.92s/it]
Batched comparisons:  99%|███████████████▉| 1211/1218 [1:28:35<00:17,  2.49s/it]
Batched comparisons: 100%|███████████████▉| 1212/1218 [1:28:37<00:14,  2.49s/it]
Batched comparisons: 100%|███████████████▉| 1213/1218 [1:28:39<00:11,  2.33s/it]
Batched comparisons: 100%|███████████████▉| 1214/1218 [1:28:41<00:08,  2.10s/it]
Batched comparisons: 100%|███████████████▉| 1215/1218 [1:28:43<00:06,  2.25s/it]
Batched comparisons: 100%|███████████████▉| 1216/1218 [1:28:44<00:03,  1.87s/it]
Batched comparisons: 100%|███████████████▉| 1217/1218 [1:28:46<00:01,  1.77s/it]
Batched comparisons: 100%|████████████████| 1218/1218 [1:28:47<00:00,  4.37s/it]

Finished all comparisons. Final results saved to: ../figures/parallel_counts_exhaustive.xlsx